src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Select.jsx
src/js/jsx/shared/TextInput.jsx
src/style/search/search-bar.less

Search bar click handling

---

src/js/jsx/shared/Select.jsx

Set key for Headers in Select

---

src/js/actions/tools.js
src/js/tools/ellipse.js
src/js/tools/rectangle.js

fix shape defaults to not overwrite selected shape properties

---

src/js/jsx/shared/TextInput.jsx

Fix layer renaming

---

src/js/actions/documents.js

Helps alleviate #765 symptoms, but not fully.
Probably shouldn't have had trim_trailing_whitespace_on_save
Requires Adapter#109

Replace performMenuCommand(1016) with an API

---

src/js/jsx/search/SearchBar.jsx

Reverse layer order in search

---

src/js/actions/tools.js

 fix for issue 1641 dont call select on empty layer set

---

src/static/menu-mac.json
src/static/menu-win.json

Added shortcut for toggling guides:  
``cmd + ; (MAC)``
``ctrl + ; (WIN)``

Add shortcut for toggling guides.

---

src/js/actions/layers.js

During shape edit / pen tool, `resetBounds` would fail if you pressed delete fast enough to delete all the points that layer would get deleted. We would try to `batchGet` bounds of a layer that doesn't exist.
Reset bounds is an updater, and I think it's ok for it to be failsafe.
Addresses #1191

Don't fail resetBounds if the batchGet fails

---

Gruntfile.js
package.json

This would have prevented #1663.

Lint JSON files with Grunt

---

src/js/actions/ui.js
src/js/jsx/Toolbar.jsx

Correctly update the pinned toolbar width

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Select.jsx
src/style/shared/select.less

Only displays the ancestry if the layer name is not unique, but you can always search using the ancestry (even if it isn't displayed).

Search by layer ancestry and for recent documents in search dialog

---

src/js/jsx/sections/layers/LayerFace.jsx
src/nls/root/strings.js

Tooltip for Artboards should be 'Artboard'

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/SVGIcon.jsx
src/js/jsx/shared/Select.jsx
src/js/jsx/shared/TextInput.jsx
src/js/util/svg.js
src/nls/root/strings.js
src/style/search/search-bar.less
src/style/shared/dialog.less
src/style/shared/select.less

Use tab or enter to select filter option. The filter appears as an svg when you confirm it.
Added autofill of text, other design changes.
Some filters don't have svgs associated with them currently so there is a rectangle placeholder.

Search using filters for layer or document type

---

src/style/sections/layers/face.less

When dragging layers, use the grabbing cursor

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx

for issues #1703, #1704, #1705

Fix errors with Datalist tabbing/clicking

---

src/js/actions/layers.js

Cory, if you have time can you take a look at this validation error and see if you have any thoughts

add selection after duplication

---

src/js/jsx/sections/layers/LayerFace.jsx

Looking for the wrong class

---

src/js/jsx/sections/layers/LayerFace.jsx

And apparently the solution to #1710 is non-obvious

Switching back to state before #1723 because it broke everything.

---

src/js/actions/ui.js
src/static/menu-mac.json

This PR fixed issues #1628 and #1626.

zoom-in shortcut: match standard PS and support numeric keyboard

---

src/js/actions/ui.js
src/static/menu-win.json

Bug fix: fix the wrong modifier for windows.

---

src/js/actions/libraries.js
src/js/events.js
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/jsx/sections/libraries/assets/CharacterStyle.jsx
src/js/jsx/sections/libraries/assets/LayerStyle.jsx
src/js/stores/font.js
src/js/stores/library.js

- Create character style asset
- Create layer style asset
- Create color asset
- Apply layer style to selected layer action
- Apply text style to selected layer action
With these, all the low level interactions between cc-libraries-api <=> Design Space <=> Photoshop should be ready for hooking up.

More CC Library - Design Space interactions

---

src/img/ico-layer-delete.svg
src/js/actions/layereffects.js
src/js/events.js
src/js/jsx/sections/style/Shadow.jsx
src/js/models/layer.js
src/js/models/layerstructure.js
src/js/models/shadow.js
src/js/stores/document.js
src/nls/root/strings.js
src/style/sections/style/style-section.less
src/style/shared/icons.less

(This PR requires https://github.com/adobe-photoshop/spaces-adapter/pull/120 to work)

Layer Effects: Support deleting layer effects

---

src/js/actions/search/layers.js
src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Select.jsx
src/js/stores/search.js
src/js/util/svg.js
src/nls/root/strings.js

Addresses
1. Too many layer filters: issue #1737, #1736, and @chadrolfs comments about filters on PR #1702
2. #1735: for this I added an unselectable dropdown option that says there are no options available.
3. #1719

Lots of little searching bugs!

---

src/js/actions/superselect.js
src/js/jsx/sections/transform/Position.jsx
src/js/jsx/sections/transform/Size.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/models/layerstructure.js

Let artboard name badges be cmd+clickable, but not artboards

---

src/static/menu-actions.json

Add have-document rule to cut/copy/paste

---

src/js/jsx/sections/layers/LayerFace.jsx

Re-render LayerFace elements when their depth changes

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx

Fix search filtering

---

src/js/actions/documents.js
src/js/actions/layers.js
src/js/actions/menu.js
src/js/actions/search/menucommands.js
src/js/jsx/Search.jsx
src/js/jsx/search/SearchBar.jsx
src/js/stores/search.js
src/js/util/key.js
src/nls/root/strings.js

Search for menu commands. When a command confirmed, it perform its corresponding action.

Add menu commands to application search

---

src/js/jsx/Search.jsx

@iwehrman was not missing something.
Issue #1805

Fix confirming search item

---

src/js/jsx/DocumentHeader.jsx
src/js/jsx/DocumentHeaderTab.jsx
src/style/document-header.less
src/style/toolbar.less

Review only as I need: 
a) @placegraphichere to look at it
b) @iwehrman (or someone) to let me know if we have anything for "all documents have loaded" as right now, I need to re-render the header every time a new document is parsed (and the application store changes)

Added Tabs for Document Header instead of past switching style

---

src/js/actions/dialog.js
src/js/actions/history.js
src/js/actions/menu.js
src/js/actions/policy.js
src/js/actions/shortcuts.js
src/js/actions/tools.js
src/js/actions/type.js
src/js/actions/ui.js
src/js/jsx/mixin/Focusable.js
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/style/Type.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/NumberInput.jsx
src/js/jsx/shared/TextInput.jsx
src/js/models/characterstyle.js
src/js/models/layerstructure.js
src/js/models/paragraphstyle.js
src/js/models/text.js
src/js/stores/document.js
src/js/tools/type.js
src/nls/root/strings.js

the known issues have been resolved. have at it

Allow text tool to work in modal state

---

src/js/jsx/sections/layers/LayersPanel.jsx
src/js/stores/dialog.js

This is the same change as #1820, but against master. Please test both places before merging. 
Also addresses #1819.

Disallow reordering groups below themselves

---

src/js/jsx/PanelSet.jsx

Fix for close document error

---

src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/jsx/sections/style/Fill.jsx
src/js/jsx/sections/style/Stroke.jsx
src/js/jsx/shared/ColorInput.jsx
src/js/models/color.js

Bug fix for #1776, handle the following cases:
* select multiple layer with different fill color: style panel shows mixed color (used to show black color)
* select multiple layer with different stroke color: style panel shows mixed stoke color (used to show the stroke color of the first layer)

Bug fix: Mixed state is inconsistent

---

src/js/jsx/PanelSet.jsx

Update the calculation of the cloak bounds at the right time

Fixes cloaking issue

---

src/js/jsx/sections/layers/LayersPanel.jsx

1. Fix a bug that prevented artboards from being reordered, as reported in #1831.
2. Change the semantics of dropping "below" groups such that dropping below an open group places it inside the group at the top of that group, and dropping below a closed group places it after the group.
As with all layers panel drag-and-drop changes, I have only limited confidence that I haven't broken something. Please test if possible, @chadrolfs.
Addresses #1831.

More layer group drag-and-drop fixes

---

src/js/actions/layers.js

Addresses #1849, lock I've forgotten during the transform work.

Add resetPolicy locks to layers.selectAll

---

src/js/jsx/shared/Datalist.jsx

Ian is concerned about the model getting out of sync within the data list and our selection jumping around here. so i'm sending this over to him to verify if his concerns are well founded.

make datalists update based on the model

---

src/js/jsx/shared/TextInput.jsx
src/js/models/menubar.js
src/js/stores/dialog.js
src/js/stores/menu.js
src/static/menu-actions.json

Addresses issue #1551 and @placegraphichere's request to be able to select all (cmd-A) in the search bar.

Allow copy, cut, paste, and select all in search bar

---

src/js/actions/index.js
src/js/actions/layereffects.js
src/js/actions/sampler.js
src/js/actions/superselect.js
src/js/events.js
src/js/jsx/Toolbar.jsx
src/js/jsx/sections/style/Shadow.jsx
src/js/jsx/tools/SamplerOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/models/layerstructure.js
src/js/stores/document.js
src/js/stores/tool.js
src/js/tools/sampler.js
src/js/util/ui.js
src/style/main.less
src/style/tools/sampler.less

Styles Workflow Card 1 - Sampler tool to modify layer color
- Click on a source layer and grab it's color:
- Text layer: text color, layer opacity
- Shape layer: Fill color, fill opacity
- Other: Pixel color at the value, layer opacity
- And apply it to selected layers:
- Type layers: Type color and layer opacity
- Shape layers: Fill color, fill opacity
- Other: no op
Styles Workflow Card 2 - Shift modifier to sample layer FX
- Shift click on a source layer to copy all styles from that layer and apply the whole set to the selected layers. Existing effects will be deleted.

Styles Workflow 1 - Sampler Tool

---

src/js/jsx/DocumentHeader.jsx
src/js/jsx/DocumentHeaderTab.jsx
src/style/document-header.less
src/style/shared/colors.less

@placegraphichere and I made some changes to the tabs
1. They shift to "small tabs" sooner (so you can see more of the filename
2. The filename expands when you hover over the non-active tab
3. The colors are updated

Document Tab Updates

---

src/js/actions/superselect.js

The associated hotfix was #1847

Porting a release hotfix to master to prevent future merge conflicts

---

src/js/jsx/Main.jsx
src/style/panel.less
src/style/search/search-bar.less
src/style/sections/layers/face.less
src/style/sections/layers/layers-section.less
src/style/shared/dialog.less
src/style/shared/typeface-list.less

Changes the class of main based on how many panels are open. Left margin of search bar changes based on that class.
@designedbyscience Is this along the lines of what you were suggesting?
issue #1892

Center the search bar, no matter how many panels are open

---

src/js/jsx/help/KeyboardShortcuts.jsx
src/nls/root/strings.js

Well... one bug #1872 
@iwehrman is fixing the tooltip bug.

Add Sampler to KBSC dialog

---

src/js/actions/layers.js
src/js/models/layer.js
src/js/models/menubar.js
src/nls/root/strings.js
src/static/menu-actions.json
src/static/menu-mac.json
src/static/menu-win.json

has accompanying PR https://github.com/adobe-photoshop/spaces-adapter/pull/127

add keyboard shortcut and menu item to edit vector masks on layers

---

src/js/jsx/sections/style/Type.jsx

fix for transparancy retention

---

src/js/tools/type.js

fix for undefined case in deselect handler

---

src/js/models/menubar.js

clear template menu before appending new templates

---

src/js/actions/superselect.js

This changes the implementation of layer drag-copy to use `layers.addLayers` instead of `documents.updateDocument`. The former is much faster than the latter. It relies on a new event added to Photoshop a few weeks back by @isonno. 
Addresses #882.

Faster layer drag-copy

---

src/js/actions/libraries.js

Fix for #1944. @volfied Thank you for reviewing again.

Add missing transfer declaration in libraries.createLayerFromElement

---

src/js/jsx/DocumentHeaderTab.jsx

No more title attribute on Document Tabs

---

src/js/jsx/sections/style/StylePanel.jsx

Prevent double click propagation on style buttons

---

src/js/actions/superselect.js

Ignore non-superselectable layers for getContainingLayerBounds

---

src/js/actions/libraries.js

Will address #1862. When we're trying to place a graphic element into the PS document, we go through it's representations to find one PS will accept. In .shape files, this is the PDF format.

Find placable representation for image elements

---

src/js/actions/documents.js

Disable overlays during document switch

---

src/js/actions/ui.js

Zoom with increments

---

src/js/jsx/sections/style/Fill.jsx
src/js/models/layerstructure.js

Addresses #2076 and #2077, casualties of a refactor.

Preserve fill color on toggle enabled

---

src/js/actions/export.js
src/js/stores/menu.js

depends on https://github.com/adobe-photoshop/spaces-adapter/pull/133

During start up, ensure that generator is enabled.  Forcibly start it if necessary.

---

src/js/jsx/sections/export/ExportPanel.jsx
src/js/jsx/sections/style/StylePanel.jsx
src/style/panel.less
src/style/sections/layers/layers-section.less
src/style/sections/libraries/libraries-section.less

Makes panel expansion more sane, also addresses #2050

Updates to expand/collapse behavior

---

src/js/actions/guides.js

Nullify the guide policy before returning

---

src/style/shared/number-input.less

Signifies they are not active
Regarding #1462

Took away the blue hover on disabled inputs

---

src/js/actions/sampler.js
src/js/jsx/tools/SamplerOverlay.jsx

Addresses #2135, @iwehrman please review.

When sampling stroke, apply the whole stroke to shape layers

---

src/js/stores/menu.js

Update menu items on guide creation/deletion

---

src/js/actions/tools.js

Changed the event policy for SHIFT to send events to Ds. Regarding issue #2069

Fixed the shift clicking to select any layer that is clicked on

---

src/img/ico-color-picker-no-color.svg
src/js/jsx/shared/ColorPicker.jsx
src/nls/root/strings.json
src/style/shared/color-picker.less

First stab at redesign of the color picker

First stab at redesign of the color picker

---

src/js/jsx/PanelSet.jsx
src/style/panel.less
src/style/shared/link-list.less

- hover, select states for recent/new files
- removed section border on last child
- added column for exiting Ds from null state

null state improvements

---

src/js/jsx/tools/GuidesOverlay.jsx

Avoid guides overlay draw debouncing to prevent blinking

---

src/js/actions/search/menucommands.js
src/style/document-header.less
src/style/help/first-launch.less
src/style/main.less
src/style/panel.less
src/style/search/search-bar.less
src/style/sections/exports/exports.less
src/style/shared/scrollbar.less
src/style/shared/select.less
src/style/shared/split-button.less
src/style/toolbar.less
src/style/tools/super-select.less

addresses #1992 
some search tweaks 
- larger font sizes
- brighter text overall
- removed parens on keyboard shortcut
- removed italics on sub-option info
- hover state brighter for sub-option info
- small padding change
- some clashes with the new colors fixup

Increase contrast between primary and secondary search info

---

src/js/actions/guides.js
src/js/jsx/tools/GuidesOverlay.jsx
src/js/stores/document.js
src/js/stores/ui.js

Depends on https://github.com/adobe-photoshop/spaces-adapter/pull/139
Addresses: #2131, #2171, and general guide edge performance.

Add guide deletion by dragging outside, error checking for guide functions, better hover highlighting

---

src/js/models/layerstructure.js

Create Artboard and Create Artboard from Template was freezing the UI after the second or third artboard was created and no other artboard was selected. Narrowed down the problem to a bug in Immutable that sent it into infinite loop. This PR accounts for that bug and now allows the creation of an artboard to handle both situations, when an artboard is selected and when it is not. This fixes the bug and prevents the freezing when creating an artboard. 
Regarding issue #1905

Adding artboards to a document without freezing

---

src/style/sections/libraries/libraries-section.less
src/style/shared/select.less

- Added an underline to "My Library" so that it signifies it is a datalist
Regarding #2108 
- Took away the bottom border for the title bar because it was looking too crowded with both the underline and the bottom border. Got designs from @davealonzo 
- Changed the height of the title to 5rem as per the design. Should we choose to add the bottom border again and take away the underline, the height of the top bar will still be the correct size. https://trello.com/c/jRlxiRui/491-design

Styling changes to the CC Libraries bar top

---

src/js/tools/superselect/type.js

What it says! Previously this only happened when the edits were committed, but not when canceled with `cmd-.`. 
Addresses #2256.

Activate select tool after canceling edits from type subtool

---

src/js/actions/guides.js
src/js/models/guide.js
src/js/stores/document.js

Requires pg-dev @1039042  #549. Jesper is reviewing the CL and will integrate to staging when it's done.

Use the new guide kind descriptor enum

---

src/js/jsx/tools/SuperselectOverlay.jsx

With all these policies flying around, it's hard to know when to highlight a layer or not... so I wrote this PR.
Addresses #1767

Don't highlight superselect layers under always_propagate policies

---

src/js/actions/libraries.js
src/js/actions/sampler.js
src/js/actions/type.js
src/js/stores/font.js

Also fixes applyTextStyle to do selection dance.
Addresses #2175,
Requires https://github.com/adobe-photoshop/spaces-adapter/pull/142
@iwehrman please review alongside 142

Create only the most common type properties for getTypeObjectFromLayer

---

src/js/jsx/tools/GuidesOverlay.jsx

@iwehrman please review since you opened the issue :)
Addresses #2317

Listen to html mousemove events for guides overlay

---

bower.json

In honor of facebook/immutable-js#602, here are some minor updates for third-party dependencies. I did some light testing, and I'm not aware of any changes in functionality relevant to our project.

Minor dependency version updates

---

src/style/sections/layers/face.less

match Ps layer nesting readability

---

src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/Library.jsx
src/style/panel.less
src/style/sections/libraries/libraries-section.less

fix for #2287, even though we won't use the messaging on export, we'll need this sometime, somewhere.

unify panel messaging appearance

---

src/nls/root/shortcuts-mac.json
src/nls/root/shortcuts-win.json
src/static/menu-mac.json
src/static/menu-win.json

Cmd-B on Mac, Ctrl-B on Windows, as chosen by @placegraphichere. 
Addresses #2215.

Create Artboard keyboard shortcut

---

src/js/actions/transform.js

For swap layers, we have an algorithm that calculates the offset of the two layers to be swapped, and applies that offset to EVERY layer that's child of the swapped layer. This takes quite a while, because we're asking PS to transform a whole bunch of layers. For artboards, we can skip this by just translating the artboard.
This helps swapping two artboards go from 2500 ms to 170 ms. Of course, if you swap two busy groups, it'll still take a long time, but that's much less common/expected than swapping two artboards.
Addresses #2231

Don't child calculate for artboard swap so it's faster

---

src/js/actions/export.js
src/js/actions/policy.js
src/js/stores/policy.js

...and then re-enabled them afterwards.

Disable keyboard policies while OS folder chooser is open

---

src/nls/de/menu.json
src/nls/de/strings.json
src/nls/fr/menu.json
src/nls/fr/strings.json
src/nls/ja/menu.json
src/nls/ja/strings.json

@volfied 
Please help to review and merge, thanks!

Updated by ALF automation.

---

src/js/actions/tools.js

Realized this breaks things on Windows.

Set correct policy modifier for borders on Win

---

src/js/jsx/tools/SuperselectOverlay.jsx

I always shied from doing this because I thought an async function in a mousemove handler would not look good...
Well, it's quite fast and works!
Adresses #2370

Use hitTest instead of bound comparison for superselect overlay

---

src/js/actions/search/libraries.js

Now that we have `openGraphicForEdit` action, we can actually quickly open library graphic assets to be edited in no-doc state. Other assets don't get listed.
Addresses #2211

Only allow library graphics to be listed/opened in no doc state

---

src/js/models/menubar.js
src/static/menu-actions.json

Low hanging fruit,a ddresses #1531.

Add no-artboards menu rule, and apply it to group menu item

---

src/style/search/search-bar.less
src/style/shared/select.less

select dropdown is shifting

---

src/js/actions/documents.js

Addresses #2392 so policies get cleaned up on doc close.

Reset policies on disposeDocument

---

src/js/jsx/sections/export/ExportAllPanel.jsx
src/js/jsx/sections/export/ExportPanel.jsx

Both the export panel, and the export all dialog...

Export Panel: Asset creation should be throttled, and the export button should be immediately disabled upon click

---

src/js/actions/export.js
src/js/actions/policy.js

Disabling policies (ie, temporarily during modal) now includes pointer policies

---

src/js/actions/layereffects.js
src/js/jsx/sections/style/BlendMode.jsx
src/js/jsx/sections/style/EffectsPanel.jsx
src/js/jsx/sections/style/LayerBlendMode.jsx
src/js/jsx/sections/style/Shadow.jsx
src/js/jsx/sections/style/Type.jsx
src/js/jsx/sections/style/VectorFill.jsx
src/nls/root/strings.json
src/style/main.less
src/style/panel.less
src/style/sections/style/shadow.less
src/style/sections/style/style-section.less
src/style/shared/color-input.less
src/style/shared/dialog.less
src/style/shared/drop-down.less
src/style/shared/title-header.less

Also, added Blendmodes to effects
Created a new component for general BlendMode listing, and then renamed the old BlendMode component to be LayerBlendMode
Added a little popover dialog instead of using the Select or Datalist component for the action of adding a new effect

Updated UI for Effects list.

---

src/js/jsx/shared/Select.jsx

@iwehrman Please review...
I created a snippet to test this as well, and tested with: empty list, one element list with existing, one element list with an non existing, your font list with repro case, run it 0-n for ranges of n...
Will address #2438 and hopefully put out the fire.

Fix binary search from infinite loop

---

src/js/jsx/sections/style/Type.jsx
src/style/shared/color-input.less

Set font size as fixed for type swatch, so we can always see it

---

src/style/sections/layers/face.less

- hover for layers on item box, not just title input
- rename look following new libraries tweaks and spectrum spec

hover accuracy, focus state spectrum look

---

src/js/actions/libraries.js

Fix for my mistake in the last PR.  #2449

CC Lib: fix placing graphic asset.

---

src/js/jsx/mixin/Focusable.js

1. Don't install keyboard policies on focus unless we're in a modal state.
2. Don't install keyboard policies more than once.
Fixes the extreme brokenness in #2454, although not _all_ the focus issues are resolved.

Modal type keyboard policy fixes

---

src/style/panel.less

Added scrollbar to the exports panel when layer is selected and when nothing is selected. References issue #2466.

Added scrollbar to exports panel

---

src/style/shared/color-picker.less

should be fixed for:
- vertical and horizontal slider
- color map

fix for #2254

---

src/js/actions/type.js
src/js/stores/font.js

Add text alignment to type sampling/type style application

---

src/js/models/menubar.js
src/static/menu-actions.json

Disable clear guides menu item if there are no guides in current doc

---

src/js/jsx/shared/ColorPicker.jsx

Addresses second part of #2421

Add last used color picker format to preferences, so it's persistent

---

src/js/tools/type.js

pull this until we have a real plan

revert disablePolicy for modal type tool

---

src/js/actions/layers.js

This addresses an unreported, occasional bug.  Sometimes when you move an artboard, the subsequent resetLayers was discarding the "exportEnabled" flag for the layer.

Fetch extension data during resetLayers

---

src/js/jsx/sections/export/ExportList.jsx
src/style/sections/exports/exports.less
src/style/shared/icons.less

Now the effects icons for trash/visibility appear all the time...Sorry @iwehrman 
Addresses #2494

Made trash/visibility icons consistent

---

src/js/actions/libraries.js

The PR change the behavior on handling new CLSO layer and expanded graphic layers (drop graphic asset with ALT modifier).
For CLSO, the new layer is added through the "placeEvent" handler, to keep consistent with embedded layer (show the new layer after transform mode). It also help address issues #2534,  #2524, and #2523 (press delete / esc during transform mode)
For expanded graphic layers, since there is no "placeEvent" emitted, we will use the previous way by calling "getLayerIDs" and "addLayers" to discover the new layers.

CC Libraries - add new CLSO layer through placeEvent handle

---

src/style/panel.less

apply min-height on effects panel

---

src/js/jsx/sections/style/AppearancePanel.jsx
src/js/jsx/sections/style/Fill.jsx
src/js/jsx/sections/style/Radius.jsx
src/js/jsx/sections/style/Stroke.jsx
src/js/jsx/sections/style/Type.jsx
src/js/jsx/sections/style/VectorAppearance.jsx
src/js/jsx/sections/style/VectorFill.jsx
src/js/jsx/sections/transform/Size.jsx
src/js/jsx/shared/ColorInput.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Dialog.jsx
src/js/jsx/shared/Label.jsx
src/js/jsx/shared/NumberInput.jsx
src/nls/root/strings.json
src/style/panel.less
src/style/sections/style/style-section.less
src/style/shared/color-input.less
src/style/shared/colors.less
src/style/shared/compact-stats.less
src/style/shared/drop-down.less
src/style/shared/icons.less
src/style/shared/number-input.less
src/style/shared/range.less

Here are some updates for Mixed States.
Additionally, some small layout adjustments and design changes.
Notably, the font preview swatch no longer reflect the size of the font
Mixed Vector Layers:
Mixed Vector and Type:
Mixed Type, same color, different faces
Mixed Type Layers

UI Mixed State changes

---

src/js/jsx/Toolbar.jsx
src/js/jsx/Zoom.jsx
src/js/jsx/sections/style/Effect.jsx
src/js/jsx/shared/NumberInput.jsx
src/style/toolbar.less

- Visuals ONLY, needs to wired up
- added Zoom.jsx for feature
- added zoom to the toolbar
- styled it up
- ready for @volfied to wire up/review

UI: Zoom status in toolbar

---

src/js/actions/libraries.js
src/js/jsx/sections/libraries/assets/CharacterStyle.jsx
src/js/jsx/sections/libraries/assets/ColorTheme.jsx
src/js/util/libraries.js

I tested the CC libraries with the sample collection from Project Central and this PR fixes the issues I encountered (primarily related to CMYK colors):
* Can show color theme in CMYK mode
* Can show and apply InDesign Char Style 
* Show font family and size in char style subtitle
The sample collection is perfect for testing, and you can add them to your libraries at this link (open and search "Sample Libraries") https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=ccprojects&title=Project+Central+Home

CC Lib: handle CMYK colors.

---

src/nls/de/strings.json
src/nls/fr/strings.json
src/nls/ja/strings.json

ALF created a pull request. Please pull this in.

ALF Automation

---

src/js/actions/sampler.js

Addresses #2572, @iwehrman please review since you've suggested the solution.

Initialize uninited layers during sample operations

---

src/style/panel.less

color to button color, not text highlight

---

src/js/actions/layers.js
src/js/jsx/sections/layers/LayersPanel.jsx
src/js/models/layerstructure.js
src/nls/de/menu.json
src/nls/fr/menu.json
src/nls/ja/menu.json
src/nls/root/menu.json
src/nls/root/shortcuts-mac.json
src/nls/root/shortcuts-win.json
src/static/menu-actions.json
src/static/menu-mac.json
src/static/menu-win.json

Implements some of the shortcuts/actions described in the most used PS shortcuts card. 
Did not implement merge layers yet, because it's going to take longer than these and will be riskier. So please review this PR separately.

Implement the must have PS shortcuts

---

src/js/jsx/sections/export/ExportAllPanel.jsx

This fixes what seems to have been a merge-induced regression from PR #2489.  Addresses #2589.

Fixed a regression in ExportAllPanel

---

src/js/tools/superselect/vector.js

During vector edit tool, any time a path selection changes, we now get an event with the ids of paths being selected. If there is no path selected, we switch back to select tool.
Requires pdgv.666 or later.

Listen to pathComponentSelectionChanged events in vector tool

---

src/js/jsx/sections/nodoc/RecentFiles.jsx

align recent files, do not add empty recent file html content

---

src/js/jsx/sections/style/Stroke.jsx

What it says!
Addresses #2611.

Enforce a maximum stroke size of 288px.

---

src/js/tools/ellipse.js
src/js/tools/pen.js
src/js/tools/rectangle.js

quick fix for latest adapter changes related to vector mask work

fix spaces-design for latest adapter

---

src/js/jsx/DocumentHeader.jsx

This is the only instance of a window `resize` handler that both executes more than once and isn't debounced. This means it's executing extremely frequently during window resizes, which may or may not materially affect the frequency with which layout and painting happens. I'm arguing with @jsbache about this offline, but this seems like a good and safe change to make either way.

Debounce handleWindowResize in DocumentHeader

---

src/js/actions/history.js

This should address #2103
I'll do 2 laps for this one.

Properly return promise during _navigateHistory

---

src/js/actions/layers.js

1. We should always be calling `initializeLayers` after `resetSelection` because that action causes teh selection to change. So, now we are.
2. `ungroupSelected` doesn't always call `resetSelection`. If it doesn't we need to call `initializeLayers` manually. We need to do so manually whenever an action changes the selection state of the layers without going through `select` or (now) `resetSelection`. If you see any other actions that might change the selection state without going through one of those actions, please let me know!
Addresses #2643.

Initialize layers after ungroup and after resetting the selection

---

src/js/jsx/sections/style/EffectsPanel.jsx

Does what it says on the tin, addresses #2586

Disable effects panel buttons with background layers

---

src/style/sections/exports/exports.less
src/style/shared/button.less

- icons in export modal the correct size
- checkbox extra margin removed

Icons at the correct size

---

src/style/document-header.less

2 bugs, 1 stone
Addresses #2620 and #2659

Make sure document tab bar shrinks to fit export button

---

src/js/jsx/sections/export/ExportPanel.jsx
src/js/models/documentexports.js
src/nls/root/strings.json

- fix for #2574 
- added logic for additional cases of multi-layer selection
- added string for mixed case

Export Warning for mixed selection states

---

src/js/actions/tools.js

According to Ian we already wipe the shortcuts onReset

remove uneeded call to remove Shortcut

---

src/js/jsx/tools/GuidesOverlay.jsx

Addresses #2684, similar to PolicyOverlay.jsx

Redraw guides overlay on window resize

---

src/js/jsx/tools/SamplerOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/stores/ui.js

Addresses https://github.com/adobe-photoshop/spaces-design/issues/2196
That's me in the sampler
That's me in the artboards
@iwehrman please review

Use REMs to draw sampler overlay and artboard adders

---

src/js/jsx/sections/style/Type.jsx
src/js/jsx/shared/Dialog.jsx
src/style/main.less
src/style/panel.less
src/style/search/search-bar.less
src/style/sections/exports/exports.less
src/style/sections/layers/face.less
src/style/sections/libraries/libraries-section.less
src/style/shared/dialog.less
src/style/shared/drop-down.less
src/style/shared/number-input.less
src/style/toolbar.less

- fix for #2656 
- fixed blendmodes for group, shape, text
- fixed typeface, weight
- fixed effects blendmode
- fixed export scale, format
- fixed library dialog
- typeface dialog width

Dialog Dropdown alignment fixes

---

src/js/jsx/shared/Dialog.jsx

Assign uniqkey at proper time

---

src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Dialog.jsx

As to allow reference by dialog id in other places

Only add a unique key suffix to Datalists

---

src/js/jsx/help/FirstLaunch.jsx

fix for #2742

---

src/js/actions/superselect.js

Addresses #2722, transform controls are hidden in two conditions: We set tool options, or we go in a modal state. During click/drag we first select the layer, and then initiate drag. And during that brief instance, transform controls of the newly selected layer flash.
So now, we first disable transform controls, and then try to select. And after initiating drag, we play a modalSafe toolOptions call to re-set the transform controls, so they appear at the end of drag.

Hide transform controls at the beginning of drag

---

src/style/sections/layers/face.less
src/style/sections/libraries/libraries-section.less
src/style/shared/range.less

- getting ready for more colors stops
- clean up for layers panel and range slider background color
- more libraries tweaks for hover/selection
- color stops ONLY need to be changed in `colors.less`

Color Stop Finesse

---

src/style/sections/libraries/libraries-section.less
src/style/shared/colors.less

one more of these color changes before we get to themes

color variable for library sample backgrounds

---

src/nls/root/strings.json

Standard vs Classic Photoshop

---

src/img/ico-loader.svg

Spinner clipped

---

src/style/sections/exports/exports.less

Remove dialog arrow

---

src/js/jsx/sections/style/Type.jsx
src/js/util/unit.js

What it says! See #1519 for details on the enforced sizes.

Enforce minimum and maximum font, leading and tracking sizes

---

src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/LibraryList.jsx

This PR addresses #2197, also added SCU for LibraryList component to improve performance.

CC Libraries - addresses rename input focus issue

---

src/style/panel.less

Single Column panel sizing updates

---

src/js/jsx/sections/transform/TransformPanel.jsx

in the reference tool I created transparent hit rectangles that are larger than the drawn rectangles.

expand hit rigion on svg elements

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx

Related to issue #2824 (Clicking 'x' in search box does not dismiss the search dialog) I was also confused at the beginning but the X button in the search box is for clearing the input. I made some change to display the X button only when the input has value, to ease the confusion.

Search - show clear input button only when the search input has value.

---

src/js/jsx/sections/style/Type.jsx

Changed classname for type color picker dialog

---

src/style/shared/color-input.less

Fixed clipped swatches by changing size slightly

---

src/style/panel.less
src/style/shared/color-picker.less
src/style/shared/dialog.less

Adjusting dialog pointer, created mixin for it

---

src/js/jsx/shared/ColorPicker.jsx

What it says! It skips "name" if the current color doesn't have a name. 
Addresses: UX concerns.

Cycle through color formats with up/down in the color picker input.

---

src/js/actions/documents.js
src/js/actions/tools.js
src/js/tools/superselect.js

All open commands should close mask mode

---

package.json
src/js/actions/documents.js
src/js/actions/layers.js
src/js/actions/shapes.js
src/js/actions/tools.js
src/js/actions/typetool.js
src/js/jsx/shared/Draggable.jsx
src/js/stores/draganddrop.js
src/js/stores/example-one.js
src/js/stores/tool.js
src/js/tools/pen.js
src/js/tools/superselect/vector.js
src/style/help/first-launch.less

These empty lines contain only spaces and tabs were not considered as extra lines in our test. Let's destroy them and make sure our test can capture them in the future.

Some extra new lines escaped from our test

---

src/js/actions/tools.js

this should not be an error

---

src/js/actions/tools.js

this pointer used without a bind

---

src/style/sections/libraries/libraries-section.less

So now it will change based on the `<html>` font size
Addresses #2861

Added specific font size in rems to library title inputs

---

src/js/models/layer.js
src/js/models/smartobject.js

Create a SmartObject model so that it behaves well with Immutable merge

---

src/js/actions/layers.js
src/js/actions/type.js
src/js/models/layer.js
src/js/models/layerstructure.js
src/js/util/svg.js

This PR requires Jenkins build 725. It fixes issue #2122

 add WarningLevels to layers for missing fonts

---

src/style/shared/button.less

Checkbox styling

---

src/style/toolbar.less

Small change to the toolbar width

---

src/js/jsx/help/KeyboardShortcuts.jsx
src/nls/root/strings.json
src/style/help/first-launch.less

- added sampler modifiers, search, mask mode and export
- sampler shift click/spacebar
- icons for tools, search, mask mode and export
- small changes to spacing for titles

KBSC Dialog updates

---

src/style/shared/colors.less

This is the second darkest of the 4 stops. It is also the “default”
standard Ps color stop.
- bg app color

Colors for B3 color stop

---

src/js/actions/tools.js
src/js/actions/ui.js
src/js/stores/tool.js
src/js/tools/ellipse.js
src/js/tools/pen.js
src/js/tools/rectangle.js
src/js/tools/superselect.js

This PR modifies the pointer policies associated with vector mask mode to refresh on uiStore change events. and to use the correct bounds.

fix bounds of pointer policy for vector mask mode

---

src/style/document-header.less
src/style/panel.less
src/style/toolbar.less

Make borders responsive, make outer side borders equal

---

src/js/jsx/PanelSet.jsx
src/js/jsx/sections/export/ExportPanel.jsx
src/js/jsx/sections/style/EffectsPanel.jsx
src/style/panel.less

Changes to the sizes of the section in order to stop the layers panel from jumping around

Updates to single panel behavior

---

src/nls/root/strings.json

CMDmd-key-unicode

---

src/js/jsx/Main.jsx
src/js/jsx/shared/Carousel.jsx
src/style/help/first-launch.less
src/style/search/search-bar.less
src/style/sections/exports/exports.less

- Next/prev buttons removed, just goes to the next. Back button returns
to the zero slide: #2749
- [edit] now fixes  #2795

Intro Dialog Fixes

---

src/style/shared/colors.less

- error icon color
- warning icon color
- fix for #2920

Color for error iconz

---

src/style/panel.less

- add blue border to dialogs
- first and last cause rounded corner issues
- final visual fix for #2491

dialog blue

---

src/js/jsx/sections/layers/LayerFace.jsx
src/style/shared/colors.less
src/style/shared/icons.less

- add string for tooltip warning - missing font and reflow
- textWarningLevel changes
- final color choice
- remove color for reflow text, keeps icon tho
- fix for #2122

Text Alert Icons

---

src/js/actions/tools.js
src/js/tools/superselect/vector.js

move shortcut for vector superselect tool into vector mode aware handler

---

src/js/jsx/DocumentHeader.jsx

make vector mask button aware of the current tool

---

src/js/jsx/shared/Carousel.jsx
src/nls/root/strings.json

References #2943.
Before: 
After:

Broken icons on Welcome Screen fixed

---

src/js/actions/tools.js

change default pixel witdth of strokes to 1 px to match standard

---

src/js/actions/edit.js

Yet another fix related to `place` command. Unfortunately, @mcilroyc's fix in #2965 using `toolModalStateChanged` does not cover this issue, due to the reason similar to place-object menu commands (https://github.com/adobe-photoshop/spaces-design/pull/2965/files#diff-0ade3704b4a758bac0c90e3fb8835095R82). 
This will address issue #2282

Fix pasting smart object copied from other sources (Illustrator) freezes Photoshop

---

src/style/help/first-launch.less

References #2966 
Before: 
After:

Adjusts the spacing between icons in French and German 

---

src/js/actions/keyevents.js

We currently store modifier state from the `adapterFlagsChanged` os event so that click handlers can determine which modifiers were active during the click. However, we only get `adapterFlagsChanged` events when the application is active. So, e.g., if you cmd-tab away from Design Space, we store modifier state with the command modifier enabled, but if you then click the title bar to activate the application again, no new `adapterFlagsChanged` events are emitted, and so the stored modifier state is now stale and the next click event will turn into a command click.
This works around the problem by clearing the modifier state whenever the application becomes inactive. As noted in the comment below, the adapter would ideally also emit an `adapterFlagsChanged` event whenever the application …

Clear stored modifier state when the application becomes inactive

---

src/js/actions/index.js
src/js/actions/mask.js
src/js/actions/tools.js
src/js/tools/ellipse.js
src/js/tools/rectangle.js
src/js/tools/superselect/vector.js

Change the delete mask workflow to be more useful

---

src/js/actions/layers.js

Currently `layers.select` does not allow modifiers to be used when multiple layers are supplied. This is because the "pivot" calculation, which is used by many of the modifiers, doesn't make sense in the case of multiple layers. However, `marqueeSelect` uses the "add" modifier and provides multiple layers, which causes an error. This relaxes the check so that the only illegal case is when multiple layers are passed with the `addUpTo` modifier. Handling that operation really does require that only a single layer be passed in; otherwise, we just nullify the pivot and move on. (The pivot is used to calculate the final selection when shift-clicking-to-select-a-range in the layers panel.)
Addresses #2974.

Fix shift+marquee select

---

src/js/actions/tools.js
src/js/tools/superselect.js
src/js/tools/superselect/vector.js

fix for issues #2893 and  #2892

use alpha propogation while in super select tool

---

src/js/actions/mask.js
src/js/tools/pen.js
src/js/tools/superselect.js
src/js/tools/superselect/vector.js

add esc handler to pen and selection tools

---

src/js/jsx/sections/style/EffectsPanel.jsx

What it says! Works just like the Export panel.
Addresses #2448.

Force the effects panel open when adding an effect

---

src/js/actions/transform.js

What it says!
Addresses #1538. See notes there for info about how to repro the problem.

Filter empty layers in swap, flip, align and distribute.

---

src/js/actions/layers.js
src/js/tools/pen.js

Fix pen tools select handler

---

src/nls/de/shortcuts-mac.json
src/nls/de/shortcuts-win.json
src/nls/fr/shortcuts-mac.json
src/nls/fr/shortcuts-win.json

https://watsonexp.corp.adobe.com/#bug=4075078
https://watsonexp.corp.adobe.com/#bug=4075062
https://watsonexp.corp.adobe.com/#bug=4075074
Changing shortcut according to linguist's suggestion.

Fix German shortcut issue.

---

src/js/jsx/sections/transform/Size.jsx

What it says! Addresses #3021.

Blur Width input when shift-tabbing beyond it

---

src/style/shared/colors.less

- hover text color
- hover icon color

More Contrast for Hover Color on Text/Icons 

---

src/js/actions/tools.js
src/js/tools/superselect.js
src/js/tools/superselect/vector.js

fix for issue #2811 
requires jenkins build 800

disable right mouse button in vector mask mode

---

src/js/jsx/sections/style/Stroke.jsx
src/style/panel.less
src/style/shared/dialog.less

References #2571 
Before: 
After:

added japanese specific styles for appearance and effects panels

---

src/js/jsx/sections/export/ExportList.jsx
src/js/models/documentexports.js
src/js/models/exportasset.js
src/js/util/exportservice.js

Add several preset quality levels of JPG, and a PNG8 option, to export settings list.  This addresses #2773

Support for other export qualities

---

src/js/actions/tools.js

vector mask with multiple layer selections now uses the selection dance 

---

src/js/jsx/sections/transform/Combine.jsx

update combine objects on vector mask change

---

src/js/actions/layers.js
src/js/actions/tools.js
src/js/tools/pen.js

This PR addresses the following issues:
* #1422  Unable to delete layers if Pen Tool is selected
* #3010 Create new layer by using the pen tool result in error

Support deleting selected layer(s) when pen tool is activated

---

src/js/models/menubar.js
src/js/stores/menu.js
src/static/menu-actions.json

disable revert while in vector mask mode

---

src/js/actions/layereffects.js
src/js/models/layerstructure.js

Prevously, sampling layer effects only handle the following cases:
1. delete all effects if the target has no layer effect
2. copy existing effects from source layer to target layer
This PR handles the 3rd case:
3. If target layer has more effects then the source layer, it should duplicate the existed effects from the source layer, and delete the extra effects.
Addresses #3016

Sampling layer effects should delete extra effects.

---

src/js/actions/transform.js

1. Filter empty layers (and adjustment layers and background layers) before playing `rotate` and `setRadius` actions. This addresses #3022.
2. Move all transform filtering into one helper function which filters empty layers, adjustment layers, backgrounds and (optionally) empty artboards.
As with #3007, this doesn't affect the UI, so some menu items or UI elements may still be enabled when the filtering will otherwise reduce the command to a no-op. This is something that it would be great to have a higher level, more unified solution for later, but for now this at least helps us avoid having unhandled exceptions.
Addresses #3022.

Filter more layers in transform commands

---

src/js/actions/libraries.js
src/js/jsx/Scrim.jsx
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/sections/libraries/assets/AssetSection.jsx
src/js/jsx/sections/libraries/assets/CharacterStyle.jsx
src/js/jsx/sections/libraries/assets/Color.jsx
src/js/jsx/sections/libraries/assets/ColorTheme.jsx
src/js/jsx/sections/libraries/assets/Graphic.jsx
src/js/jsx/sections/libraries/assets/LayerStyle.jsx

Here are the events logged:
* create/delete/update (only rename)/switch library
* create/delete/update (only rename) element
* apply color / color-theme / layerstyle / characterstyle
* place graphic
* open/update graphic
* open library links: share library, share public link, view online
* open element links: share public link, view online
* open Adobe Stock link

Log analytic events for CC Libraries

---

src/js/actions/documents.js
src/js/actions/edit.js
src/js/actions/export.js
src/js/actions/tools.js
src/js/actions/transform.js
src/js/actions/ui.js
src/js/jsx/IconBar.jsx
src/js/jsx/PanelSet.jsx
src/js/jsx/help/FirstLaunch.jsx
src/js/jsx/search/SearchBar.jsx
src/js/jsx/sections/export/ExportAllPanel.jsx
src/js/jsx/sections/export/ExportList.jsx
src/js/jsx/sections/export/ExportPanel.jsx
src/js/jsx/sections/style/AppearancePanel.jsx
src/js/jsx/sections/style/ColorOverlayList.jsx
src/js/jsx/sections/style/EffectsPanel.jsx
src/js/jsx/sections/style/Fill.jsx
src/js/jsx/sections/style/LayerBlendMode.jsx
src/js/jsx/sections/style/ShadowList.jsx
src/js/jsx/sections/style/Stroke.jsx
src/js/jsx/sections/style/StrokeList.jsx
src/js/jsx/sections/style/UnsupportedEffectList.jsx
src/js/jsx/sections/transform/Flip.jsx
src/js/jsx/shared/Carousel.jsx
src/js/jsx/tools/SamplerOverlay.jsx
src/js/util/ui.js

https://trello.com/c/jg3fH91Q/599-analytics-todo
Update: 
Currently Tracking:
*Search*
- What category was searched and if filters were used or not. Categories include: menu commands, layers (including the exact type), recent documents, current documents. 
- When a failed search occurs including the search term of the failed search. (This can be optimized in the future) 
*Export*
- When a preset is used and which one is used
- When user deletes an asset 
- When user creates a single asset 
- When user exports using the panel
- When user exports from the dialog
- Quality/format/setting of every asset exported 
*Swap*
- Artboards are swapped 
- Non-artboard layers are swapped
- Layers are flipped horizontally 
- Layers are flipped vertically 
*UI*
- When user collapse or expands a panel (2 …

Adding calls to Headlights API

---

src/js/actions/sampler.js

See the comment in the code for more details.  I'm not really proud of this, but I think it is safe and works better than the current functionality.  Addresses (hacks around) #3084

Fix for sampler/replaceGraphic to workaround a core bug

---

src/js/stores/font.js

Please test w.r.t. font size and line height on documents of multiple resolution. Affects the sampler and copy/paste styles workflows.
Addresses #3122.

Font sizes and line heights extracted from layers are in pixels, not points.

---

src/js/actions/edit.js

…by toolModalStateChanged - even though those are received only at the end of modal placement.
The theory is that, as a workaround for the un-timely toolModalStateChanged events, we must suspend policies at the beginning of nativePaste.  But, because we DO end up receiving toolModalStateChanged (both enter and exist, in quick succession) after the user places the object, then we do not strictly need to restore policies "finally" as part of nativePaste.
This hopes to address #3126 which was restoring policies while still in text edit modal state.

Restore policies after nativePaste only if not currently in modal tool state

---

src/style/panel.less

Fixes size label in the Effects panel -- Japanese

---

src/js/actions/dialog.js
src/js/actions/guides.js
src/js/actions/policy.js
src/js/actions/shortcuts.js
src/js/actions/tools.js
src/js/jsx/tools/PolicyOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/tools/ellipse.js
src/js/tools/pen.js
src/js/tools/rectangle.js
src/js/tools/sampler.js
src/js/tools/superselect.js
src/js/tools/superselect/type.js
src/js/tools/superselect/vector.js

Updated policy action terminology:
1. `ALPHA_PROPAGATE` -> `PROPAGATE_BY_ALPHA`
2. `FOCUS_PROPAGATE` -> `PROPAGATE_BY_FOCUS`
3. `NEVER_PROPAGATE` -> `PROPAGATE_TO_BROWSER`
4. `ALWAYS_PROPAGATE` -> `PROPAGATE_TO_PHOTOSHOP`

Policy terminology update.

---

README.md

What it says! You can click the "Display Rich Diff" button below to see the before/after. (I also filed #3159 in the process of making this.)

Updated README screenshot

---

src/style/help/first-launch.less
src/style/main.less
src/style/sections/exports/exports.less
src/style/sections/libraries/libraries-section.less
src/style/sections/style/glyphs.less
src/style/shared/button.less
src/style/shared/colors.less
src/style/shared/icons.less

Thrilling PR changing the name of an older variable names to be less specific for colors.

fix for #1946

---

src/js/tools/sampler.js
src/js/tools/superselect.js

It's just a search-and-replace renaming! How hard could it be!
Addresses #3173.

Fix the PROPAGATE_BY_ALPHA_AND_NOTIFY propagation mode.

---

src/js/actions/mask.js
src/js/actions/sampler.js
src/js/tools/superselect/vector.js

handle delete correctly for non modal superselect case

---

src/js/fluxcontroller.js

Currently if an action is marked as `modal: true`, which means it may execute while Photoshop is in a modal state, but then transfers to an action with `modal: false`, which means it must not execute while Photoshop is in a modal tool state, the modal tool state will not be committed because the controller only handles this flag at the action-enqueue level and not the transfer level. This PR changes the controller so that the `modal` flag is handled uniformly for both cases, inside `FluxController.prototype._applyAction`.

Fix non-modal transfers

---

src/js/stores/document.js

Don't set doc dirty on guide visibility change

---

src/js/actions/transform.js

For similar reasons to Swap, if autoExpand is enabled, and we try to resize 3 artboards at once, the canvas shift would break things. SetSize has been updated to temporarily turn off auto expand during it's operation.
Addresses #3164 
As far as I can tell, for three artboards, the setSize time went from 90 ms to 150 ms, so it's not a bad loss.

Do the autoExpand dance for setSize

---

src/js/util/headlights.js

Converts isChecked Boolean to String

---

src/js/actions/documents.js
src/js/actions/history.js
src/js/actions/layers.js
src/js/actions/sampler.js
src/js/actions/tools.js
src/js/actions/transform.js
src/js/actions/ui.js

This shouldn't be merged until after we GM. Adding a review only label

refactor code to add handler to reset border policies

---

src/js/main.js

Details in adobe-photoshop/spaces-adapter#164. These two PRs should be merged at the same time.

Reduce plugin-compatibility check to a warning

---

src/js/actions/history.js
src/js/actions/transform.js

I missed some that were introduced in my last rebase.

cleanup action objects

---

src/js/actions/tools.js
src/js/stores/ui.js

add listener to update border policies based on ui store

---

src/js/actions/tools.js

Addresses #3224... because we need more policies

Add shift+cmd/ctrl policy to inner selection rectangle

---

src/js/actions/sampler.js
src/js/actions/shapes.js
src/js/jsx/Main.jsx
src/js/jsx/Scrim.jsx
src/js/jsx/sections/layers/DummyLayerFace.jsx
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/layers/LayersPanel.jsx
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/Library.jsx
src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/sections/libraries/assets/Graphic.jsx
src/js/jsx/shared/Draggable.jsx
src/js/jsx/shared/Droppable.jsx
src/js/models/bounds.js
src/js/stores/draganddrop.js
src/js/stores/style.js
src/js/util/ui.js
src/style/sections/layers/face.less

* Improved initial drag performance (#3181)
* Improved overall performance when dragging over droppable items
* Make the Droppabel / Draggable components easier to use and read.
Before: https://www.dropbox.com/s/eja1idsmxg6z1i4/dnd-before.mov?dl=0
After: https://www.dropbox.com/s/u6mz642ar10ueuv/dnd-after.mov?dl=0
Here is a document (I stole from @iwehrman long ago) contains 1000+ layers which makes it perfect for testing/comparing the administration: 
Here are some drag-and-drop scenarios:
* layer reordering: layer -> layer 
* create graphic from layer: layer -> library panel
* create layer from graphic: graphic -> canvas

Refactor Draggable/Droppable with performance improvements

---

Gruntfile.js
src/index-build.html
src/index.html
src/js/init-build.js
src/js/init.js
src/style/component-styles.less
src/style/main.less

Instead of loading different CSS files for different stops, now all component CSS is scoped under a class on the body tag, which is applied at load based on the PS color stop.

Move all CSS for different color stops into 1 file

---

src/nls/root/strings.json

quick fix for missing string. i didnt make an issue since this is an easy fix

add string for super select vector tool

---

src/js/actions/transform.js
src/js/jsx/mixin/Scrubby.js
src/js/jsx/sections/transform/Position.jsx
src/js/jsx/shared/Label.jsx

I tied the scrubby to the zoom level, which i think i like. this probably needs some tweaking

Scrubbing of Positions works now

---

src/js/jsx/Guard.jsx
src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/sections/style/EffectsPanel.jsx
src/js/jsx/sections/transform/Position.jsx
src/js/jsx/shared/Carousel.jsx
src/js/jsx/shared/CheckBox.jsx
src/js/jsx/shared/ColorInput.jsx
src/js/jsx/shared/NumberInput.jsx
src/js/jsx/shared/Select.jsx
src/js/jsx/shared/TextInput.jsx
src/js/jsx/shared/ToggleButton.jsx
src/js/jsx/tools/SuperselectOverlay.jsx

Fix JSDoc errors due to jsdoc update

---

src/js/jsx/DocumentHeader.jsx
src/style/document-header.less

- Reorg the document bar buttons with Mask first
- Highlight for mask mode more pronounced
- Additional work to follow
- string loc thing updated

Mask Mode App Ui Design Work

---

src/js/actions/tools.js

fix for reset border policies in no docuement case

---

src/js/actions/layers.js
src/js/models/documentexports.js
src/js/stores/export.js

1. Load layer metadata lazily, so that when initializing a document metadata is only requested for selected layers. As with other lazy properties, metadata is loaded on-demand by `initializeLayers`/`resetLayers`. Addresses #3290. 
2. Respect the `lazy` parameter in `resetLayers` when choosing whether or not to load layer metadata when resetting layers.
3. Correctly reset/update layer export information as a result of `resetLayers`. Previously, updated export information that resulted from `resetLayers` was ignored.
This provides a modest document load-time speedup. For Vermilion, it seems to save a small few hundred milliseconds.

Load layer metadata information lazily 

---

src/js/actions/documents.js

This addresses #3276.  A new document will not have "guides" property (due to recent lazy loading change), so this handles that case when setting the first guide.  @iwehrman please review to make sure this is inline with how we should recover from lazy loading of guides.

Handle case where first guide is added to a new document

---

src/js/jsx/sections/layers/LayersPanel.jsx

This is a minor performance optimization. It eliminates one [forced synchronous layout](https://developers.google.com/web/tools/chrome-devtools/profile/rendering-tools/analyze-runtime#how-to-identify-layout-bottlenecks) when clicking in the layers panel by suppressing the scroll-into-view behavior, which is unnecessary in that case. The Chrome timeline seems to indicate that this saves a reliable 5ms of layout on each click. This isn't really noticeable, but maybe it's educational? 
Before (some spent in layout):
After (no time spent in layout):

Suppress layer panel scroll-into-view on click

---

src/js/actions/history.js

This addresses #3307.  
It is possible for the current selection state (after undo/redo) to contain layers which were not initialized at the time the history state was captured.
Consider a newly loaded document with three shapes: 1, 2, & 3, with  Layer 1 selected.  Layers 2 and 3 are not fully initialized.
- Move Layer 2 below layer 3
- Layer 2 is now selected
- Undo
- Layer 2 is still selected, but must now be explicitly initialized
Please review @iwehrman.

Loading document from history should initialize selected layers

---

src/js/actions/tool/pen.js

check for missing docuement in pen selection

---

src/js/jsx/tools/GuidesOverlay.jsx
src/js/jsx/tools/PolicyOverlay.jsx

Addresses #3351, but the core of the issue is re-iterated on #3355

Avoid drawing negative width/height rectangles on overlays

---

src/js/actions/transform.js

We were playing the `setAutoExpand` calls outside the `playLayerActions` calls, so on an undo, we would get back to the state where we turned auto expand off.
Now we use the handy transactions to make sure the autoExpand dance is included in the history state.
Addresses #3357

Play setSize and swap in a transaction with autoExpand dance included

---

src/js/jsx/Scrim.jsx
src/js/jsx/sections/transform/Position.jsx
src/js/jsx/tools/GuidesOverlay.jsx
src/js/jsx/tools/SuperselectVectorMaskOverlay.jsx

fix for issue #3385. 
also fixes issue with using depreciated react call (moved to react-dom)

handle multiple tool overlays properly

---

src/js/util/collection.js

Ref point center and X, Y set to zero now displays

---

src/js/actions/search/commands.js

Menu Commands fixed in search

---

src/js/jsx/shared/Dialog.jsx

This PR fixes issue #3325.
Before:
After:

Fix wrong dialog position when it is placed above its target.

---

src/js/jsx/sections/export/ExportPanel.jsx
src/style/shared/icons.less

Add loader back to Export Panel, fix rotation issue

---

Gruntfile.js

The new config will enable LESS source map for internal/remote dev tool.

Enable LESS source map

---

src/js/actions/groups.js
src/js/actions/index.js
src/js/actions/layers.js
src/js/actions/mask.js
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/models/menubar.js
src/js/models/tools/superselect.js
src/static/menu-actions.json

The goal here is only to reduce the size of `actions.layers`. Also:
* moves the mask actions from `actions.layers` into `actions.mask`, and
* converts `layers.unlockBackgroundLayer` into action.

Factor actions.groups out of actions.layers

---

src/js/jsx/search/SearchBar.jsx

Updates 'clear search'  icon whenever filters are changed

---

Gruntfile.js
npm-shrinkwrap.json

This adds an npm-shrinkwrap.json file to the repository. This forces npm install to only choose specific versions of packages that are known to work in our repository. This will help us guard against packages that don't quite follow semver rules. More information here: https://docs.npmjs.com/cli/shrinkwrap
Addresses #3372.

Add a shrinkwrap file

---

src/js/actions/transform.js

In #3441 I "cleaned up" the layer transform handler in a way that may, in some cases, cause history to not be recorded correctly. In particular, the transform events may be associated with rogue history events, and the handler should anticipate this. (Before #3441 we just inserted an awkward delay with the hope that any other events would already have been delivered and handled.) Without handling such out-of-order history events in some way, the later transfers to reset actions would then not amend history correctly.
I haven't actually been able to reproduce this problem, but that may just be because all the transform events I've been able to trigger so far have the correct ordering w.r.t. history states. Or maybe there is some other reason why this isn't actually a problem. In any case, …

Anticipate rogue history states when handling transform events.

---

src/js/jsx/sections/transform/Rotate.jsx

This is an attempt to get rid of `_lastAngle` to hopefully simplify the tracking of angle state in the Rotate component.  It seems to work, but am interested in @volfied's keen eye.  This also addresses #3446 which I noticed in master while comparing the two branches.

Clean up of Rotate.jsx to remove _lastAngle in favor of react state.value

---

src/js/actions/superselect.js

Marquee select only starts if there is nothing under the pointer. With vector masked layers, we would consider masked out areas still within the layer, so now we hitTest to double check the click/drag location and start marquee on those areas.
Adresses #3158

Use hitTest to start marquee select

---

src/js/actions/shapes.js
src/js/jsx/sections/transform/Combine.jsx
src/js/models/layerstructure.js

disable combine operations between different types of path objects

---

src/js/models/layerstructure.js

make replace layer code vector mask aware

---

Gruntfile.js

This change watches for localization file changes and rebuilds as necessary. Addresses #3429

Watch for dictionary file changes

---

src/js/jsx/tools/GuidesOverlay.jsx

Instead of immediately starting a guide tracker on mouse down, now we wait for user to drag the mouse out of the guide zone before creating/dragging the guide. This prevents creating guides underneath the zone areas.
Adresses #2640, at least the part I agree with.

Create guides on zone drag-out instead of mouse down

---

src/js/jsx/tools/SamplerOverlay.jsx

Adresses #3111 - we were using our own bounds calculations, which would consider masked layers in their full rectangle. Now we rely on hitTest, similar to what we do with superselect, so masked out areas don't highlight the layer.

Use hitTest for sampler overlay highlighting

---

src/js/jsx/sections/style/Type.jsx

Appearance panel datalist position remains still

---

src/js/jsx/sections/style/Radius.jsx
src/style/panel.less

References #3512
(Apologies for the UNREGISTERED sprawled over this image)

Adjusts radius text input alignment in appearance panel

---

src/js/models/tools/superselect.js

fix spurious delete action that didnt get caught when the function moved

 fix action call to refer to the correct action file

---

src/js/actions/superselect.js

Missed this one during my drag start latency work, oops.
#3538

Set select options correctly on marquee select

---

src/js/jsx/sections/style/Radius.jsx
src/js/jsx/sections/transform/Position.jsx
src/js/jsx/sections/transform/Size.jsx

Addresses #3554, correctly implementing `shouldComponentUpdate` for Size, Position and Radius components.

Refined SCU for Size, Position and Radius checking each state member

---

src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/shared/Draggable.jsx

Disable drag-and-drop when editing layer name.

---

src/js/jsx/sections/style/VectorAppearance.jsx

Addresses #3530, regression from 16.1.2

Hide radius controls when there are no radii layers

---

src/js/jsx/sections/export/ExportPanel.jsx

1. The quick export button in the export panel is now disabled in modal states.
2. Component state that forcibly disables export is now reset when the controller resets to prevent it from being stuck in a disabled state.
Addresses (and there is more discussion in) #3137.

Disable quick direct export in modal state

---

src/js/actions/documents.js
src/js/actions/tools.js

exit Vector Mask Mode on Document Close

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx

Fix for partial search query execution resulting in error

---

src/style/sections/layers/face.less
src/style/sections/libraries/libraries-section.less

I forgot the px unit in my previous PR so the recent style fix will not work correctly in smaller screen (my bad :( )

Add missing px unit to the media queries.

---

src/js/jsx/search/SearchBar.jsx

Bug fix: search bar localization error

---

src/js/jsx/sections/style/EffectsPanel.jsx

Reordered the Effects to be in more logical order
Fix for #3636 
removed some white spaces

Reordered the Effects to be in more logical order

---

src/style/panel.less

Padding changed to avoid clipping on color swatches

---

npm-shrinkwrap.json
package.json

Upgrade spaces-adapter to v1.2.1, and update the shrinkwrap file accordingly. I believe the from/resolved changes are just noise, but please double-check my arithmetic @mcilroyc.

Upgrade spaces-adapter

---

src/js/actions/layers.js

With this change, `layers.resetBounds` ignores layers that don't have bounds like non-artboard groups, groupends, and adjustment layers. As mentioned in #3686. I can't actually measure a speed improvement here, but it still seems reasonable...

In resetBounds, ignore layers that do not have bounds.

---

src/js/actions/documents.js

This fixes the more annoying portion of the issue reported in #3694.  When opening multiple documents at the same time with the `Open...` menu, the opened-but-inactive documents can not have their history state initialized (PS limitation).  When the document is later selected, various actions will cause a warning that indicates history was trying to be amended, but the history store is not initialized.  This seems to be safe to ignore, but the fix in this PR seemed like the right thing  to do.
`[History] Could not amend history, document history not found`
In the case of large documents this would happen immediately, but in smaller documents it can still happen after selecting a new layer for the first time (in the newly selected document).
This PR updates the `document.selectDocument` …

Init document history on first-time selectDocument

---

src/js/actions/libraries.js

Do not apply CC Libraries color with no text or vector layers selected

---

src/js/actions/libraries.js

What it says! Addresses #3674 very narrowly.

Leave vector edit mode when placing Libraries graphic

---

src/js/jsx/sections/style/Type.jsx

Increase size of font size input field

---

src/js/actions/export.js

Semi-hokey fix for #3609
If you exporting a batch of layers, and there are layer-name collisions, use a simple suffix to avoid a filename collision on the exported assets.
example (updated):

When exporting a set of layers with some duplicate layer names, use a suffix to distinguish

---

src/style/search/search-bar.less

What it says! (If anybody knows a better way, feel free to chime in.)
Addresses #3763.

Fix search bar hover text size

---

src/js/actions/debug.js

Address issue #3762. Also increase JSON spacing of all descriptor log for better readability.

Show params of descriptor event inside a group.

---

src/js/fluxcontroller.js

Re-enabled the time stamp for production mode. Also added comments to prevent them from disabled again. @iwehrman can you review? Thank you.

Re-Enable action time stamp in production/debug mode.

---

src/js/jsx/sections/layers/LayerGroup.jsx

Fix for issue #3746, which layer selected from the canvas is not scroll into the visible area.

Reveal layer when it becomes selected or is newly created.

---

src/style/help/first-launch.less

References issue #3745 
This forces the intro screen to always take the colors of the medium color stop.

Making introduction screen default into medium color stop values

---

src/js/actions/search.js

This ends mask mode before opening the search dialog in order to prevent key event policy problems, as described in #3740. (It's unclear why that is happening only on Windows.)

End mask mode before opening search dialog

---

src/style/help/first-launch.less

References #3745
The keyboard shortcut dialog is fixed for all color stops

Fixed the colors of the keyboard shortut dialog

---

src/js/actions/documents.js

Fix for issue #3750 
We are receiving one `placeEvent` with information of the last new layer when dropping multiple files , which causes the layers panel to add only one new layer. This PR fix the issue by fetching all layer IDs of the current document and then compare with the previous document model to detect all new layer IDs.

Bug fix for dropping multiple files onto canvas

---

src/js/actions/documents.js

This PR updates the visibility state of both Guides and Smart Guides menu items, when user turn on one of them (before, we only update the visibility state of the clicked item). 
The reason for this change is because, in standard PS, when `View > Extra` is off and `View > Show > Guides/Smart Guides` are on, the descriptors that get the visibility state of guids/smart guides will return false. When we run the descriptor to turn on one of them, PS will instead turn on the `View > Extra` menu item, which makes both Guides and Smart Guides on now. Without this fix, user will see both guides and smart guides on the canvas while the menu items are not both checked.
*More discussion is on JIRA PS-1212*

Fix menu item state for guides and smart guides.

---

src/style/panel.less

Fix stroke color swatch clipping on the bottom edge

---

src/style/sections/libraries/libraries-section.less

References issue #3826 
Before: 
After:

Removed bottom border for libraries panel

---

src/nls/de/strings.json
src/nls/fr/strings.json
src/nls/ja/strings.json

The new strings of go URL were localized, please help to merge.
Because ALF automation requires same structure for localized and core dictionaries, so I stop it to prevent override the bug fix for localized version.  In case new strings are added, please inform me.

Localization update:  Adding goURL for FGJ.
