adobe-photoshop/spaces-design

src/js/actions/layers.js
src/js/stores/document.js

Addresses #1489 
Two commits:
1. After deleting a layer, we now query photoshop for the current selection state.  We previously were making no attempt to update the selection state, and that was bad
1. Attempt to make more consistent use of "resetSelection" within the layer actions.  Note that this affects three "other" code paths: reordering layers, deleting the last anchor of a shape, certain types of "ungrouping".
Note: this "introduces" a post condition error when doing some ungrouping (such as ungrouping an empty group) but I think it is a separate, existing issue that is just being surfaced more correctly now.  I didn't want to hold up this PR for that fix.

Layer actions fixes: post-deletion selection reset, and minor resetSelection refactoring.

---

src/js/actions/layers.js
src/js/models/layerstructure.js
src/js/stores/document.js

This PR provides proper background layer unlocking wrt to both history store, *and* the "replace layer" logic.
1. The replace layer logic now handles the special case of unlock background layer by allowing an explicit layer ID parameter of that which is to be replaced.  The recent simplifications to replace layers based on selection state does not handle this situation gracefully otherwise.
2. The unlock background layer action no longer emits two separate history-changing flux events
addresses #1443

Unlock background layer: correct history states and layer replacement

---

src/js/actions/ui.js

This is an API Jesper developed for us, which allows us to set rectangles so certain events to immediately clear out regions of the HTML page. We use this during `scroll` events that come from Photoshop so when user starts panning / scrolling, we can immediately erase our layer bounds.
It's a big improvement to one of the oldest issues.

Set cloaking overlay on window resize

---

src/js/actions/documents.js
src/js/actions/layers.js

Relies on adobe-photoshop/spaces-design#108, which adds a `getPropertiesRange` call to efficiently get a list of properties of a range of references (e.g., all layer references on a document). This adds a new private helper function, `layers._getLayersForDocumentRef` which uses `getPropertiesRange` to more efficiently get all the layer descriptor objects when loading documents (by, e.g., `initActiveDocument` and `initInactiveDocuments`).  This provides a significant performance improvement at document-load time for large documents. The mega-artboards document previously spent ~7s waiting on Photoshop for these descriptors and now only waits for ~4s. 
In a follow-up PR, I'll apply similar new functionality in `batchPlay` to the existing `_getLayersByRef` function to go from O(mn) play …

Use a multiget reference to load a document's layer descriptors

---

src/js/actions/layers.js
src/js/actions/superselect.js
src/js/events.js
src/js/stores/document.js
src/js/stores/menu.js

This PR adds a new type of REORDER_LAYERS event that does *not* increment history.  This is to support the recently added logic that, after moving a layer between Artboards, resets the entire layer order by asking photoshop.  Additionally, this step is *no longer* called in the "copyDrag" case, because that ends up doing a full updateDocument anyway.
addresses #1613

Fixes for option-dragging a new layer

---

src/js/actions/documents.js
src/js/actions/history.js
src/js/actions/layers.js
src/js/actions/shapes.js
src/js/actions/ui.js

This PR makes full use of multiGetRefs, added in adobe-photoshop/spaces-adapter#110, for a variety of modest performance gains. `layers.addLayers`, for example, takes about 75% as long as on master. But, it all adds up!
Unless you're fetching an arbitrary set of properties from an arbitrary set of references, there isn't a good reason now to use `batchGet` and friends. Instead, choose something like `getPropertiesRange` if you're getting a fixed set of properties from a contiguous range of references, or `batchMultiGetProperties` to get a fixed set of properties from an arbitrary set of references.
Relies on adobe-photoshop/spaces-adapter#110.

Finish conversion to multiGetRefs 

---

src/js/actions/documents.js
src/js/actions/ui.js
src/js/stores/ui.js

With the overlay cloaking functionality, bounds overlays are automagically cleared by the plugin on every "scroll" event. The zoom and centering commands always trigger a scroll event, so the current 50ms artificial delays in those commands (which were added to give the plugin time to repaint the CEF surface before changing the canvas) are no longer necessary.
It would be great to also remove these delays from the document open/close/selection actions, but those are not guaranteed to generate a scroll event. (They seem to do so only if the canvas is positioned or zoomed differently from one document to the next.) This will require some sort of core change, which I'll file a Watson bug for separately.
When testing, please confirm that there are no ghostly bounds when performing any of the …

Remove artificial delays from zoom commands

---

src/js/tools/type.js

Addresses #1599. 
I didn't want to disable this because I see use in it, so instead I'm handling it gracefully.

Listen to move events during type tool

---

src/js/actions/application.js
src/js/actions/dialog.js
src/js/actions/documents.js
src/js/actions/draganddrop.js
src/js/actions/edit.js
src/js/actions/example.js
src/js/actions/help.js
src/js/actions/history.js
src/js/actions/index.js
src/js/actions/keyevents.js
src/js/actions/layereffects.js
src/js/actions/layers.js
src/js/actions/menu.js
src/js/actions/policy.js
src/js/actions/preferences.js
src/js/actions/search.js
src/js/actions/shapes.js
src/js/actions/shortcuts.js
src/js/actions/superselect.js
src/js/actions/tools.js
src/js/actions/transform.js
src/js/actions/type.js
src/js/actions/ui.js
src/js/fluxcontroller.js

While setting up JSDoc, I've realized that our way of defining actions is very incompatible with JSDoc. This PR gets rid of all the pesky action objects defined at the end of each action file, and instead relies on the "command" function definitions to be the actions. 
The reads/writes/modal etc. like properties are directly defined next to the function object.
This will require rebase on every other branch if it goes in first, and I hope it does, because getting rid of all those objects was a pain.
I also had to make couple extra changes to make sure that our actions were named same as their exported names. And I alphabetized the action index.

Get rid of action objects, instead define properties of action functions

---

src/js/actions/layers.js
src/js/models/bounds.js

Will alleviate #1650 alonside with Jenkins build #370. We expose sheet bounds for type layers in layer descriptor in `boundingBox`

Use boundingBox for type layers

---

src/js/actions/documents.js
src/js/jsx/sections/nodoc/RecentFiles.jsx
src/js/models/menubar.js
src/js/stores/application.js
src/js/util/path.js

This replaces all the mutable `ApplicationStore` data structures with `Immutable` ones. This fixes one untracked [bug](https://github.com/adobe-photoshop/spaces-design/blob/063ed2575864b429e258e9e2ea753e78b9db2061/src/js/jsx/Properties.jsx#L94), and is necessary for an upcoming performance optimzation.
Please test things like switching among open documents and going to and from a no-doc state, and also the recent files list.

Immutilate application state

---

src/js/jsx/Toolbar.jsx

@iwehrman Based on our discussion, I found this solution to be simpler and less hacky.
Addresses #1255

End modal state explicitly on toolbar button click

---

src/style/shared/icons.less

This relates to #1390. As part of the UI update, the selection state for the tools will be the highlight blue. Rather than fix the underline, I just switched to the blue

Update selected state for toolbar icons

---

src/js/actions/layers.js
src/js/actions/superselect.js
src/js/actions/transform.js
src/js/events.js
src/js/stores/document.js
src/js/stores/history.js

we now can guarantee that moveToArtboard (MTA) event notifications will always come after the corresponding "move" event.  This is not ideal, but its at least consistent.  If we get an MTA, that means we need to fetch the layer order from photoshop.  This needs to be updated on the newly created history state, which is a new concept in the history store that I call "amendment".  
I've also consolidated this "move" listener logic in transform.js.  We might be able to take this further, but baby steps.  Please check this out @volfied since we've talked about it some, and you are working in the same circus ring.

handle moveToArtboard events by reordering layers, and amending the current history state

---

src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/shared/Draggable.jsx

Couple of issues that arose:
1. 1 bug was caused by the fact that handleDragStart is where we defined the initial position of the dragged elements. However, if an element was never clicked on, this never ran. So moved it all into when the drag is actually moving
2. Similarly, the elements need to make sure to clear their state, otherwise there can be a slightly flicker in position when a second drag operation starts.
@chadrolfs : Could you give this a quick check for placement issues?
@iwehrman : Don't think I hurt performance with this, but would you give it a once over?

Fixes for misplacement of dragged layers

---

src/js/jsx/sections/transform/Flip.jsx

Swap enable rules used to be reliant on flip rules, but with artboards correctly working, it's time to separate them. This change will allow artboards to be swapped, and flipped (with their contents)
Addresses #1532

Separate flip/swap enable logic, and allow flip/swap for artboards

---

src/js/actions/dialog.js
src/js/actions/transform.js
src/js/events.js
src/js/fluxcontroller.js
src/js/jsx/shared/Dialog.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/stores/dialog.js

Addresses general marquee performance issues.
1. Register/deregister dialog actions each take about 100 ms, which delays marquee by a lot, now they directly edit the store
1. Transform handlers in transform actions are now debounced, so we don't constantly reset selection/bounds and layer order. This helps in cases where the user is quickly drag/dropping layers
1. Resetborderpolicies is debounced, and it does not get called if we're in a marquee select mode
1. Removed post condition for deselectAll, because it was adding a 50ms delay to marquee select starting code
1. If an action is not modal, and we're trying to end modal tool state, we no longer completely fail when the API fails. This happens if you transform layers too fast and we're in a modal state during resizing/rotating. …

Marquee select performance pt. 1

---

src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/layers/LayersPanel.jsx
src/js/jsx/shared/Draggable.jsx

1. Internally suppress handlers for the click event that follows a drag operation. Draggables (like `LayerFace`) no longer need to provide special handling to ignore these clicks.
2. Add a proper `onDragStop` handler for draggables, renaming the existing handler to `onDrop`.
Addresses #1710.

Suppress click after drag

---

src/js/actions/layers.js

This addresses #1694.  We were previously passing only one argument when transferring to `getLayerOrder()` after reordering layers.  Because of a fluxor(?) quirk which passes its own second argument when none is supplied during transfer, getLayerOrder was misinterpreting its existence and fouling up the logic.  No history state was being captured, and the rest was...

Explicitly provide false parameters when transferring to getLayerOrder

---

src/js/actions/libraries.js
src/js/jsx/Properties.jsx
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/shared/SplitButton.jsx
src/js/models/color.js
src/js/models/layer.js
src/js/stores/font.js
src/js/util/collection.js
src/nls/root/strings.js
src/style/main.less
src/style/sections/libraries/libraries-section.less
src/style/sections/style/style-section.less

this PR implements the following "add" buttons:
1 - Add Graphic: layer / multiple layers
2 - Add Character Layer: text layer only
3 - Add Stye Layer: layer with shadow effects
4 - Add Fill / Stroke Color: layer with fills / strokes attribute
*I hide the other buttons (search stock, sync, create/delete library) temporarily until they get supported*
@volfied please review. A complete UI of the asset list will be in the next PR.

CC Libraries: support contextual "Add" buttons

---

src/js/jsx/sections/layers/DummyLayerFace.jsx
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/layers/LayersPanel.jsx
src/js/jsx/shared/Droppable.jsx
src/js/stores/draganddrop.js
src/style/sections/layers/face.less

1. Adds an invisible dummy layer face at the bottom of the layer index (when the last top-level layer is a group), which exists only as an index-0 drop target.
2. Removes the "batch" draganddrop registration infrastructure. It was no longer useful in a world in which not all document layers are mounted upfront. When the registration calls went through the action system it made sense to batch them, but now it doesn't make any real difference.
Addresses #1695.

Enable dropping at the bottom of the index directly below a group

---

src/js/actions/ui.js
src/js/jsx/sections/layers/LayersPanel.jsx

For some reason, the "grabbing" cursor does not automatically reset to the "default" cursor after a layer drag until the next mousemove event. This works correctly in modern web browsers, so perhaps this is a consequence of the details of the CEF integration provided by the Spaces plugin. The patch below hacks around the issue using the `os.resetCursor` API.
Ideally this would be part of the dragging infrastructure, but the comment below explains why that might not be sufficient. We can decide how to cross that bridge once @shaoshing and @volfied get to it with the drag-and-drop functionality of the CC Libraries panel.

Reset cursor after drag and disable tooltips during drag

---

src/js/actions/documents.js
src/js/actions/edit.js
src/js/actions/history.js
src/js/actions/layers.js
src/js/actions/libraries.js
src/js/actions/policy.js
src/js/actions/shapes.js
src/js/actions/superselect.js
src/js/actions/tools.js
src/js/actions/transform.js
src/js/actions/type.js
src/js/actions/ui.js
src/js/events.js
src/js/jsx/Main.jsx
src/js/jsx/Scrim.jsx
src/js/jsx/sections/style/Fill.jsx
src/js/jsx/sections/style/Opacity.jsx
src/js/jsx/sections/style/Stroke.jsx
src/js/jsx/tools/PolicyOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/stores/policy.js

- Remove unnecessary plucks from SCUs of Fill, Opacity and Stroke.jsx
- Clean up transform/move handlers to minimize time
- Clean up overlay toggle (artifact)
- Reset border policies immediately instead of as reaction to re-render
In addition, includes:
Policy visualizer: helps see where the mouse border policies are set
@chadrolfs Can you start testing and let me know if things are better in this branch? It would be very ideal to test these in a compiled build as post condition verifications etc. really slow things down.
@iwehrman Please review.

Cavalcade of transform fixes

---

src/js/jsx/tools/SuperselectOverlay.jsx

And instead let the actual function handle it.
This was a relic of D3 highlighting when we got the mouse events... but now that we have a complete control over highlighting function, we let it handle the highlight on draw.
Addresses #1760 @iwehrman since you opened this bug, can you review?

Get rid of topLayer highlighting during draw

---

src/js/actions/layereffects.js
src/js/jsx/sections/style/Shadow.jsx
src/nls/root/strings.js
src/style/sections/style/shadow.less

This PR is the result of our discussion on adding / editing effects for multiple layers. The conclusion is that adding / editing only works when selected layers have same shadow counts (see Seth's comments below for the cases to consider if want to support any mixed effects). When the counts don't match, the panel displays "Mixed Appearances". Example:
Pasting Seth's comments for reference
```
Small scoping this would say if effects do not match, then we do to not allow editing of effects for that selection. That’s kind of annoying, but it is the smallest, simplest thing.
If we want to allow that kind of editing, here’s the  cases I’m thinking about:
1) user selects two layers for the purpose of adding effects to both at the same time.
2) user selects layers with mismatched effects, and …
```

Disable adding / editing shadow effects when selected layers have different shadow counts

---

src/js/jsx/sections/layers/LayersPanel.jsx
src/js/jsx/shared/Draggable.jsx

Also disallow dragging an empty list of layers, which happens if you try to drag any selection that involves a background layer. Also delete some dead code.
Addresses #1764.

Disallow dragging artboards onto groups

---

src/js/models/characterstyle.js
src/js/models/color.js
src/js/models/fill.js
src/js/models/shadow.js
src/js/models/stroke.js

Avoid a gang of errors when opening CMYK files, per #1732

Only parse RGB Colors, warn otherwise

---

src/js/actions/type.js
src/js/jsx/sections/style/Type.jsx
src/js/stores/font.js

To improve startup performance, and to more evenly distribute load on the UI thread in some cases, this moves the loading of the font list from startup time until it's first necessary. Luckily, loading the font list doesn't seem to be quite as slow as it used to be, but in some cases this could shave at least a few hundred ms off of startup time.
Side note: it's kind of weird that we mount the `Type` component even when there are no type layers. I guess this is a consequence of having all the type-related logic in one component. That makes sense, but it also kind of seems like the `Type` component should only be mounted when there are selected `Type` layers. Maybe I'm over-thinking this.

Load the font list lazily

---

src/js/jsx/shared/ColorInput.jsx
src/js/jsx/shared/ColorPicker.jsx

This addresses the color picker drag jitter noted in #1627.
This removes the ColorPicker's CWRP which was forcing state.color to be calculated on new props, and instead fixes the way the ColorInput component forces the picker to update by listening to a specific timetravel event from history store.
request review by señor @iwehrman

Reduce ColorPicker Drag Jitter

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/stores/search.js
src/style/search/search-bar.less

A simple priority system to better predict options. This can definitely be finessed in the future, but as a first pass, it gives better results.
Now we get:
Instead of:

Add priority values to search options so we get a better ordering of options

---

src/js/stores/draganddrop.js
src/style/sections/layers/face.less

Slightly expands the dummy layer area, and also makes the drop separator a little more responsive when dragging around invalid drop areas.
Addresses #1695, and to a lesser extent #1771.

Minor layer drag tweaks

---

src/js/models/eventpolicyset.js

I'm just gonna leave this here:
```
var scores = [1, 10, 2, 21]; 
scores.sort(); // [1, 10, 2, 21]
// Watch out that 10 comes before 2,
// because '10' comes before '2' in Unicode code point order.
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
Helps solve #1650

Use lodash sort for getMasterPolicyList

---

src/js/jsx/search/SearchBar.jsx
src/style/main.less

for issues #1742 and #1720 
For #1742, I replaced dismissing the dialog with `event.stopPropagation()` because otherwise the item that was last selected (which doesn't necessarily match what you've inputted) will be set as the input value when you click on the dialog.

Search bugs: don't close dialog on click; fix for text jumbling when highlighted

---

src/js/jsx/sections/layers/LayersPanel.jsx

This is a bit of a heavy hammer, We only need to do this for arboard changes, but i'm not sure if there is a simple test to verify that we are making a layer drag between two different artboards 
fix for issue #1614 and #1690

 fix for 1614

---

src/js/jsx/sections/layers/LayersPanel.jsx

This is a follow up to #1790. That PR resets the bounds of the selected layers after being dragged and dropped in the layers panel to account for on-canvas movement that results from auto-nesting. But, if you drag an unselected layers, it will be selected after the index is re-ordered. This patch fetches the most recent document model to ensure that the list of selected layers is current after the reorder operation.
Addresses #1690.

Reset bounds of selected layers after drag

---

src/js/actions/menu.js
src/js/fluxcontroller.js
src/js/jsx/Scrim.jsx
src/js/models/menubar.js
src/js/stores/menu.js
src/nls/root/strings.js
src/static/menu-actions.json
src/static/menu-mac.json
src/static/menu-win.json

Under help menu, now we have better organization, and toggle items for postcondition verification and policy visualization, to help with debugging.
Addresses #1711, and couple other dev needs.

Add debug menu items for postCond and PolicyVis toggling

---

src/js/actions/superselect.js
src/js/actions/transform.js
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/stores/tool.js

Couple changes:
- Remove couple enable overlay calls that caused wrong re-draws
- Change "editArtboardEvent" handler, so we reset bounds first, and then get layer order
- During layer moves, if the hysteresis wasn't broken (0,0 move), we re-enable the overlay
- Emit change events from tool store when tool modal state changes
- Listen to tool store changes in SueprselectOverlay, so we can redraw overlay when modal state changes - this should be safe, as Toolbar, Scrim and SuperselectOverlay are the only listeners of tool store
- If modal state is true, immediately clear the overlay, otherwise, debounce draw
- Clean up the code to always clean things, but not draw anything in modal states
Addresses #1683, and probably also couple more transform/overlay bugs.

Simplify overlay code, fix redraw issues with move/transform

---

src/js/jsx/sections/transform/Position.jsx
src/js/jsx/sections/transform/Size.jsx

When I added the "artboards" property to layerstructure, I mistakenly started calculating the overall artboards count in position/size enablers. Oops.
Fixes https://github.com/adobe-photoshop/spaces-design/issues/1794

Check for selection artboard count

---

src/js/actions/transform.js

Addresses #1589. When we first designed swap, we figured this might become a problem. Not swapping just top/left corners may be unexpected, but with this change, at least the features becomes reflective so user can swap back and forth to undo.

Make swap reflective

---

src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/sections/style/BlendMode.jsx
src/js/jsx/sections/style/Fill.jsx
src/js/jsx/sections/style/Shadow.jsx
src/js/jsx/sections/style/Stroke.jsx
src/js/jsx/sections/style/StrokeAlignment.jsx
src/js/jsx/sections/style/Type.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Dialog.jsx
src/js/stores/dialog.js

1. Require at registration time that `Dialog`s all have unique IDs. If we don't require that then actions invocations like `openDialog(id)` and `closeDialog(id)` have unintended, negative consequences.
2. Elaborate all `Dialog` IDs in the app to be unique, mostly by jamming the document ID into the IDs of `ColorInput`s and `Datalist`s.
3. Fix a race in `Dialog` in which the `openDialog` action could execute before an asynchronous setState call was complete. (This could cause the target DOMElement to be null in some cases when computing the position of the dialog.)
4. Fix a bug in a `Dialog` error handler: `displayName` is a `ReactElement` property, not a method. (Thanks @volfied!)
5. Fix an unrelated `Datalist` bug that prevented re-rendering when options are updated (e.g., from an empty …

Dialog bugfix extravaganza

---

src/js/jsx/sections/style/Type.jsx

Instead, just display nothing until the font list is ready. This is necessary because the font family is what should be shown, but that information isn't available anywhere except the font list.
Addresses #1797.

Don't show "mixed" typeface before font list is initialized

---

src/js/jsx/sections/layers/LayerFace.jsx

Since we aren't using a callback on startEditWithCurrentModalTool this needs to be adapted

dont use callback on Promisified function

---

src/js/jsx/sections/layers/LayersPanel.jsx
src/js/stores/dialog.js

**NOTE: This is a PR against the release branch!**
1. Work around a Photoshop issue (again) which causes reordering a group below itself to fail.
2. Demote the missing-dialog error in `stores.dialog.deregisterDialog` to warnings. When the controller resets (e.g., because of the failure above), the first thing that happens is that stores are reset. Hence, failure to deregister a dialog is in that case benign. It could indicate a problem otherwise, so I'm leaving the warning in.
Addresses #1819.
I'll prepare a separate PR against master. There would be conflicts applying this diff because `LayersPanel` has changed significantly since `release` was updated.

HOTFIX: Disallow reordering groups below themselves

---

src/js/jsx/mixin/Focusable.js
src/js/jsx/shared/TextInput.jsx

Addresses #1682 
Problem was, textinput would call _beginEdit, which would call acquireFocus, and we'd have a race condition between acqurieFocus of Focusable and setState of React.
Now we make sure acquireFocus returns the promise, and in _beginEdit we wait for that promise to first set the state, and then use the callback of `React.setState`to actually do DOM editing, which is what React suggests we should do.
@iwehrman Can you review, since I bugged you about this.
@hamburge Please be an observer/reviewer as this is important for your work

Make sure to wait for acquireFocus to finish on _beginEdit

---

src/js/actions/search/documents.js
src/js/actions/search/layers.js
src/js/actions/search/menucommands.js
src/js/stores/search.js
src/nls/root/strings.js

Issue #1804. It seems like standard on Windows is to use the abbreviations "Ctrl," "Alt," etc. and the shift symbol.
This also fixes that the shortcut for flip vertical/horizontal wasn't showing up by adding an option to not shorten the paths of search type items.

Use modifier symbols instead of strings for menu commands in search

---

src/js/models/characterstyle.js

Before this change, we were defaulting the color and showing the wrong value.
@pineapplespatula, this was your code, so please review.

Correctly set the first color of CharacterStyle

---

src/js/actions/superselect.js
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/models/layerstructure.js

Currently invisible layers are targetable on-canvas with selection and deep (command/alt) selection. This makes it impossible to target visible layers in VermilionArtboards.psd because there is a hidden grid system at the top of the layer index which covers the entire page. @placegraphichere correctly pointed out that invisible layers should not be targetable on-canvas, and that this was the source of frustration targeting layers in VermilionArtboards.psd. This change corrects that. Also, @volfied pointed out that groups with only visible children should also be treated as invisible, so he fixed that too.
Partially addresses #1734, by making smart guide overlays more consistent with the HTML overlays. (We still shouldn't draw both in different colors, but this this at least makes things …

Do not target invisible layers

---

src/js/actions/layers.js
src/js/actions/search/layers.js
src/js/jsx/Search.jsx
src/js/jsx/search/SearchBar.jsx
src/js/stores/application.js
src/js/stores/search.js
src/js/util/svg.js
src/nls/root/strings.js

Can now register a search module to either include layers in any open document or in just the current document.
If the layer is from the non-current document, the file name it comes from will appear as secondary information on the search option. Otherwise it shows the shortened layer path (just like before).
If a layer from the non-current document is confirmed, we switch to its document and select it.

Search for layers in any open document, not just the current document

---

src/js/actions/superselect.js

HOTFIX #1846: Ignore null layers during removeArtboardIDs

---

src/js/actions/layers.js
src/js/tools/type.js

I am currently getting this Warning: 
`flattenChildren(...): Encountered two children with the same key, `.$1508=114`. Child keys must be unique; when two children share a key, only the first child will be used.`
I would like to chat with someone on monday about our layer implementation and how to add duplicate/ temporary layers to the model without it being so hacky.

 first pass at adding new type layer. has warnings

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/util/svg.js
src/style/search/search-bar.less
src/style/shared/select.less

Issues #1816, #1807, and also:
- Fix for if you had a filter set, the autocomplete suggestion would not always be lined up depending on your screen resolution.
- Fix for if there were no filter suggestions, there was an extra line on the top of the drop down.
- When you click on the dialog and the input loses focus, don't show the autofill suggestion
- Removes code that supported displaying multiple svgs for filters since it is not necessary.

Search stylin'

---

src/js/actions/layers.js
src/js/jsx/sections/layers/DummyLayerFace.jsx
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/layers/LayersPanel.jsx
src/js/jsx/shared/Draggable.jsx
src/js/stores/draganddrop.js

This PR removes the Draggable component's dependencies on its parent component to pass in the **dragPosition** and **isDragTarget** by retrieving them from the DragAndDrop store directly. This will avoid duplicate in the LibrariesPanel and Tab components. More importantly, it makes the code easier to understand. 
Also resolved a position bug when you drag and move a layer fast.
**before** ![drag-before](https://cloud.githubusercontent.com/assets/118264/8881715/b02b21bc-31f6-11e5-948d-66ddbccbe520.gif)
**after** ![drag-after](https://cloud.githubusercontent.com/assets/118264/8881728/c968c51c-31f6-11e5-9400-a4057a5c23d9.gif)
I against the way of wrapping the target component with higher level components (e.g. Draggable/Droppable, or  the similar …

removes Draggable's dependencies on its parent component

---

src/js/actions/layers.js

This addresses #1843 
@iwehrman: you break it, you bought it: 9d285585eb80f49b49703de96013441742e359e1
cc @shaoshing just as an FYI since you recently ported this particular code from the LayersPanel to the action.
The resetBounds action is an accident waiting to happen.  I will attempt to make this less error-prone during the next round of history changes.  In the meantime, the *default* behavior is that resetBounds is a *history changing* event.  It is generally used as a generic "final step" in several other history-changing workflows.  But, in cases like this, it must explicitly be told *not* to change history.  I agree this is confusing.

Post-reorder bounds reset should be non-history-changing

---

src/js/actions/type.js
src/js/events.js
src/js/stores/document.js

Our history model and modal text states do not currently coexist properly.
to work around this the color set routine which was a nonoptomistic history state
if set in the modal environment should instead append to history.

Modify color change in text to only sometimes add history

---

src/js/jsx/sections/layers/LayersPanel.jsx

This is analogous to PR #1856
fixing #1843 on release branch

Post-reorder bounds reset should be non-history-changing - hotfix on release branch

---

src/js/actions/libraries.js
src/js/jsx/Scrim.jsx
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/Library.jsx
src/js/jsx/sections/libraries/assets/Graphic.jsx
src/js/jsx/shared/Droppable.jsx
src/style/scrim.less
src/style/sections/libraries/libraries-section.less

This PR implements the drag-and-drop of graphic asset from libraries panel to canvas. Works as below:
( For now, you have to double click the dropped asset to quit the transform mode, before you can do anything else )
@volfied please review

Drag and drop graphic asset from libraries panel to canvas

---

src/js/actions/search/documents.js
src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Select.jsx
src/js/jsx/shared/TextInput.jsx
src/js/stores/search.js
src/nls/root/strings.js
src/style/search/search-bar.less
src/style/shared/animation.less
src/style/shared/colors.less
src/style/shared/dialog.less
src/style/shared/select.less

Search bar styling to match the new designs. There are some missing svgs--rectangles currently replace all of the missing item type svgs, the circle on the right will be an X to clear the inputted value, and the magnifying glass will be a different version that is flipped the other direction.
Other changes:
- Show all possible filters, not just if they have corresponding options available. For example, if there are no Smart Objects in the document, still show the Smart Objects filter option.
- Fix broken datalist updating- the filter icon would not always show until the render after selecting the filter.
The designs:

Restyling of search bar

---

src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/stores/font.js

Just a quick update to reflect to the recent changes in the master.

Fix (#1863) loading a library after creating a Type layer result in errors 

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/style/search/search-bar.less

When you click inside the search dialog or on the "no options match" option, the dialog will no longer lose focus or close. Instead it will remove the autosuggest text (if it exists) and then highlight all the text in the input.
issue #1869

Search won't lose focus when you click on the dialog itself.

---

src/js/actions/search/documents.js
src/js/actions/search/layers.js
src/js/jsx/search/SearchBar.jsx
src/js/stores/search.js
src/static/menu-actions.json

You can now open the search bar when there is no document and search recent documents and menu commands to your heart's content. (issue #1888)
I added an optional property to the registered searches in the search store specifying if a category will have any options when there is no document. Then we can ignore those filters when rendering the drop down, so we don't have a bunch of filter options for layers and current documents when there is no open document.

Search for recent docs and menu commands when there are no documents

---

src/js/actions/superselect.js

Should address #1846, at least during my testing I got up to 30 enqueued clicks/deletes and nothing crashed.

Add read lock for JS_DOC to click and drag so they wait for delete

---

src/js/actions/search/menucommands.js
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/TextInput.jsx
src/js/stores/search.js
src/js/util/key.js
src/nls/root/strings.js

1. Issue #1912: puts menu commands in their default order
2. Issue #1825: we now have a lovely table for looking up localized keyCode names by their integer values
3. Fixes bug where input text was highlighted when you click on the search bar itself or when applying a filter where you had more text (for example if I typed "mylayer tex" and then applied the text filter, the remaining "mylayer" would be highlighted instead of leaving the cursor at the end)
4. Prevent error from not having registered search when finding search items and from closing dialog with escape

Search bugs

---

Gruntfile.js
src/index-build.html
src/index.html
src/js/actions/search/menucommands.js
src/nls/de/menu.js
src/nls/de/shortcuts-mac.js
src/nls/de/shortcuts-win.js
src/nls/de/strings.js
src/nls/fr/menu.js
src/nls/fr/shortcuts-mac.js
src/nls/fr/shortcuts-win.js
src/nls/fr/strings.js
src/nls/jp/menu.js
src/nls/jp/shortcuts-mac.js
src/nls/jp/shortcuts-win.js
src/nls/jp/strings.js
src/nls/locales.js
src/nls/shortcuts-mac.js
src/nls/shortcuts-win.js
src/nls/strings.js

This PR makes it possible to additionally load French, German and Japanese language dictionaries based on the locale in use by Photoshop in debug and compiled builds. For now, the dictionaries are copied as-is except for the `About Photoshop...` menu item, which has been edited in the other language dictionaries to show the current language. Later, the localization team will work with translators to update these dictionaries with translations as appropriate.
In debug builds, we just need to configure require to use the locale specified by `navigator.language` before loading the main module. In compiled builds, it's a little more complicated. We concatenate/compile the JavaScript once for each locale, and then at runtime we configure the locale and also alias `js/main` to `js/main-<lang>`, …

String localization: French, German and Japanese

---

src/js/actions/layers.js
src/js/actions/libraries.js
src/js/jsx/Scrim.jsx
src/js/jsx/sections/layers/LayersPanel.jsx
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/Library.jsx
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/jsx/sections/libraries/assets/CharacterStyle.jsx
src/js/jsx/sections/libraries/assets/Color.jsx
src/js/jsx/sections/libraries/assets/Graphic.jsx
src/js/jsx/sections/libraries/assets/LayerStyle.jsx
src/js/stores/draganddrop.js
src/style/sections/layers/face.less
src/style/sections/libraries/libraries-section.less

Now you can drag and drop layers into the libraries panel to create graphic asset.
Here are few things worth of mention:
* Adding a single linked layer is prohibited, but multiple or mixed multiple linked layers are accepted (same as standard PS)
* Asset + buttons are removed for now. More discussion is at #1859 
* Dragging a layer down to the libraries panel might cause the libraries panel's scroll event unexpectedly.

Libraries - drag and drop layer

---

src/style/search/search-bar.less

Chrome on Retina displays apparently doesn't know how to add rem values. @designedbyscience said this is currently the best workaround option to properly calculate the rem value.
issue #1806

Search options should not shift horizontally when selected

---

src/js/actions/ui.js
src/js/stores/ui.js

The previous implementation only center the selected document once after startup, leaves the other documents shifted when opening multiple document. This PR will make sure document is centered when the panel is resize (including initial startup), which is the same behavior in standard PS.
Fix issue: #1830

Center document when the panel is resized

---

src/js/actions/edit.js

`menu.nativeModal` and `menu.native` fail in debug mode when the underlying menu command isn't available. In the case of the native clipboard edit operations, these errors are harmless and can safely be ignored.
Addresses #1955.

Ignore clipboard-related errors due to menu.nativeModal failure

---

src/js/actions/application.js
src/js/actions/documents.js
src/js/actions/edit.js
src/js/actions/example.js
src/js/actions/help.js
src/js/actions/history.js
src/js/actions/layers.js
src/js/actions/libraries.js
src/js/actions/menu.js
src/js/actions/policy.js
src/js/actions/sampler.js
src/js/actions/search.js
src/js/actions/search/menucommands.js
src/js/actions/shapes.js
src/js/actions/shortcuts.js
src/js/actions/superselect.js
src/js/actions/tools.js
src/js/actions/transform.js
src/js/actions/type.js
src/js/actions/ui.js
src/js/fluxcontroller.js
src/js/locks.js

The controller currently assumes that actions will specify the entire set of read and write locks necessary to safely execute the given action _as well as all other sub-actions to which the action may transfer_. Suppose, for example, we have:
```javascript
var foo = function () {
// write A
};
foo.writes = [A];
var bar = function () {
// write B, and then
return this.transfer(foo);
}
bar.writes = [A, B]; // A is needed because of the transfer to foo
```
Above, the `foo` action writes to state protected by the `A` lock, and so includes the appropriate write lock declaration. The `bar` action itself only writes to state protected by the `B` lock, but also transfers to `foo`, and so must also include all of the locks specified by `foo` in its lock declaration. 
Suppose now we update `foo` so …

Local lock declarations

---

src/js/actions/libraries.js
src/js/models/layer.js
src/js/util/path.js

Addresses #1860. Problem was, we were forcing all graphic assets to be Photoshop assets, which was confusing both Photoshop and library panel. This should provide more parity with the Classic panel.
@shaoshing Please review.

Correctly represent different graphic assets

---

src/js/actions/layers.js
src/js/actions/libraries.js

This PR fixes #1944 (CC Lib: dragging asset with Opt/Alt key to place expanded layers results in error)

Libraries: should add all new layer IDs for expanded graphic asset.

---

src/js/actions/libraries.js
src/js/util/path.js

Using `os.getTempFilename` makes `createElementFromSelecteLayers` safe to run on different platforms.

Apply new os.getTempFilename api in graphic asset creation.

---

src/js/actions/superselect.js
src/js/models/layerstructure.js

Addresses #1940, and likely another superselect bug we may not have noticed.
Problem with #1940 was, I was using PS hit layer IDs for deep select, without artboards taken out.
Other bug is more nuanced, we start with `topBelowArtboards` and then systematically replace selected layers with relatives. However, if a relative is in the `topBelowArtboards`, it would remain at the beginning of the list, breaking z-order.

Superselect Fixes

---

src/js/actions/transform.js

Code cleanup: Added an underscore prefix to transform.flip, align, and distribute to indicate that they are private. This addresses #1895.

Added an underscore prefix to transform.flip, align, and distribute 

---

src/js/actions/search.js
src/js/actions/search/menucommands.js
src/js/jsx/help/KeyboardShortcuts.jsx
src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/TextInput.jsx
src/nls/root/menu.js
src/nls/root/shortcuts-mac.js
src/nls/root/shortcuts-win.js
src/nls/root/strings.js
src/static/menu-actions.json
src/static/menu-mac.json
src/static/menu-win.json

:bug: :bee: :beetle: :snail: :ant: 
-#1929 Put search shortcut in the Keyboard Shortcuts dialog and moved the command to `Window` from `Layer`, but if the executive decision is to put it in `Edit` (or somewhere else), I can move it again.
-I was also dissatisfied with how things looked after 507b561bf74b2acfe2b800472121b2013010b704, since the text would sometimes highlight momentarily before going to the end of the word, so I undid most of those changes and added a prop to TextInput for when we will never be selecting all text. I think it now looks cleaner and means there are fewer changes in `TextInput.jsx`
-Also #1930, #1931, #1932

More search bugs

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/stores/search.js

Order search results so that the group of options that contains the suggestion is on top. Also if there is no suggestion, select the first item. With these changes, you will always be able to see what is selected (with the one exception of the first render, when you open the dialog and click on the text input).
As a side effect, also fixes a bug where the search bar would not reopen after hitting escape on a search with a filter applied. The dialog would not close properly in that case, because the filter element was still selected. Now, after applying a filter, the first element of the list will be selected and the modal will fully close when you hit escape.

Better ordering of search results

---

src/js/actions/libraries.js

I've removed the IMS connection from Photoshop as we don't use it. And changed the descriptor names... because there is no IMS information anymore.
This will require pg-dev-mac 440 to work. So @shaoshing, please merge this once you grab the latest Jenkins build as to not disturb your library work progress.

Use correct descriptor name for libraries

---

src/js/jsx/Search.jsx
src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Select.jsx

Instead, keeps a list of IDs that correspond to items with type "filter" to check if an item is a filter, or look directly at the item's type if that is easily available.
Issue #1966

Don't encode search item type in IDs

---

src/js/actions/layers.js
src/js/actions/transform.js
src/js/jsx/sections/style/Type.jsx
src/js/jsx/sections/transform/Size.jsx
src/js/models/characterstyle.js
src/js/models/text.js

Longer term, we want to scale the font sizes in text layers that are transformed on canvas for both typographic and asset-export reasons. For the short term, this pull request changes how font sizes are interpreted in affine-transformed text layers such that a font size that is implied by that transform is now used instead of the literal font size used by the text rendering engine.
More concretely, this pull request: 1) loads `impliedFontSize` into the `textSize` property of the `CharacterStyle` models, 2) removes the `hasTransform` property in text models, and 3) removes the checks that disable the `Size` component in the transform panel and the size input of the `Text` component. It's also now necessary to 4) update the `textSize` property whenever a layer is text layer resized, so when …

Allow setting the font size on transformed layers

---

src/js/jsx/shared/Button.jsx
src/js/jsx/shared/TextInput.jsx
src/js/jsx/shared/ToggleButton.jsx

The new version of `classnames()`, which replaced the old react add-on, is more powerful and smart and stuff.

Clean up of a few older components that weren't using classnames() to its full potential

---

src/js/jsx/Main.jsx

Before it would center the dialog based on your preferences, even though there is always one panel when there is no document. Now, we always assume there's one panel when there is no document open. #2003

Center search dialog when there is no document

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx

This would happen because the updating of the search suggestion would occur when Datalist's filter value went from `null` to `""`. This meant that if you had no text in the input and clicked on an item, the first item would always be selected.

Prevent incorrect search option from being selected occasionally on click

---

src/js/actions/libraries.js
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/Library.jsx
src/js/jsx/sections/libraries/assets/CharacterStyle.jsx
src/js/stores/library.js
src/style/sections/libraries/libraries-section.less

this PR includes the following improvements over the CC Libraries:
* Memorize the last selected library, and restore it for new documents or reload - 1909
* Do not center library content vertically
* Can add graphic asset with long layer name - 2001
* Correctly render text style with no color - 1994
* Allow drag-n-drop on the initial library - 2008
@volfied please review

CC Libraries - improvements

---

src/js/jsx/PanelSet.jsx

No more flashing from no-doc state to new or open document

Proper check for no doc to some doc state

---

src/js/jsx/shared/Datalist.jsx
src/style/search/search-bar.less

Issue #2025. Adjust the suggestion width to be (width of the whole text input) - (width of entered text)
@iwehrman can now open up an image of his favorite tweets without screaming :scream:

Clip search bar suggestion if it is longer than the text box

---

src/js/actions/search/libraries.js
src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/stores/search.js

Issue #2024. 
There's currently no way to tell the difference between filtering for one library versus another when they have the same name, but it will at least properly filter when you select either of the two options.
I also changed back how Datalist updates when you apply a filter to a forceUpdate instead of checking if the icon changes, because when you have the "all libraries" filter selected and then pick a specific library, the icon won't change and the Datalist has no way of updating.

Handle searching for libraries that have identical names

---

src/js/actions/export.js
src/js/jsx/PanelSet.jsx
src/js/jsx/sections/export/ExportPanel.jsx
src/js/jsx/sections/export/LayerExports.jsx
src/style/sections/exports/exports.less

This PR contains a few minor style tweaks, and a semi-major refactoring of LayerExports & ExportPanel.
Style...
1. Remove Asset (trashcan) was sized wrong
1. Export headers alignment (esp suffix) was wrong
1. Collapse Export Panel didn't work at all (only partially works now)
1. The "add asset" button needed to be moved up (adjacent to panel title)
New feature: When adding the first asset, the layer is automatically enabled for export (ie, it is "checked" in the export all dialog)
Refactor: as part of moving the "add asset" plus button, I needed to move logic up in to the ExportPanel, which is now the component that watches the export store.  I think this improved the organization a bit.

Export style fixes; adding first asset enables layer for export; moved 'add' button

---

src/js/actions/layers.js
src/js/tools/type.js

This works around an apparent PS race condition in which we sometimes get both a "make" and a "createTextLayer" event at the beginning of the type modal tool state. If it's the latter, and it happens after the make event, then bad things happen. With this PR, if that happens we now log a warning and reset the selected layers. 
Addresses #1969

Work around occasional duplicate PS make event

---

src/js/actions/layers.js
src/js/actions/superselect.js
src/js/actions/transform.js
src/js/models/layer.js
src/js/models/layerstructure.js
src/js/stores/document.js

Speed up artboard creation by using new output from the `make` event that includes the resulting name and layer IDs for the new artboard to update the model without resetting the entire document. This reuses the existing group creation infrastructure, but requires updating the layer index from PS afterward due to auto-nesting.
Side note: I renamed the `layers.getLayerOrder` action to `layers.resetIndex` because that's more consistent with all the other reset-model-from-PS actions.
Requires CL 1036241 (pgdev ~465 from Friday afternoon). Addresses #1414.

Faster artboard creation

---

src/js/actions/sampler.js
src/js/actions/shapes.js
src/js/events.js
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/jsx/sections/style/Fill.jsx
src/js/jsx/sections/style/Stroke.jsx
src/js/jsx/sections/style/StrokeAlignment.jsx
src/js/jsx/sections/style/StylePanel.jsx
src/js/models/fill.js
src/js/models/layer.js
src/js/models/layerstructure.js
src/js/models/stroke.js
src/js/stores/document.js
src/js/stores/menu.js
src/js/stores/style.js

This one is a hairy PR, so @chadrolfs and @ktaki, please slam on the fill/stroke related workflows a little on this PR before it's merged.
Clears out the layer model to have a singular stroke and fill information, since we essentially kept a list of them when there could only be one. :sword: Gets rid of all the pesky fill/strokeIndex variables being thrown around, and makes sure style sampling/pasting and library style application work right.
@iwehrman can you review this bad boy?

Singularize stroke and fill for layer models

---

src/js/models/menubar.js
src/static/menu-actions.json

These actions only need a document if there is no input modal open.

Allow copy/paste/select all in search bar open when there is no document

---

src/js/actions/documents.js

Thanks to @TomRuark, there is now a layer ID included with the `placeEvent` event, and we can use this to call `layers.addLayers` to update the document model instead of calling `documents.updateDocument`, which is much slower.
Addresses #1063.

Faster smart object placement

---

src/style/sections/style/style-section.less
src/style/shared/button.less
src/style/shared/split-button.less

What it says. The disabled cursor styling is not disabled elsewhere, e.g., in Libraries drag and drop.
Addresses: concerns that this was a bad idea.

Eliminate disabled cursor styling on buttons

---

src/style/search/search-bar.less
src/style/shared/select.less

Uses flex display to cut off additional search info. If the primary info is very long it will have a primary-info-sized ellipsis as well. Issue #2053

Make search item overflow ellipsis color match secondary info

---

src/js/actions/layers.js
src/js/actions/type.js
src/js/events.js
src/js/jsx/Toolbar.jsx
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/style/Type.jsx
src/js/models/characterstyle.js
src/js/models/paragraphstyle.js
src/js/models/text.js
src/js/stores/document.js
src/js/tools/superselect/type.js
src/js/tools/type.js

This is modal-type bug-fix PR. I believe it addresses issues #2071, #2009, #1927, #1883, #1881, #1857, #1691. There are still a number of type issues it does not address, so please take a look at the [Type issue label](https://github.com/adobe-photoshop/spaces-design/labels/Type) if you see a problem during testing to see if an issue has already been filed.
Highlights:
* Removes the `*Assigned` properties in `ParagraphStyle` and `CharacterStyle` in favor of a simpler `mergeWith` operation for resolving inconsistencies.
* Simplifies and throttles the `updatedTextProperties` event handler, which PS emits whenever the style properties for the current cursor position/text selection change in the modal state.
* Applies this handler in the select type sub-tool, as well as in the full type tool. …

Modal type bug fix grab bag

---

src/js/actions/layers.js
src/js/events.js
src/js/stores/document.js
src/js/stores/history.js

After committing a new text layer, some time in the future get a 'make' event.  If we determine that this event is related to the type layer we've just added to the model (and for which we've already captured a history state), then we need to *amend* the history state with the late-breaking information.
In practice this means the layer name has changed.  It is now informed by the type layer's text content.
This PR also spruces up history state 'amendment' handling;  it is now generally handled more efficiently, and less chatty.
addresses #2092

After type layer commit, 'make' event handler resets Layers and then amends current history with the result

---

src/js/actions/transform.js

Calls `resetLayers` on type layers at the end of `transform.setSize`. Also, removes `transform.setBounds`, which was dead code.
Note for testing: Photoshop doesn't change the implied font size if you just change the layer's width; it seems to only actually care about the height. (I'm not sure if that's guaranteed though, so I'm not factoring that into the logic here.)
Addresses #2093.

Reset type size after resizing text layers in the transform panel

---

src/js/actions/export.js
src/js/jsx/sections/export/ExportAllPanel.jsx
src/js/jsx/sections/export/ExportPanel.jsx
src/js/jsx/sections/export/LayerExports.jsx
src/js/jsx/shared/CheckBox.jsx
src/js/jsx/shared/Gutter.jsx
src/js/locks.js
src/js/models/documentexports.js
src/js/models/exportasset.js
src/js/util/exportservice.js
src/nls/root/strings.json
src/style/sections/exports/exports.less
src/style/shared/button.less

Export All panel:
- Improved UI including grey tri-state checkboxes!
- Added two new checkboxes to quickly select (mark for export) All artboards, and All non-artboards
- Layers are listed in proper layer order, including artboards in reverse (per dave, I think)
Tech Debt Payments:
- Moved the definition of supported scales and formats into the model
- Improved error handling of asset export, including adding a timeout since generator seems to sometimes just not respond
http://cl.ly/2w3z3U350J2i

Export enhancements: quick selection, and improved style in export all panel

---

src/js/actions/layers.js
src/js/models/menubar.js
src/nls/root/menu.json
src/static/menu-actions.json
src/static/menu-mac.json
src/static/menu-win.json

createArtboard can now handle inputs of type Bounds, payload, and undefined; if artboard selected, uses that as default size if no preset or Bounds have been passed in. Addresses issue #1905

Added new functionality to the Menu bar - Create Art From Template

---

src/nls/root/shortcuts-mac.json
src/nls/root/shortcuts-win.json

Previously it was CMD + g. Now it is corrected to CTRL/CMD ; 
Regarding issue #1938

Fixed the keyboard shortcut for Toggle Guides

---

src/js/models/shadow.js

Ability to achieve lighter colors is impossible with current default
set to "multiply". This is a stop gap until we can get blend modes into
effects panel options.
This will take forever to review.
addresses #2087

Set the default blend mode for shadows to be "Normal"

---

src/js/util/layeractions.js

This adds a short-circuit return to `playSimpleLayerActions` when the one target layer is equal to the one selected layer. This helps avoid problems with selecting layers in modal tool states. Presumably this could be pushed into `playLayerActions` more made more wide-ranging, but I couldn't immediately convince myself that that was safe. (E.g., I think if there is more than one layer, the existing function will play the play object once for each layer, in each case with only the one layer selected, and so we can't necessarily skip the dance in that case?)
Addresses #1881.

Skip the selection dance if possible

---

src/js/actions/documents.js
src/js/actions/guides.js
src/js/actions/index.js
src/js/actions/tools.js
src/js/events.js
src/js/jsx/Scrim.jsx
src/js/jsx/Toolbar.jsx
src/js/jsx/tools/GuidesOverlay.jsx
src/js/models/document.js
src/js/models/guide.js
src/js/stores/document.js
src/style/main.less
src/style/tools/guides.less

Allows: 
- Dragging of existing guides
- Dragging a guide off screen to delete
- Overlay at the edges of canvas, allowing new guide creation
Technicals:
- Policies are created around each guide to allow mouse events to go to Photoshop during move tool
- Because guides of inactive documents can't be read, we re-read guides every time document changes
- Because guides are 1 indexed, rangeOpts fails if there are 0 guides, so we immediately return empty array in no guide cases
Requires latest spaces-adapter#134

Guides in Design Space!

---

src/js/actions/layers.js
src/js/models/layerstructure.js

Addresses #2090, which was actually two bugs in one:
1. When creating an artboard from a document with a locked background layer, PS first unlocks the background layer, which implicitly replaces the background with a new layer, and then Design Space panicked when resetting the z-index because it observed that the new z-index had layers that weren't in the old z-index. This fixes that problem by first explicitly unlocking the background layer (and our model) before creating the artboard.
2. The response from PS when creating an artboard was different depending on whether or not there was already an existing artboard in the document. The change in #2065 wasn't tested against the "first artboard" case until recently, which is why this inconsistency just became apparently. As of CL 1037057, …

Fix initial artboard creation from non-artboard documents

---

src/js/jsx/tools/GuidesOverlay.jsx

Addresses #2128 
Problem was, because overlay was still showing, our synthesized mouse event was not going to Photoshop.Created a Watson bug for Fitz, since it goes to PS in Mac, and not in Windows, causing the issue.

Hide the guide overlay on click so mouse events can go to PS

---

src/js/jsx/sections/export/ExportPanel.jsx
src/js/jsx/sections/style/StylePanel.jsx
src/js/jsx/shared/Button.jsx

Stop event propagation of double click events in title header buttons (Export add asset and Style copy/paste), even when disabled, the latter with new `onDisabledClick` and `onDisabledDoubleClick` event handlers on `Button`.
Addresses #2149.

Suppress double click events in title header buttons

---

src/static/menu-mac.json

Add submenu attribute to designate the "help" menu as the OSX help menu.
The functionality require CL: 1037599 in team sandbox

Added attribute to designate the help menu as the OSX help menu

---

src/js/actions/sampler.js

Apparently it's a design choice. So we disable type sampling
Addresses #2137

Disable type sampling in multi-text-runs since they don't have type info

---

src/js/actions/documents.js
src/js/actions/transform.js

Idea for this fix came to me during the design meeting... We can just disable auto expand during swap, so the PS canvas size does not shift underneath us in between swap operations!
Addresses #1532, so happy to finally fix it.
Requires https://github.com/adobe-photoshop/spaces-adapter/pull/136

Disable auto expand during swap

---

src/js/actions/type.js
src/js/jsx/sections/style/Type.jsx
src/js/jsx/shared/ColorInput.jsx
src/js/jsx/shared/ColorPicker.jsx
src/js/stores/document.js
src/style/shared/color-picker.less

This adds an opaque mode to the `ColorInput` and `ColorPicker` that constrains selectable colors to be opaque and disables the opacity slider. The `ColorInput` used by the `Type` component now uses opaque mode when in a modal tool state.
This is definitely imperfect, but I think it's an improvement. Sometimes the non-opaque color flashes in the input before switching to an opaque color because it takes a while for PS to send us the modal state change notification. There's also nothing we can really do about people typing in non-opaque colors. 
Also, in opaque mode we force 100% opacity, but my first attempt just froze the existing opacity. After trying it out, it seemed like 100% opacity was preferable because it was more clear that the opacity was completely disabled.
Addresses #1914.

Color picker opaque mode

---

src/js/actions/guides.js
src/js/models/guide.js
src/js/models/layerstructure.js
src/js/stores/document.js
src/js/util/exportservice.js

Requires Playground-dev-mac#499 and https://github.com/adobe-photoshop/spaces-adapter/pull/135
- If all selected layers are part of the same artboard, guides created will be artboard guides
- Correctly sets policies for guides based on selection

Support artboard guides

---

src/js/actions/search/layers.js
src/js/actions/search/libraries.js
src/js/jsx/Search.jsx

Work around a combined React-and-PS bug in which we can't block actions until React rendering has finished, and PS stops running CEF entirely during the place-graphic modal tool state. More details in #2177, which this "addresses."

SuperHack: Fix graphic placement from search bar

---

src/js/actions/superselect.js
src/js/jsx/tools/SamplerOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/models/bounds.js
src/js/models/layerstructure.js

Updated the rules for superselect a bit. Back in April, to make layers outside canvas selectable I made changes and used PS's hitTest only for z-order sorting. Well, it caused bugs like #2112 and #2113 where bigger layers in other artboards, that are higher in the z-order would highlight over the layer user was visibly hovering on.
Now we restrict superselect with artboards:
- A layer is highlighted only when the mouse is over it in the artboard. Highlight is still for the full layer bounds, but doesn't get lit unless the mouse is in the artboard.
- Superselect clicks can only select layers on visible pixels.
@iwehrman Please review, as I've bothered you the most about this issue.

Improved select tool selection criteria

---

bower.json
src/js/actions/export.js
src/js/jsx/sections/export/ExportAllPanel.jsx
src/js/models/documentexports.js
src/js/util/exportservice.js

- A few minor optimizations
- In debug mode, try to see if there is plugin websocket (briefly) *before* the usual routine of checking/starting generator.  This Allows us to use a remote generator in debug mode.
- Provide "maxConnectionAttempts to NodeDomain (this requires a new version of generator-connection.   PR forthcoming)
**This requires `bower install` to pick up the new generator-connection version specified in bower.json**

Export generator plugin connection improvements

---

src/js/jsx/sections/style/Fill.jsx
src/js/jsx/sections/style/Shadow.jsx
src/js/jsx/sections/style/Stroke.jsx

Addresses #2079
This is really a temporary fix for this bug, as we are changing the looks for these panels right now. Also seeing if switching the visibility icons like this is any better...not sure it is

Fix for Fill, Stroke and Effects icons bug

---

src/js/jsx/tools/SamplerOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx

Fixes issues that happened when opening new documents that DOM elements would be out of date and we'd be trying to retrieve their layer models from an invalid document layer tree.
Argh

Safety checks for updateMouserOverHighlights calls during DOM updates

---

src/js/actions/export.js

Fixes an issue with loading the export plugin in the situation where we must first start generator

Export plugin init hot fix: Fixed binding in _initService

---

src/style/search/search-bar.less

I came across an obvious copy-and-paste error in the search-bar style code, so I made changes to match what the intent apparently was.
Related to #1951, in that a fix for that issue would have prevented this bug. Would you care to review this, @DivyaPrabhakar?

Search bar style copy-and-paste bugfix

---

bower.json
src/js/actions/export.js
src/js/util/exportservice.js

When our generator plugin starts up, it stores the port number (on which it has started the websocket) in photoshop's custom prefs.
DS will now try to fetch that value before attempting to connect.
Depends on:
- https://github.com/adobe-photoshop/spaces-adapter/pull/137
- https://github.com/adobe-photoshop/generator-connection/pull/5

Export startup procedure now checks photoshop for the configured port

---

src/js/actions/tools.js
src/js/models/bounds.js

We were installing border policies before guide policies, which gave them precedence. So a guide within the selected layers' border would not be clickable (clicks would come to us). #2170 
Now we install guide policies AFTER border policies so they are higher priority.

Reset guide policies AFTER border policies are installed

---

src/js/actions/shapes.js

If it wasn't provided, we were trying to access values from within it, and _.merge would fail.
Addresses #2228

Initialize shapes options to empty object if null

---

src/js/actions/libraries.js
src/js/actions/shapes.js
src/js/jsx/sections/style/Type.jsx
src/nls/root/strings.json

Addresses #2228, #2234, #2233 
Also sets libraries.applyColor to use transactions (seems like I actually forgot to do this @shaoshing!)
@shaoshing can you review?

Transactionize libraries.setColor, and fix shape actions

---

src/js/actions/layers.js
src/js/fluxcontroller.js
src/js/tools/type.js

There are a variety of problems when creating a new type layer in a modal state. After we learn about the new layer from the `createTextLayer` event, we call `addLayers` to initialize the model, but that model does not yet have any style information due to a PS bug. However, we do get an `updateTextProperties` event with the initial style information, but we were previously losing that because it came before the `addLayers` call had finished. This works around those problems by saving the style properties from this event and applying it to the new layer model as soon as it has been created.
Note that, in a perfect world, all these handlers would be actions managed by the flux controller. Unfortunately I think a bigger refactoring job will be needed to convert all these handlers to actions …

Fix initial type properties in modal state

---

src/static/menu-mac.json
src/static/menu-win.json

Changed the KBSC for Ungroup to CMD + SHIFT + g (Mac) and CTL + SHIFT + g (Windows). Note, the previous KBSC on Windows was ALT + CTL + g. Not sure if that was on purpose but changed it to SHIFT + CTL + g for now, let me know if that is not correct. 
Regarding issue #1491

KBSC change for Ungroup layers on Mac and Windows

---

src/js/actions/sampler.js
src/js/jsx/sections/style/Stroke.jsx
src/js/jsx/tools/SamplerOverlay.jsx

One more for the count... Stroke.jsx was not assigning some options in certain cases, causing an undefined value to go to PS. #2246
Also, the inside stroke in Sampler HUD was calling applyColor instead of applyStroke, so fixed that too.
#2234
Also copies stroke into the clipboard, instead of just strokeColor (which was no longer used)

Set stroke options correctly and apply stroke

---

src/js/actions/export.js
src/js/util/exportservice.js
src/nls/root/strings.json

This PR contains two major things:
1. When a user initiates an export, they are presented with a "folder chooser" dialog to choose where the assets should be exported.  This starts in their home directory, but then should remember their choice during this session.  (improvements to follow).
1. Consistency with the new version of the generator-spaces plugin that went through a few breaking changes in order to clean things up.
Requires generator-spaces PR
merged ~~https://github.com/adobe-photoshop/generator-spaces/pull/3~~
min version:  jenkins playground-dev builds (~535win / 538mac) 
One particular caveat:
When in the OS folder chooser dialog, do NOT try to create a new folder.  Choose an existing one.

Allow the user to choose an export folder during each export

---

src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/NumberInput.jsx
src/js/jsx/shared/TextInput.jsx

Revert focus-handling changes from 9285681 so that keyboard focus isn't returned to PS after tabbing away from a datalist. This broke tabbing through datalists, as described in #1877.
There are still issues with focus in modal type states, but @jfitz-adobe is working on a different solution for that. There are also still issues with keyboard navigation and `Datalist`, which this does not address. If you find other concrete issues, please file them separately.
Addresses #1877.

Do not return keyboard focus to PS on blur

---

src/js/actions/type.js
src/js/events.js
src/js/stores/document.js
src/js/tools/type.js

1. Parse style properties from `createdTextLayer` event as well as the `updateTextProperties` event, instead of having to back-patch the properties from the latter event after calling `addLayers`. This reverts the garbage from #2242.
2. Removes the `resetLayers` call from the type tool deselect handler because I have no idea why it does that. Addresses #1936. 
Requires Mac Jenkins build pgdev.541 from Thursday evening.

Type tool API update

---

src/js/stores/font.js

On autoLeading, leading would be -1, and `if (leading)` would return true causing the multi line text cramming issue.

Get lineHeight from a text style only if it's positive

---

src/js/actions/edit.js
src/js/actions/history.js
src/js/actions/layers.js
src/js/actions/type.js
src/js/events.js
src/js/jsx/sections/style/Type.jsx
src/js/stores/document.js

undo/redo
- While in modal state* the UNDO action will now play the actual 101 command in photoshop.  This is OK because photoshop deals with history differently in the text world.  More improvements possible, but this is a decent first step.
- Still has minor bug with showing menu item in the correct situations
updating text properties while modal will **NOT**:
- Send `historyStateInfo` as a play option to photoshop
- Amend history (admittedly I was confused on this matter coming in to this bug work)
- Reset bounds (which, awkwardly, is the thing that *correctly* creates history state when non-modal)
Committing an existing text layer will now AMEND history (via the "set" event).  As an example, this means that the correct "mixed" state will be captured after a multi-color-text run is …

Type modal history fixes

---

src/js/actions/type.js
src/style/shared/split-button.less

The problem was that we were trying to merge type options into another `undefined` set of options, which results in undefined. That is, `_.merge(undefined, x) === undefined`. This broke the alignment action because the `canExecuteWhileModal` option is required in the modal state. This fixes the problem by having `_getTypeOptions` perform the merge into a fresh object.
Addresses #1882.
**Update:** Also pushed dccdd8b to address #2277.

Fix modal text alignment

---

src/js/actions/index.js
src/js/actions/typetool.js
src/js/tools/type.js

This uses the new `toolModalStateChanged` event's `reason` property to handle canceled type modal states. The goal is to reset the layers, but that should _only_ happen if there was no `deleteTextLayer` event, which handles the exit from the modal state specially by removing the layer models.
Partially addresses #2257, but note that there is [a core bug](https://watsonexp.corp.adobe.com/#bug=4045762) which notes that there is no `deleteTextLayer` event when canceling out of a modal tool state for a layer that has never been committed. This causes a Photoshop error in that case because `resetLayers` is unable to reset models for layers that have already been deleted in the Photoshop document. But, when that core bug is addressed, no further JavaScript changes should be required.

Update type properties after canceling edits

---

src/js/actions/documents.js
src/js/actions/libraries.js
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/libraries/Library.jsx
src/js/jsx/sections/libraries/assets/AssetPreviewImage.jsx
src/js/jsx/sections/libraries/assets/AssetSection.jsx
src/js/jsx/sections/libraries/assets/Graphic.jsx
src/js/jsx/shared/TextInput.jsx
src/js/models/layerstructure.js
src/js/models/library_sync_status.js
src/style/sections/libraries/libraries-section.less

* Make sure to update asset's preview image when it is edited outside of DS (e.g. Ai, or win Ps)
* Remove the last "updateDocument" in libraries actions.
* Prevent long asset title from scrolling horizontally when scrolling the asset list.
#1860 CC Lib: adding a vector smart object imports into library incorrectly (hopefully)
#2230 Positions of icons are off from clickable regions in Libraries panel header
#2201 Stale empty layer remains after placing cloud-linked smart object in new artboard

CC Libraries - improvements and bug fixes

---

src/js/jsx/tools/GuidesOverlay.jsx

This prevents component updates occurring due to mouse moves in Guides Overlay, which caused the blink. 
Addresses #2130

ShouldComponentUpdate for GuidesOverlay

---

src/js/actions/guides.js

Addresses #2253, in certain guide locations, the edge of the policy would be at the wrong place and mouse events would stay with us.

Floor and ceil the guide policy areas so they sit pixel perfect

---

src/js/jsx/sections/transform/Rotate.jsx

Addresses #2298, and reverts to our old behavior. Later optimizations must have started updating Rotate component all the time.

Rotate#shouldComponentUpdate that checks doc and layer IDs

---

src/js/jsx/tools/PolicyOverlay.jsx

When showing policy frames, also show the canvas bounds (as defined by the UI edges) to make it easier to debug issues with the overlay offsets, etc. It looks like this:

Draw canvas bounds with policy frames

---

src/js/actions/documents.js
src/js/actions/export.js
src/js/actions/layers.js
src/js/events.js
src/js/jsx/sections/export/ExportAllPanel.jsx
src/js/jsx/sections/export/ExportList.jsx
src/js/jsx/sections/export/ExportPanel.jsx
src/js/models/documentexports.js
src/js/stores/export.js
src/js/util/exportservice.js
src/js/util/global.js
src/nls/root/strings.json

Two functional changes:
- Now supports document-level export, for NON AB documents, using the Export Panel with *no layers selected*
- An :arrow_down: icon in the export panel which performs an export of the selected layer(s) or document.
Reviewer notes:
- Added `EXTENSION_DATA_NAMESPACE` to global.js (we discussed this on a recent engineering powow, which mixed agreement)
- I started the process of handling multiple layer selection in export panel, but stopped short in order to keep this PR of reasonable size.  A PR is forthcoming that will take it further.
- Moved the step of setting assets to "requested" status as part of the action, instead of it being orchestrated within react
- Renamed the react component to `ExportList` since it now handles document level exports, and will soon …

Allow document-level exports

---

src/js/actions/ui.js
src/js/events.js
src/js/jsx/Main.jsx
src/js/jsx/PanelSet.jsx
src/js/jsx/Toolbar.jsx
src/js/stores/ui.js

1. Updates panel sizes (and hence the adapter's "overlay offset" state) when the display configuration changes, using the new `displayConfigurationChanged` os event. Addresses #2214.
2. Reduces `updateToolbarWidth` to a helper function that immediately transfers to `updatePanelSizes`. Removes the `TOOLBAR_PINNED` event.
3. Averts an unhandled exception when clicking on the toolbar before any tool is known to be active. Addresses #2156.
4. Correctly updates the toolbar width even when unpinned. Addresses #2265.

Update panel sizes when display configuration changes

---

src/js/actions/guides.js
src/js/actions/layers.js

My recent core related guide changes, I introduced a `reverse` call to getGuidesForDocumentRef call... so editing one guide was causing another guide to change.
I also noticed that artboards move their guides with them, but we don't do anything to update the guides. So for now I'm querying all guides on resetBounds calls. In the future this can be done smarter by just asking for that artboards guides if any is moved (I'd like to unblock guides first, and then fix this in a separate issue)
Addresses new gripes in #2144

Get guides in correct order from PS and ask for them on layer moves

---

src/js/actions/superselect.js
src/js/actions/transform.js
src/js/events.js
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/tools/superselect.js

f9a3db3 addresses #2150, and it works. However, PS doesn't always send us ALL the nudge events, so if you want to test it, please download latest Jenkins of pg-dev to get ALL the nudge events.
40c6003 addresses #2301, problem was, I was only finishing marquee select if there was a rectangle being drawn, so for small enough distances / fast mouse events / action not finishing on time, the marquee flag would remain up, and overlays would be broken. Now it's more stable, and we reset the flag on tool select as well (so user can't switch tools while marquee selecting to leave the flag up, darn user!)

React to Nudge, and fix marquee

---

src/js/models/layerstructure.js

Will help address #2187, we basically were not including owner artboard in superselectable layers, so now artboards are special cased, so they can be selected/dragged in one go.

Always include artboards in superSelectable

---

src/js/actions/documents.js
src/js/actions/superselect.js
src/js/actions/transform.js
src/js/actions/type.js
src/js/actions/ui.js

Back in #1960, when we had on canvas transform, we had to toggle the overlays for a lot of actions ourselves. But with the invention of cloaking technology, and us drawing transform through Photoshop, most of those toggles became obsolete...
Simple code clean up, removed it where it didn't make a difference.

Toggle overlay cleanup

---

src/js/actions/ui.js
src/js/models/document.js
src/js/models/layerstructure.js
src/static/menu-actions.json

If there is no selection during zoom in/out, we keep the center fixed and zoom out/in correctly.
Addresses #661, and possibly couple other zoom bugs that I will add as I see them.
#2206
#2169
#1081
#1709
@iwehrman You sic'ed me on this, you review it :)

On no-selection, don't shift zoom center.

---

src/js/actions/tools.js

This makes cmd dragging easier on transform handles. Before, you had to click, and then hold down cmd to distort.
Addresses #2168

Add a always-propagate policy for command modifier (distort) on border

---

src/js/jsx/shared/Select.jsx

Problem: updateAutoFill would not match any filter, and set the `state.id` of Datalist to null... Then we would use selectExtreme to select the first result. And as far as Select knew, it was already at that ID, so it didn't need to set it's own state again. So that's why it would work when we typed 'do', but not 'doc'.
Always selecting it makes sure that states are correct.
Addfresses #2347

Always set the ID on Select#setSelected

---

src/js/actions/guides.js
src/js/events.js
src/js/stores/document.js
src/js/stores/menu.js
src/nls/root/menu.json
src/static/menu-actions.json
src/static/menu-mac.json
src/static/menu-win.json

Requires https://github.com/adobe-photoshop/spaces-adapter/pull/145
Adds View>Clear Guides button that clears out all guides in current document.

Implement clear guides menu item and action

---

src/js/actions/ui.js
src/js/jsx/tools/GuidesOverlay.jsx

@jsbache pointed this out. When PS loses focus, we should toggle our overlays so the guides overlay doesn't just stay lit. We re-enable them on app focus.

Toggle overlays on activationChanged events

---

src/js/actions/documents.js
src/js/actions/libraries.js
src/js/jsx/Scrim.jsx
src/js/jsx/Search.jsx

This changes the execution of the CC Libraries `placeElement` action to be considered "asynchronous" by the adapter, which allows CEF to continue to run while the command is being played, even while in the smart-object placement tracker. A side effect of playing commands in this state is that they can generate additional events, and so it was also necessary to convert the `placeEvent` handler into an action which calmly, safely declines to add layers to the model which have already been added. It also seems to be necessary to explicitly set the required key propagation policies when playing `placeElement` asynchronously.
This fully addresses #2177, and also removes a few `Promise.delay` superhacks that only worked if you were sufficiently lucky.

Place CC Libraries graphic assets asynchronously

---

src/js/jsx/sections/style/Type.jsx
src/js/stores/font.js

Because we were setting `state.typefaces` in the shouldComponentUpdate of Type.jsx, if the two postScriptMaps between two instances of a Type.jsx were equal, we wouldn't recompute the new state.typefaces, and it would be passed `undefined` into the Typeface datalist, causing #2295, not rendering the Dialog.
Now we calculate the typefaces in the font store, this is not ideal, as they're very UI specific... but at the same time this is the sanest way of doing this.
@iwehrman Since we chatted about this, please review the fix.

Move typefaces for Datalist calculation to the font store

---

src/js/actions/export.js
src/js/jsx/sections/export/ExportList.jsx
src/js/jsx/sections/export/ExportPanel.jsx
src/js/models/layerstructure.js
src/nls/root/strings.json

- Only show and operate on "supported" subset of selected layers
- Currently unsupported: background layers, empty artboards, empty groups, zero-bound layers
- If layers are selected, but none are supported, a message is shown
- If layers are selected, but there are no common assets, a message is shown
- Uses @placegraphichere 's Panel Message pattern
- Includes some minor react housekeeping
- Review note: Added new function `filterExportable` to `layerstructure` (instead of documentExport) so that it would have easy access to `isEmptyGroup`
This addressees part of #2273
(A separate plugin change will make the error message better when we DO request export of layers that generator pukes on)

Export panel and its operations should filter out unsupported layers

---

src/js/actions/ui.js

On Windows, zoom animations act weird and zoom the doc out to the window center. On Mac, animations don't really work anyways... so I've decided to turn them off by us.
Addresses Win side of #2169

Disable zoom animations

---

src/js/actions/documents.js
src/js/actions/export.js
src/js/actions/libraries.js
src/js/actions/superselect.js
src/js/events.js
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/jsx/sections/libraries/assets/Graphic.jsx
src/js/models/layer.js
src/js/stores/library.js
src/js/stores/preferences.js
src/js/util/exportservice.js

**require changes from the adapter and generator-space plugin, see bottom for setting up generator-space plugin**
This PR implements open-for-edit for graphic assets. You can double click on graphic asset's thumbnail to open the asset for editing. Some notes:
* currently it only supports edit PSD file. The other file types require features that are not supported in DS yet.
* switching back to standard PS will break the upload-after-save feature, but switch from standard PS to DS will maintain the functionality.
* Close document will delete the temp files.
It also fix #1408 Closing Library Linked Smart Object blinks zero-doc state.
@volfied please review. 
@mcilroyc I made the change to import the file system commands, so could you review this PR?
```
Run latest PS dev build (> 594)
```
or …

CC Libraries - support open-for-edit for graphic assets.

---

src/js/models/layerstructure.js
src/js/stores/document.js

I messed up during singularizing strokes and fills and removed these necessary methods and wired them to the wrong store handler. This undoes the damage.
Addresses #2207

Re-add addStroke and wire it correctly to stroke being added

---

src/js/jsx/shared/Select.jsx

If key we're looking for was at index 0, the binary search algorithm would fail. 
Causing index to become -1, and reset to the first item, which would cause the bounces in #2405 and #2391

Fix binary search in Select edge case for index 0

---

src/js/jsx/sections/style/Stroke.jsx
src/js/jsx/shared/ColorInput.jsx
src/js/jsx/shared/ColorPicker.jsx
src/js/jsx/shared/NumberInput.jsx
src/style/shared/color-input.less

- Moved coalescing functionality into color picker
- Add focus state highlight to color picker swatch so when it's tabbed to, it's highlighted, and toggles dialog with Enter/Esc
- On dialog open, focus on the ColorInput, and tab becomes locked into the color picker dialog. Tab on Opacity input goes to Color input, and shift tab on color input goes to opacity input.
- Fix a stroke issue #2382

Color Picker grabbag

---

src/js/actions/documents.js
src/js/actions/menu.js
src/js/actions/ui.js
src/js/jsx/DocumentHeader.jsx
src/js/jsx/IconBar.jsx
src/js/jsx/Main.jsx
src/js/jsx/PanelSet.jsx
src/js/jsx/Toolbar.jsx
src/js/jsx/tools/PolicyOverlay.jsx
src/js/stores/document.js
src/js/stores/ui.js
src/static/menu-actions.json
src/style/panel.less

1. Do not manually reposition documents on first selection. Instead, either leave the documents where they already are, or let Photoshop position the canvas using the overlay offsets.
2. Enable Zoom to Selection and Center Selection for the document when no layers are selected.
Addresses #1999 and #1081.
Note that a document opened in Design Space when there are currently no open documents will be positioned incorrectly because the panel bounds aren't currently updated until _after_ the first document is open. I intend to address that in this PR as well, but it doesn't work yet. So, I'm putting this up for review/testing first (by @placegraphichere) to make sure that, besides the first-doc behavior, this is an improvement.

Don't reposition newly selected documents

---

src/js/actions/libraries.js
src/js/actions/search/libraries.js
src/js/jsx/sections/libraries/Library.jsx
src/js/jsx/sections/libraries/assets/AssetSection.jsx
src/js/jsx/sections/libraries/assets/CharacterStyle.jsx
src/js/jsx/sections/libraries/assets/Color.jsx
src/js/jsx/sections/libraries/assets/ColorTheme.jsx
src/js/jsx/sections/libraries/assets/Graphic.jsx
src/js/jsx/sections/libraries/assets/LayerStyle.jsx
src/nls/root/strings.json
src/style/sections/libraries/libraries-section.less
src/style/shared/colors.less

This PR resolved the following issues:
Now you click single click on title to toggle the asset buttons. Note that single click on title will have a delay before showing the buttons, as we have to wait and make sure the single click is not triggered by a double click event (https://github.com/adobe-photoshop/spaces-design/compare/shao/libraries-fixes?diff=unified&expand=1&name=shao%2Flibraries-fixes#diff-9c5b0e09defc4119032323e45a76eab1R128). 
The clickable area for toggling the buttons is also expanded for easier control. 
This is caused by the out dated history state because applying text / layer style does not emit new history event. I added the `historyStateInfo` and it is working fine. @mcilroyc can you help me confirm this is the right solution?
Improved the UI to highlight the new …

CC Libraries - bug fixes

---

src/style/main.less
src/style/shared/color-picker.less

For some reason the retina UI sizes are all a little bigger than non-retina UI sizes, which doesn't make any sense. They all also feel a little too big to me. This reduces the sizes across the board on retina. I think it feels better on a big 5k iMac and on a 15" MBP. If anybody can test on smaller retina devices, that would be helpful.
Before:
After:

Reduce UI size on retina displays

---

src/js/jsx/shared/ColorInput.jsx
src/js/jsx/shared/ColorPicker.jsx
src/style/shared/color-picker.less

I was mistakenly passing the swatch overlay of ColorInput to the colortype thumbnail... but we should just render the pure color instead.
Addresses #2416

Render the same thumb overlay for all color pickers

---

src/js/models/layerstructure.js

This seems to be a workaround for a caching bug, but seems safe.  When a document that contains groups is loaded, the group layers have a bounds object (albeit empty).  When you *create* a group, the bounds are null.  This seems wrong. Regardless, removing the test for bounds existence, and simply testing for childBounds existence and non-emptiness seems to be a sufficient workaround.
Note that I tried testing just for childBounds emptiness, but when creating a group out of an empty layer (edge case) even the childBounds is null.
Second attempt at fixing #2376

Exportability: do not validate existence of bounds, only of childBounds

---

src/js/jsx/DocumentHeader.jsx
src/js/jsx/Toolbar.jsx
src/style/document-header.less
src/style/toolbar.less

This makes the document header visible in both the doc and no-doc states to reduce UI flashing when going back and forth between those states. I also think it looks less weird, given that the toolbar is also enabled in the no-doc state.
There's no technical reason for this change. I just think it looks nicer. Over to @placegraphichere to decide whether he agrees or not.

Show the document header in the no-doc state

---

src/js/actions/ui.js

With #2343, we no longer zoom the document on startup. But that means that we also don't get a `scroll` event from Photoshop to initialize our window transform. This makes it impossible to select objects on the canvas until the first scroll event (e.g., when panning the document). This fixes the problem by explicitly setting the transform in `ui.afterStartup`. It has to be _after_ startup because `ui.updateTransform` short circuits if there is no active document.
Addresses: my complaints in Slack.
Thanks to @jsbache for helping me narrow down the issue!

Initialize the window transform on startup

---

src/js/jsx/Guard.jsx

It looks like the cursor doesn't automatically reset itself when changed until the after mouse moves next. The `Guard` component frequently changes the cursor when the UI is disabled, but it can get stick around in the disabled state for an unwelcome amount of time if you're not moving the mouse. This fixes the problem by calling `os.resetCursor` when the `Guard` switches between enabled and disabled states.

Reset cursor when updating Guard

---

src/style/search/search-bar.less
src/style/shared/color-picker.less
src/style/shared/dialog.less

bug ref #2422 
- increased font size
- alignment for color input value
- spacing around swatches, maps and sliders
- spacing for RGB/HSB
- dialog border-radius tweak
- dialog arrow tweak for retina
- added box-shadow on color sliders/maps to reduce white glow on corners
- start of map pointer fitting on the edges of slider better
- removed some old MQ settings
- removed some math, and unnec css
- Note: this does not fix the color slider min-max range issues

color picker tweaks

---

src/js/jsx/sections/export/ExportList.jsx
src/js/jsx/sections/export/ExportPanel.jsx
src/js/jsx/sections/style/AppearancePanel.jsx
src/js/jsx/sections/style/VectorAppearance.jsx
src/js/jsx/sections/style/VectorFill.jsx
src/js/jsx/sections/transform/TransformPanel.jsx
src/js/jsx/shared/SplitButton.jsx
src/style/main.less
src/style/sections/exports/exports.less
src/style/shared/drop-down.less

With reference to the designs here: https://trello.com/c/KR5wYVkW/494-design
This has been reviewed once by @designedbyscience in the Review Only PR #2341 
- I used the new stylings written for `.formline` and `.formline__space-between` to have the elements span the entire width of the Export Panel, as the designs show. 
- In order to have the formlines span the entire width of the Export Panel, I had to take away some of the modularity that `containerContents` provided so that an extra div would not be inserted. Then I could have dictate that the width of the `<ExportList>` will span the container. 
- Took out <Gutter> components in `ExportList.jsx` and `ExportPanel.jsx`
- Made every element of the formline have an underline 
- Changed the font size of the `TextInput` to match the font …

Export Panel UI updates

---

src/js/jsx/sections/export/ExportAllPanel.jsx
src/js/jsx/sections/export/ExportPanel.jsx

@designedbyscience says he understands why this fix works.  So I guess I'll assign it to him.  I think this is risk-free enough to make it in to the MAX build.

Export 'loader' icon should be animated

---

src/js/actions/libraries.js
src/js/actions/search/libraries.js
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/Library.jsx
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/jsx/sections/libraries/assets/AssetSection.jsx
src/js/jsx/sections/libraries/assets/CharacterStyle.jsx
src/js/jsx/sections/libraries/assets/Color.jsx
src/js/jsx/sections/libraries/assets/ColorTheme.jsx
src/js/jsx/sections/libraries/assets/Graphic.jsx
src/js/jsx/sections/libraries/assets/LayerStyle.jsx
src/js/jsx/sections/style/Type.jsx
src/js/stores/library.js

This PR includes the following fixes / improvements:
1. make applying non-RGB color asset works
2. Mouse over character style title will show font info, instead of display name. This allow users to check the font name and style, when they overwrite the default display name.
3. Mouse over graphic asset will show `display name` + `file extension`
4. Add new graphic asset will reveal the new graphic asset by scrolling to top of the graphic list automatically.
5. show only editable graphics in search result when there is no document. Fix for #2211
6. Resolved warning in Type: ```Failed propType: Invalid prop `value` of type `boolean` supplied to `Datalist`, expected `string`. Check the render method of `Type`.```

CC Libraries - bug fixes and improvements

---

src/js/jsx/shared/ColorPicker.jsx

If you type color name, until you change color/alpha it should stay that name. If you type HSV(...) it should be shown in HSV format.
Addresses #2421

Preserve color format in color picker lifetime

---

src/js/jsx/tools/SuperselectOverlay.jsx

Addresses #2456, it must have been a timing issue where the OS.mouseMoveHandler got a layer ID from PS that's not in our models.

Add a null check for layer highlighting

---

src/js/actions/guides.js

This was causing issues where an error would put us in a constant loop of resets, because we forgot to nullify the guide policy ID between failures.

Reset guide policy ID on reset

---

src/js/jsx/shared/ColorInput.jsx

The swatch that is part of `ColorInput` components needs to be able to take focus so that the color picker can be part of the focus change. But, currently, the color swatch does not correctly implement focus management between CEF and PS. In particular, if the swatch has focus, it isn't easy to release focus back to PS, and when in this state none of the keyboard shortcuts will work. This is a short-term workaround for the issue which temporarily removes the ability for the color swatch to take focus. After the MAX deadline, we'll reinstate this and also implement correct swatch focus management.

Disable focus on color swatches temporarily

---

src/js/actions/search/libraries.js
src/js/jsx/sections/libraries/assets/CharacterStyle.jsx
src/js/models/library_sync_status.js
src/js/stores/library.js

Thanks to @chadrolfs's screenshot, this PR fix #2271 by handling undefined progress attr in new library's sync data. Also improved the log format for easier debugging.

CC Libraries - fix infinite syncing icon

---

src/js/actions/guides.js

Depends on https://github.com/adobe-photoshop/spaces-adapter/pull/148 to work fully. Basically, PS code changed so when we're creating artboard guides, we gotta make up for the relative positioning PS does for our window to canvas transforms. 
Will address #2461

For artboard guides, change position to relative mouse location

---

src/style/sections/exports/exports.less

@designedbyscience Suggested this tweak to the Exports Panel 
Before:
After:

Spaced out buttons in the exports panel header

---

src/js/actions/documents.js
src/js/actions/layers.js
src/js/models/layer.js
src/js/models/layerstructure.js
src/js/stores/document.js

This PR delays requests for "inessential" properties on layer descriptors until layers are first selected. This is designed to improve startup performance by reducing the amount of information fetched from Photoshop. On VermilonArtboards.psd, for example, startup time is reduced by about 25% (from 7.1s to 5.3s).
This change is accomplished first by splitting off from the `_optionalLayerProperties` array in `actions.layers` another array, `_lazyLayerProperties`. When a document is initialized with `layers._getLayersForDocument`, the (remaining) optional properties are fetched for all layers, while the lazy properties are only fetched for the selected layers. Layer models for which the full suite of properties have not been fetched have their `initialized` property set to false until fully …

Delay loading inessential layer properties

---

src/js/jsx/sections/export/ExportList.jsx

These changes to the inputs were accidentally overwritten by a recent commit.  @placegraphichere this should fix the suffix input disabled issue you mentioned.  It also restores the ability to tab through the inputs without making changes.

Fixed export panel input configurations - fixing a recent regression

---

src/js/jsx/PanelColumn.jsx
src/js/jsx/PanelSet.jsx
src/js/jsx/sections/export/ExportPanel.jsx
src/js/jsx/sections/layers/LayersPanel.jsx
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/nodoc/ArtboardPresets.jsx
src/js/jsx/sections/nodoc/RecentFiles.jsx
src/js/jsx/sections/style/AppearancePanel.jsx
src/js/jsx/sections/style/EffectsPanel.jsx
src/js/jsx/sections/transform/TransformPanel.jsx
src/js/jsx/shared/Datalist.jsx
src/style/panel.less

Currently each document has its own panel set in the DOM, which is reasonable as documents have different attributes and state. However, this cause problems to the library panel as switching between document should maintain the same state (scroll position, selected asset, dialog, etc.). The problem is originally reported in #2312. This PR changed the behavior by rendering only one libraries panel for all documents, and still keep separate copy of other panels. 
(Note that I tried and it is not working by creating a top level libraries panel instance and pass it as a prop to the panel set, because the instance will have different component key (final key = parent keys + component key) when rendered and will result in DOM replacement.)
This PR also addressed #2430 by adding the onBlur …

Render one libraries panel for all documents to maintain consistent state

---

src/js/models/paragraphstyle.js

This relaxes an overly strict check in the `ParagraphStyle` construction function that would throw if it found a justification value it didn't understand. As it turns out, there are more valid justification values than those previously checked for! Namely, `justifyLeft`, `justifyCenter` and `justifyRight`. This just lets anything pass through into the model as long as it's not falsey.
Addresses #2375. Instructions for testing are in that issue.

Allow all text justification values 

---

src/js/jsx/mixin/Focusable.js

This removes one of @iwehrman's change from couple days ago for #2454 because we need those policies to be installed at all times. 
We also had a dormant bug where we were calling `removeKeyboardPolicies` with an undefined `commit` variable, so they were never being sent to PS to be removed.
Here is the scenario where this bug shows:
1 - Create shape layer
2 - Switch to super select tool
3 - Use arrow keys to nudge layer
4 - Click one of the transform inputs
5 - Use arrow keys to change that value
6 - Press escape / click outside to lose focus
7 - Use arrow keys again - at this point, arrow keys no longer work until we switch back and forth to superselect tool
As far as Ian's change of installing policies only in modal state goes... We need the never_prop policies for arrow keys because …

Always install arrow policies for focusable, and remove them correctly

---

src/style/shared/button.less

This is my "best attempt" at styling the unchecked state of checkboxes to match the spectrum standards.  
This is either:
1. "good enough"
1. Needs a ninja like @designedbyscience to carry it forward with CSS tweaks
1. Needs some SVG magic instead of a pure CSS treatment, since my current belief is that the minor alignment issues are not solvable with CSS hackery.
cc: @davealonzo @placegraphichere @DivyaPrabhakar

Unchecked checkboxes should be 'transparent' with a grey border

---

src/js/actions/documents.js
src/js/actions/layers.js
src/js/jsx/sections/style/LayerBlendMode.jsx
src/js/jsx/sections/style/Opacity.jsx
src/style/shared/number-input.less

@volfied pointed out this morning that he was unable to load a picture of his puppy dog. This was due to my recent change in #2439 to `layers._getLayersForDoc` handling layer indexing incorrectly for documents with background layers. In my defense, the way Photoshop does this is completely :banana: :banana:.
CC @mcilroyc since you reviewed #2439 and CC @volfied because it was your puppy.

Fix error loading documents with a background layer

---

src/js/jsx/sections/style/Stroke.jsx

If we had an image coming from PS, where stroke was set to empty color (red line crossing white square), we would get "null" as the color, and downsample would accept that as mixed. Instead, we consider those layers (where stroke is null) to be default color.
Reason for this is: if any property of stroke other than color is set (or the eye icon is clicked to enable stroke), it'll start with the default color anyways, so this removes the ambiguity of the mixed stroke for no-stroke layers.
Addresses #2207

When stroke is in empty color state, initialize it at default color

---

src/js/jsx/shared/ColorInput.jsx

This factors out a `ColorSwatch` component from the `ColorInput` component and makes it a `Focusable component. Once you focus the swatch by tabbing to it, you can hit enter to open the color picker. After the picker closes, the swatch regains focus. From there, you can keep tabbing or hit escape to return focus to PS. 
It's possible, though perhaps not likely, that this addresses #2490.

Focusable color swatch

---

src/js/actions/policy.js
src/js/tools/type.js

fix for type tool with Jespers change to keyboard policies on the plugin

remove policies while in a text modal state

---

src/js/actions/tools.js

Always propagate sends all mouse clicks to PS, and this causes an issue when the resize border is below the panels.
Addresses #2354

Use alpha propagate instead of always for border policies

---

src/js/fluxcontroller.js

What it says! This should prevent some unrecoverable errors in which actions failed as a result of being in a modal tool state. Also addresses #2267, but standard PS is now better about preventing switching to DS from modal states.

End modal tool states before startup and reset

---

src/js/actions/documents.js

We used to just skip calling addLayers, but this caused problems like #2484.
I tested this with couple places/drags, and it seems to work fine, and not break other place events.

On place events, replace if layer already exists

---

src/js/actions/ui.js

Problem was, with tiny layers, we'd get a zoom factor much bigger than our allowed zoom, and this would break bounds calculation. Now we limit the zoom factor to [0.05, 32], even when it's fit selection.
Addresses #2526

Fix the zoom level within the valid increments during panZoom

---

src/js/actions/libraries.js

Will require https://github.com/adobe-photoshop/spaces-adapter/pull/149, and CL 1043494 to work.
Addresses #2414 
All other open operations will still add file to MRU list

Disable MRU add for library opened files

---

src/js/actions/export.js
src/js/jsx/sections/export/ExportAllPanel.jsx
src/js/stores/export.js
src/nls/root/strings.json

This fixes a pretty brain-dead mistake in the way artboard prefixes were being derived.  Now, in the react render() method after sorting artboards, a map of layer>prefix is created (if necessary).  That map is provided to the "export all" action.  This maintains consistency of prefixes across the UI, and the actual export process.... but the prefixes are still transient (not persisted to PS metadata, nor maintained in our store which would require a lot more overhead of trying to keep up with AB positions on canvas).  Addresses #2473
bonus: Also add the "Use Prefix" label as a translatable string

Better artboard export prefix handling

---

src/js/actions/documents.js
src/js/actions/libraries.js
src/js/events.js
src/js/stores/library.js

If user click the save button in the close-document model dialog, we are not going to receive a save event for the document, and this cause lost changes when editing a graphic asset. This PR check if the document is saved when closed, and trigger the update-graphic-asset event to properly save the changes.
#2495

CC Libraries - handle update graphic asset for the close-document model dialog.

---

src/js/actions/search/libraries.js
src/js/jsx/sections/libraries/assets/AssetSection.jsx
src/js/jsx/sections/libraries/assets/CharacterStyle.jsx
src/js/util/libraries.js
src/nls/root/strings.json

This PR displays leading and tracking of character styles in the libraries panel, and fix their title in the search result. It also extracts the code of formatting character style into `util/libraries` to avoid duplicates in search and libraries panel, and make them less error prone..

CC Libraries - improve character style titles in the panel and search result

---

src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/sections/style/Type.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Select.jsx
src/js/jsx/shared/TextInput.jsx

1. Ensure that tabbing away from a focused `Datalist` does not open the `Datalist`. Once a `Datalist` is focused, start typing, or use the up/down arrows to open the `Datalist`.
2. Ensure that changing the blend mode updates the `Datalist` in `Type` component.
3. Ensure that the selections can be made in the `LibraryList` `Datalist` can be made either by pressing enter or or clicking to commit.
4. Ensure that tabbing away from the `LibraryList` `Datalist` releases focus back to PS completely. This is the last focusable element in the UI, and otherwise the app ends up in an indeterminate focus state which causes problems with shortcuts, etc.
Remaining known issues:
1. Committing a `Datalist` selection with enter should leave the `Datalist` focused, but it doesn't.
2. Shift-tabbing away …

Various Datalist event handling fixes

---

src/js/models/layerstructure.js

In #2434 I observed that selection of layer ranges with many ancestors was very slow. A quick profiler run showed that almost all of the time was being spent in the `Flip` component's `componentWillReceiveProps` method, and in particular that method's call to `LayerStructure.prototype.selectedNormalized`. That method has an `O(m^2*n)` algorithm, for `n` layers and `m` selected layers, where an `O(m*log(m)*n)` algorithm suffices. Making this small change improves performance significantly.
However, I found it mysterious that this should be the case, since in #2434 `m` is should be very small. It turns out that there is a _different_ bug wherein PS is interpreting range selection to include all descendants, even hidden ones, in the range. This seems wrong to me, but it does explain why the …

Speed up layers.selectedNormalized

---

src/js/jsx/DocumentHeader.jsx
src/nls/root/strings.json
src/style/document-header.less

Adds an "open export dialog" to the document header 
Things to note: 
1.) Despite some of the comps regarding the UI (example: https://trello.com/c/zD4DGHqz/452-epic-ui-overhaul), I was told to only insert "open export dialog" icon for the time being. 
2.) @designedbyscience and I talked about the DOM structure and he said it is best to keep the new class .generator-header as a sibling to .document-header for CSS stability. 
This is what the UI looks currently:

Global export button added to document header

---

src/js/stores/dialog.js

This addresses #2400.
Because the dialog state is a nested map, it must be merged deeply.  Otherwise, an undefined dismissalPolicy blows away the previous policy instead of the desired behavior of leaving it untouched.
Note that dragging files onto the PS icon (to open as a new document) seems to also suffer from some weird issues, especially if layers are selected?  Anyway, when it works, then this change addresses 2400.

Properly merge dismissal policy during dialog open of previously registered dialog

---

src/js/actions/documents.js
src/js/actions/export.js
src/js/jsx/sections/export/ExportAllPanel.jsx

This addresses #2521 by adding a default asset during new doc creation (w/ artboard).
Furthermore, to make artboard export more convenient, especially for docs created in standard PS:
- Export All panel shows artboards even if they have no assets configured
- "Checking" an artboard that has no assets (including the "All artboards" mass checkbox at the top) will auto-add a 1x asset where needed.

Add default asset to artboards on new doc creation, and other artboard export conveniences

---

src/js/tools/pen.js

This is a tool setting I realized is default on in PS, but not in DS, which was causing #1681 
So we now turn this feature on, and using pen tool, when you switch to a closed path/shape and try using it again, pen tool automatically starts a new layer as it should.
Addresses #1681

Turn on auto add/delete for pen tool

---

src/js/jsx/DocumentHeader.jsx
src/js/jsx/IconBar.jsx
src/js/jsx/PanelSet.jsx
src/js/jsx/Toolbar.jsx
src/js/jsx/tools/GuidesOverlay.jsx

We currently call `ui.updatePanelSizes` when we receive a `displayConfigurationChanged` event from the adapter, but this may arrive before the browser has redrawn the UI with the new UI sizes. This changes the panels to call debounced helper function to update the panel sizes only after 500ms have passed without a new `displayConfigurationChanged` event.
With this change, it's possible to have drag the Design Space application window from one display to another and have the on-canvas UI (e.g., guides overlays) continue to work correctly.

Update panel sizes on display configuration change

---

src/js/jsx/Search.jsx

Addresses #2580, while keeping @mcilroyc's change. Problem was, `dismissOnDialogOpen` is true by default, and search dialog has a sub dialog, which mcilroy's recent fix caused this buggy behavior to show.
@iwehrman please review since it's urgent.

Turn off dismissOnDialogOpen for search dialog as it has a sub dialog

---

src/js/actions/ui.js
src/js/jsx/Zoom.jsx
src/js/jsx/shared/NumberInput.jsx

Addresses #2592 
On NumberInput, if step is provided as 0, we disable stepping. Default is 1, so this shouldn't affect other NumberInputs.
Also, set the min/max of Zoom UI to 5,3200 so it is within the acceptable realm of zoom values, and disabled stepping for it.

Disable stepping on 0 step for number input, and limit zoom UI

---

src/js/jsx/Scrim.jsx
src/js/jsx/sections/style/AppearancePanel.jsx
src/js/jsx/sections/style/EffectsPanel.jsx
src/static/menu-actions.json
src/style/shared/icons.less

This PR disabled the following features for unsupported document:
* guide creation
* copy/paste appearance/style buttons
* add effect button
* menu item: export
* menu item: search
Some files for testing unsupported document:
1 CMYK mode https://www.dropbox.com/s/z0u5nldb9fcu8aq/cmyk.psd?dl=0
2 3d https://www.dropbox.com/s/uzm4n8y6k2av5zb/3d.psd?dl=0
Related to issue #2545

Handle unsupported document by disabling more features

---

src/js/actions/ui.js

Addresses #2600.
Just emitting change in _handlePanelResized was not enough, as the zoom change wasn't being accounted for by the panel resizing. @iwehrman please review.

Update transform after updating panel sizes

---

src/js/stores/ui.js

Do not reset panel boundaries after a controller reset because:
1. The panel boundaries shouldn't have changed anyway; and
2. We don't yet have any good way to tell the individual panel components that they should reset their sizes when the controller resets.
Ideally we would have some kind of event that the components could easily listen to which would cause them to reset their sizes. And probably there should be a more general mixin for panels that contribute to the panel boundaries. But, for now, this super hack is sufficient to address #2593:

Preserve overlay offsets on reset

---

src/js/actions/superselect.js
src/js/actions/transform.js

JP moved duplicateNewSheets events into the "move" events, so they always come to us in right order.
Addresses #2510. Requries pgdv 668 or later.

Move duplicateNewSheets handler into the move event handler

---

src/js/models/layerstructure.js

This addresses #2504.  @shaoshing passed this to me because he was assuming I remembered the purpose of the second conjunct at line 891.  Alas, I do not.  Removing it fixes the issue (as he suggested) and seems to work correctly for other code paths:
1. dragging a file on to the PS icon
1. new shape layers
1. new text layers
I'd love for someone besides @shaoshing to look at this to double check both of our work.

Relaxed the condition for isNewSelected in layerstructure's addLayers

---

src/js/jsx/tools/SuperselectOverlay.jsx

It was causing highlights to blink as it removed all highlights if marquee was on. Addresses #2594

Don't update mouse over highlights while in marquee state

---

src/js/actions/libraries.js
src/js/fluxcontroller.js
src/js/stores/library.js

This PR fixed the `deleteGraphicTempFiles` transfer due to a typo in my previous PR. It also fixed a possible circular dependency issue when resolving action dependencies, by checking the dependency stack. 
Resolved issues: #2548 #2565

CC Libraries: resolve issues related to graphic editing.

---

src/js/actions/export.js
src/js/actions/policy.js
src/js/actions/preferences.js
src/js/actions/tools.js
src/js/actions/type.js
src/js/actions/ui.js
src/js/events.js
src/js/models/eventpolicyset.js
src/js/stores/policy.js

1. Convert `disablePolicies` and `reenablePolicies` to `suspendPolicies` and `restorePolicies`, allowing policy actions to be added during the suspended state. This currently does not allow you to remove a policy during the suspended state that was added before the suspended state. This also doesn't allow you to suspect policies twice without restoring them in the middle. The former feature could be added if necessary.
2. Suspend policies while in the type modal tool state.
3. Fix a bug in which clicking a never-before-selected layer with the type tool would fail as a result of the `updateTextProperties` event being handled before the selection change, and hence before initialization.

Suspend policies during modal tool states

---

src/js/actions/search.js
src/js/jsx/Search.jsx
src/js/locks.js
src/js/models/menubar.js
src/js/stores/search.js
src/static/menu-actions.json

1. Register search providers in `search.beforeStartup` instead of in `Search`'s `componentWillMount` method so that search providers are re-registered after a controller reset.
2. Ensure that the search command is enabled either if there is no open document or if there is a supported document open.
Addresses #2505 and #1888.
@shaoshing: 2) above tweaks your recent unsupported document change in 1e52903c3095d859496750784ecaa926fc8b42d6.

Fix search after reset

---

src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/style/sections/libraries/libraries-section.less
src/style/sections/style/style-section.less

Before, the panel content for Libraries was removed if the library was collapsed, now it is just hidden with CSS (same as the other panels).

Change Libraries panel to hide on collapse with CSS

---

src/js/fluxcontroller.js

This effectively unblocks menu commands and shortcut commands from running before `afterStartup` is complete. It's possible there was some good reason for delaying this state change until after `afterStartup`, but I can't currently see what it might be.
The moral of the story is that, from now on, if the app requires some initialization to run without error, it should go in `beforeStartup`. If it's able to run without the initialization then it can go in `afterStartup`.
Addresses #2272.

Mark the controller active after beforeStartup instead of after afterStartup

---

src/js/jsx/PanelSet.jsx

This changes the initial render of `PanelSet` to draw the icon bar and a single empty column instead of nothing to improve the experience of the initial UI load. It's not perfect, but I think it's better.

Render icon bar and empty column on startup

---

src/js/actions/shapes.js
src/js/jsx/sections/style/Fill.jsx
src/js/jsx/sections/style/Stroke.jsx

This will address #2570, but more importantly, fix toggling of strokes/fills so they behave correctly.
- Change `setFillEnabled` and `setStrokeEnabled` to pass in a `null` value for color.
- If color being passed to `setFillColor` and `setStrokeColor` is null, and color is being enabled, we will use the last known fill/stroke colors from the layer models for each layer itself, using default fill/stroke color as fallback. This allows us to disable/enable strokes/fills of multiple layers without overwriting/losing values.
@ktaki please test this on the branch, this is a big change and I want to make sure I'm not introducing new bugs.
@mcilroyc your expertise with layerActions and fill/stroke would be very appreciated in reviewing.

Re install existing fill/stroke colors on re-enable

---

src/js/jsx/shared/ColorPicker.jsx

ColorPicker keeps the state.color in HSVAColor type, so ColorFields should expect that.
Addresses #2568

Set ColorFields expected color proptype to HSVAColor

---

src/js/jsx/shared/ColorPicker.jsx

Addresses #2551, problem was, we were parsing the Hsv value into rgb, which kept losing the hue when saturation was 0.

Persist the hue value across 0 saturations in color picker

---

src/js/models/historystate.js
src/js/stores/history.js

This should address #2646.
Look you guys, I don't know why this is necessary.  I also do not know when it broke, other than that it was at least several sprints ago, before the major plugin version change.  
Prior to this commit, if I stick a breakpoint at stores/history.js line 444, I could execute that same code in the console.  If I tried to step in to it, it exploded.  I was stumped.  I moved the logic out of that low-value abstraction (as a method of the historystate model) and just did tha business directly in to the history store.  It worked.  Is that obvious to anyone why?

Fix the 'revert' history store handler

---

src/js/actions/type.js

We're currently initializing the font list twice for no reason. The `Type` initiates before each render if it hasn't already been initialized, but `Type` apparently renders twice in succession before the first call is complete. The fix is to just have the `type.initFontList` action itself check to see if the font list has already been initialized and to bail out early if so. This saves a few hundred milliseconds on startup time.

Initialize the font list only it necessary

---

Gruntfile.js
src/js/actions/layers.js
src/js/actions/superselect.js
src/js/actions/transform.js
src/js/jsx/sections/transform/Position.jsx
src/js/models/bounds.js
src/js/models/layerstructure.js

Will address #2613, and show layer position in relation to it's owner artboard.
- Added `Bounds.prototype.relativeTo` method which returns a new bounds object with updated position in relation to the given bounds object.
- Added `relativeChildBounds` cached property that calculates the bounds of a layer relative to it's owner artboard.
- Added `selectedRelativeChildBounds` cached property that grabs all the selected layer's relativeChildBounds.
- Add `relative` flag to `actions.transform.setPosition` to use relative child bounds during transform calculations, subsequently added it to `_getMoveLayerActions` as well.

Add relativeChildBounds, and use it for position inputs

---

src/js/jsx/sections/export/ExportAllPanel.jsx
src/style/sections/exports/exports.less

Any overflow of assets in the export dialog is hidden and ends in an ellipsis instead of truncating. 
Minor CSS change, addresses #2557.

Assets in the export dialog end in ellipsis instead of truncation

---

src/js/actions/libraries.js
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/Library.jsx
src/js/stores/library.js
src/style/sections/libraries/libraries-section.less

1 can edit large document format (PSB, here is a sample asset for testing purpose http://adobe.ly/1LAQoVB)
2 handle error when double-click smart object while its associated element is deleted. (#2615)
3 automatically scroll to the last locally updated graphic asset in the libraries panel.
4 match asset rename input style with the layers panel. (#2621)

Various improvements for the libraries panel

---

src/js/actions/layers.js
src/js/jsx/sections/layers/LayerFace.jsx
src/js/models/layerstructure.js
src/js/stores/document.js

The changes `layers.select` to be fully optimistic: the complete selection post-state is calculated up front in JavaScript, and the layer model is updated in parallel with the Photoshop play command instead of in sequence. Previously we only did this when no modifier was used. Even if Photoshop worked correctly this would be somewhat faster, but as is there is also a terrible bug in which the `addUpTo` modifier does not take the visibility (w.r.t. expanded/collapsed ancestors) of layers into account, such that selecting a range of collapsed groups would also select all of their descendants.
Note that the specification of `addUpTo` requires the notion of a "pivot" element, which represents the starting point of a range selection. This is tracked in `LayerStructure.prototype.pivotID` the …

Fully optimistic layer selection

---

src/js/actions/documents.js
src/js/actions/search.js
src/js/models/document.js
src/js/stores/document.js

This PR is in the same spirit as #2439, which delayed loading detailed information about layers until their first selection, but for documents. It changes `documents.initInactiveDocuments` to only load a small subset of essential document properties during startup, and `documents.selectDocument` to finish loading all of the properties when the document is first selected. It does _not_ change `initActiveDocument` or `updateDocument` or anything else that might initialize a new document after startup. An uninitialized document is detected simply by having a null `layers` property.
With 7 moderately sized documents open, this reduces overall startup time from ~6.5 seconds to ~4.5 seconds, which is a ~30% reduction.
Although #2439 was a fairly simple architectural change, this is even …

Lazy document initialization

---

src/js/actions/export.js
src/js/models/documentexports.js
src/js/models/layer.js

This was really the practical use of this method anyway, which allowed some cleanup.
Addresses #2641.  In some cases, new layers did not have layer-level exports defined properly in the `ExportDocuments` model.
This PR also tries harder to safely default artboards to "exportEnabled" and having one default asset.  When opening a document that has undefined export-related `extension` values, we assume this is a fresh document (never opened in DS, or at least the exports were not monkeyed with), so we default the values accordingly.  This is a request by @davealonzo.

DocumentExports.getLayerExports will always return an Immutable List

---

src/style/panel.less

- When lots of effects are added, export panel will not get shoved down and become unusable.
- fix for #2585 
- also #2468

Export panel maintains minimum height

---

src/js/actions/tools.js
src/js/actions/transform.js

This change requires CL 1044998, which will be available in pgdv.mac.688
Problem was that I was preventing both artboard tool switch AND drag operation from happening when multiple artboard selection border was clicked. So now I only prevent the tool switch in PS side.
But this presented a new problem: We would get two "move" events, where one would have "0,0", and because we were debouncing, we would handle the 0,0 event, and immediately return, eating up the other event. So now, if there are any artboards selected, "move" events all are considered legal.
I also noticed that we would draw one big policy frame all selected artboards... however, if oyu had two artboard selected that were not in a row/column, this would create a fake policy on the empty corners, and PS would still draw the …

Multiple artboards in selection for dragging / policies

---

src/js/jsx/tools/SuperselectOverlay.jsx

I recently switched the border policies to alpha propagate instead of always_propagate to prevent mouse stealing over our own panels. However, this broke one of the highlighting rules, so I fixed it.
There wasn't an issue for this yet.
Noticed this while trying to fix 2515, hence the branch name.

Check for alpha_propagate policies as well for highlighitng

---

src/js/jsx/sections/style/Fill.jsx
src/js/jsx/sections/style/Shadow.jsx
src/js/jsx/shared/ColorInput.jsx
src/style/shared/color-input.less

1) Fix alignment of Effects color swatch, which should have lined up with the Appearance color swatches
2) Correct the stroke swatch, which I had done wrong and @davealonzo nicely pointed out to me (and happily made some of the code cleaner)
3) Attacked that corner radius issue #2564 some more: This issue is largely to blame on Chrome, and can be seen in normal desktop Chrome as well. It seems to have several compounding issues
* Flexbox + z-index create it for any color
* Any color with alpha < 1 also creates it
I had written a hack for the opacity issue previously, which was actually not necessary as I was able to remove the z-index instead. So for opaque colors, it looks good. Anything less than opaque still shows white corners, though it only looks really bad in the range 0.85 < alpha …

Updates to color swatches

---

src/js/actions/layers.js

Just another initialize. RemoveLayers dispatches event, event changes selection, selected layers aren't initialize, so document store doesn't emit a change event. So we have to initialize those layers to get a change event. Boy saves world.
Addresses #2601

Initialize newly selected layers after layer deletion

---

src/js/jsx/PanelSet.jsx

This is more an experiment than anything else, using a PR so we can have a conversation about it.
For the proposed single column mode, there are a lot of ways we could get there...this is one of them. Instead of moving all of the panels into a single column, which has some issues around space (why we moved to two column in the first place), this simply allows the user to quickly switch between Properties and Layers/Libraries. 
Behavior is:
2 columns open: Command Click on either column toggle button closes both panels
2 columns closed: Command Click on either column toggle button open both panels 
1 column open: Command Click on either column toggle button switches the open panel for the closed panel
For your consideration, @placegraphichere

Command Click on Column Toggles has different behavior

---

src/js/actions/ui.js
src/js/jsx/Main.jsx
src/js/jsx/PanelSet.jsx
src/js/jsx/shared/Dialog.jsx
src/js/models/menubar.js
src/nls/root/menu.json
src/static/menu-actions.json
src/static/menu-mac.json
src/static/menu-win.json
src/style/panel.less
src/style/shared/title-header.less

Another small-screen/single column option. Here, there is a menu option for Single Column Mode under the Window menu. 
With this option, all of the panels now appear in a single column, and the toggle panels toolbar disappears. I adjusted some of the sizing of both the panels and the headers in order to fit more on the screen.
Attached is the screen at approximately the resolution of a 13" Macbook Air

Enables a single column mode, where all panels appear in a single column

---

src/js/actions/documents.js
src/js/actions/history.js
src/js/models/layerstructure.js

This addresses #2715 .
This also fixes an unrelated, unreported bug with history states not handling visibility correctly for newly added layers.

Init 'next' doc before closing the first

---

src/style/sections/libraries/libraries-section.less

- Footer matches Ps icon height in right toolbar
- reduce dropdown section height size but maintain gap between dropdown
section and scroll area

Libraries Visual Tweak to header/footer

---

src/js/actions/superselect.js

Layers.select doesn't like it when you pass it "select" as the modifier (even tho that's the default modifier) and multiple layers... Well guess who did that until now? Marquee select.
@mcilroyc please review as this is a FIXNOW bug. #2735

Don't pass a modifier to layers.select through marquee in normal case

---

src/js/actions/libraries.js
src/js/events.js
src/js/stores/library.js
src/js/stores/policy.js

This PR fix the issue that PS is not responding to mouse click in the transform mode after a graphic asset is dopped on the canvas. This is related to #2719 and requires latest Jenkin build (>= 703) to fully work.
Since this is related to the event policy, @mcilroyc can you reivew my PR? Thank you.

Suspend/Restore all policy around the placeEvent of graphic asset.

---

src/js/actions/documents.js

Numero #2715 part dos.   Let `null` document ID pass through (if last doc was just closed), and do NOT query history.

Bug fix in disposeDocument, better handling for final document close

---

src/js/actions/documents.js

fix of #2683 I had wrongly assumed that my fix in documents.select would cover these cases.

fix issue 2683 exit mas mode when opening a new doc

---

src/js/actions/tools.js

fix for #2678 
I'm not sure if the reciprocal is also true, that if you lock a layer we should exit mask mode. maybe @placegraphichere has some thoughts. but in the mean time this is a nice little low risk fix

do not enter mask mode if layer is locked

---

src/js/actions/shapes.js
src/js/models/layerstructure.js

Another artifact from multiple strokes age, where we checked to see if all layers had strokes and if not, we called _refreshStrokes. Problem was, with transactions, we wouldn't play the actual setStroke objects yet, so we'd be trying to grab a non existent stroke from PS, and things would burn.
I removed the check, and need to call _refreshStrokes, because we can recreate the stroke ourselves using available strokeProperties.
Addresses #2699

Add stroke to layers without a stroke object during setStroke command

---

src/js/jsx/sections/style/EffectsPanel.jsx
src/js/jsx/sections/style/ShadowList.jsx
src/style/panel.less

This PR restricts the maximum number (10) of layer effects user can create. If reach maximum number, the coresponding menu item will be greyed out. for #2729
For you convenience, you can import this layer effect (http://adobe.ly/1jDyVku) to your cc library to quickly populate these effects.

Restricts the maximum number of layer effects user can create

---

src/nls/root/strings.json

capitalize GitHub name correctly in strings. 
#2742

capitalize name correctly

---

src/js/jsx/IconBar.jsx
src/js/jsx/PanelSet.jsx
src/js/stores/ui.js

This is a very narrow fix for #2731, in which toggling single-column mode fails to update the UI borders (i.e., the overlay offsets and cloaking rectangle).
After the next release, the border/panel/column management really needs some cleanup and additional structure... (CC @shaoshing, who may care to think about this during his quiet moments.)

Reset UI borders when toggling single-column mode

---

src/js/actions/documents.js
src/js/actions/layers.js
src/js/actions/tools.js

1. Call `resetBorderPolicies` after `resetLayers` because bounds may have changed.
2. Call `resetBorderPolicies` at the _end_ of `disposeDocument` to avoid an atomicity violation due to lack of concurrency control among non-sequential invocations of `this.transfer`. This is a SuperHack :tm:.
The latter bug is quite nasty. I realized that it existed in theory a few weeks ago, but I verified that it's causing the second problem above. In particular: `disposeDocument` transfers `resetBorderPolicies` and another action which itself transfers to `resetBorderPolicies`, but does not serialize the two transfers. The executions of the two instances of `resetBorderPolicies` interleave in a _very bad way_. This is exactly the sort of concurrency controller that the controller should be providing for …

Misc border policy fixes

---

src/js/actions/documents.js

This delays `updateDocument` from resolving until after its call to `resetBorderPolicies` finishes. Note that it is **NEVER** OK to call `transfer` without blocking on the promise that is returned!
Along with #2790, I hypothesize that this is a very narrow fix for #2224. (@ktaki is verifying this now.)

updateDocument should block on resetBorderPolicies

---

src/js/actions/layers.js
src/js/events.js
src/js/models/layerstructure.js
src/js/stores/document.js
src/js/stores/menu.js

Problem:
On deleting a layer, we would transfer to  initialize the newly selected layer so it would actually get doc store to emit a change event. However, if the deleted layer caused a canvas resize shift, we would handle this by translating all the layers in the document by the shift. And we would translate the newly selected layer's shifted boundaries. So things would go to shift.
So now, instead of transferring to initializeLayers, I enqueue that action. This way, handleCanvasShift gets played first, and then init layers gets played, and the bounds are correctly shifted / initialized.
@iwehrman I don't know whether you'll agree with this fix. But I can't figure out a cleaner way. So please review and argue with me tomorrow.
Addresses #2713

Enqueue initialize instead of transferring to in removeLayers

---

src/js/actions/documents.js
src/js/actions/search.js
src/js/actions/search/layers.js
src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/TextInput.jsx
src/js/stores/application.js
src/nls/root/menu.json
src/nls/root/strings.json

1. Display a read-only "initializing.." message while initializing background documents instead of showing nothing for a long period of time. This improves the user experience. Partially addresses #2781.
2. Do a better job preserving search focus when tabbing away and back. The search-in-progress is no longer committed. Focus is correctly preserved when tabbing away. For some reason it still loses focus  though when you click on another application window!? Partially addresses #2759 and #2057.
3. Speed up formatting of layer name results by not reducing the layer ancestry to use the "shortest unique paths". I think this makes more sense from a UX perspective, and it's also happens to be terribly slow. Also partially addresses #2781.
4. Rename "Current Documents" to "Open Documents".
5. …

Misc search improvements

---

src/js/actions/shortcuts.js
src/js/actions/tools.js
src/js/events.js
src/js/stores/shortcut.js

1. Add a new `shortcuts.addShortcuts` action to add shortcuts in bulk.
2. Use one call to `shortcuts.addShortcuts` in `tools.beforeStartup`. Previously, we were doing separate transfers for each call to `shortcuts.addShortcut` (singular) which was both bad for performance (N redundant policy calls in the adapter instead of one) and a concurrency-safety problem waiting to happen. 

Add shortcuts.addShortcuts to add shortcuts

---

src/js/actions/libraries.js
src/js/jsx/sections/libraries/Library.jsx
src/js/stores/library.js

This PR addresses issue #2642 by removing stale edit status in the initial load (when you open the graphic in DS and close the document in classic).

CC Libraries - fix open-dialog issue when double click graphic for edit.

---

src/js/actions/documents.js
src/js/actions/tools.js

1. Abort `changeVectorMaskMode` early if there is no document open.
2. Do not `changeVectorMaskMode` in `documents.open` until the document has been initialized.
Addresses #2779.

Wait to change vector mask mode until document is initialized

---

src/js/jsx/shared/Dialog.jsx

Addresses #2424. 
Ideally I think these would just be suppressed, but I'm not sure how to do that and I _am_ sure how to do this! All dialogs with a `dismissOnCanvasClick` policy will have the same behavior. 
PS: actually, I do know how to suppress these events: by using a policy over the canvas region. But, that seems fairly risky compared to this simple change.
Also note: this does _not_ address a similar problem with pinch-to-zoom. To handle that, we would need to do something at a very different level because there are no adapter os events for the pinch gesture. For example, the cloaking mechanism would have to know whether or not there is a dialog open that is on top of the canvas. So, this is definitely still an issue, but one that I think will have to be addressed separately!

Dismiss the export dialog on wheel events

---

src/js/stores/menu.js

This addresses #2652 
When ungrouping layers, the menu was not recognizing this change, and so in some cases the "undo" menu item was left inactive.

Menu stores now listens for UNGROUP_SELECTED

---

src/style/panel.less

Okay, chatted with @placegraphichere and decided on keeping the icon at the 24px sizing that it natively is...which ended up being achieved by deleting some CSS.

Fixed size of reference tool

---

src/js/actions/layereffects.js
src/js/actions/sampler.js
src/js/jsx/tools/SamplerOverlay.jsx
src/js/models/effects/layereffect.js
src/js/models/layer.js

This PR addresses the following sampler issues:
#2777 Sampling Text via HUD sometimes fails on first click, takes 2nd or double-clicks
#2826 Sampler: Shift + click to sample Typeface fails. This is fixed by increasing the clickable area of the type button in the HUB.

Sampler - addresses 2777 & 2826

---

src/js/actions/export.js
src/js/locks.js

There are three components to this PR, the first two of which address #2799, and the other fixes an unreported bug that I noticed while testing.
1. When export service completes its initialization, it updates the store's "available" flag via a separate flux action (instead of transfer) so that it only gets the JS_EXPORT lock when it needs it, thus not preventing other actions in the meantime.
1. Remove the GENERATOR lock entirely.  Because the plugin's websocket interface will allow concurrent calls, there is no practical need for this lock. *This* lock (held by the export's afterStartup action) was preventing the `document.close` action which uses generator to clean up old temp files.
1. Allow (only) the post-export asset update to fail silently - these updates are not strictly necessary …

 Improve export service startup to not lock other actions, better error handling on post-export asset updates

---

src/js/actions/layers.js

This is another very narrow fix for another `resetBorderPolicies` race that results in ghostly border policies. In this case, it's between the `layers.select` action and its transfer to `layers.initializeLayers`. Their calls to `resetBorderPolicies` interleave in a bad way, and the border polices are never cleaned up, which causes issues like in #2224. See for yourself:
Fixing this one was easy (`initializeLayers` always calls `resetBorderPolicies` anyway, so I just removed the other, redundant call), but these sure are fun to find! Recall that #2794 intends to make this entire class of bugs go away forever.

Narrow fix for another resetBorderPolicies race

---

src/js/actions/ui.js
src/js/events.js
src/js/jsx/tools/SamplerOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/stores/ui.js

This causes the on-canvas UI (i.e., the `SamplerOverlay` and `SuperselectOverlay`) to be redrawn upon receiving a `displayConfigurationChanged` event using pixel values that are current for the new browser root-size (i.e., with the same rem value but with updated pixel value). These events are emitted when the screen resolution changes or the when the window is moved between displays. Note for testing: Chromium doesn't seem to update it's CSS breakpoints when you just change the screen resolution on a single display. But it should do so, and hence is testable, when dragging the window between displays.
This also fixes the erroneously named and defined `pxToRem` function. In fact, we're converting a rems to pixels. The function was also off by a factor of 1/16, which forced the callers to …

Redraw on-canvas UI when display configuration changes

---

src/js/actions/documents.js
src/js/jsx/DocumentHeader.jsx
src/js/stores/application.js

This prevents the document tabs from mounting one at a time, which is distracting. Yes, it delays the render somewhat, but since we initialize documents lazily now, it shouldn't slow things down too much. This also prevents a re-render from happening when the controller resets.
Addresses #2843.

Delay rendering document header until inactive documents are loaded

---

src/js/jsx/DocumentHeaderTab.jsx
src/style/document-header.less

Regarding issue #2842 
Now looks like:

Moved the dirty document indicator and changed the color to red

---

src/js/actions/documents.js

Always call `initInactiveDocuments` after startup to ensure that the `inactiveDocumentsInitialized` store state is set.
Addresses #2855.

Always call initInactiveDocuments after startup

---

src/js/actions/libraries.js
src/js/actions/menu.js
src/js/events.js
src/js/stores/menu.js

This is similar to libraries drag-n-drop, the event policies have to be suspended before executing place commands via the menu item, and then restored afterward; otherwise, DS will be freezed. Addresses issue #2770

Suspend/Restore event policies around menu's place commands.

---

src/style/document-header.less

Regarding issue #2711 
Now looks like:

Added a border around .document-container instead of shadow

---

src/js/stores/ui.js
src/nls/root/menu.json

This anticipates the single-column mode overlay offsets when opening the first document from the no-doc UI. 
Addresses #2801. 
This also fixes a grammar nit.

Correctly center first document in single-column mode

---

src/js/jsx/sections/layers/LayerFace.jsx
src/js/models/smartobject.js
src/js/util/svg.js
src/nls/root/strings.json
src/style/shared/colors.less
src/style/shared/icons.less

Requires pgdv.679 or later.
layer.smartObject now contains `linkMissing` and `linkChanged` properties. We use `linkMissing` to change our own layer panel icons.
We currently do not get any notification from PS when this status changes, so it's up to us to later on hook up queries and model updates on our side.
Addresses #1990 and #2083

Hook up missing link icons for linked and cloud smart objects

---

src/js/jsx/sections/style/Type.jsx

Regarding issue #2821 
Before: 
After:

Number input for text values made larger

---

src/js/models/layer.js
src/js/models/smartobject.js

It seems that if a linked smart object has a broken link, the descriptor's `linked` property is still *true* and its `link` contains a *string* instead of the fully formed *object*.
This PR contains a very narrow fix for this scenario, and I'm sure it could probably use some further clean-up.  It feels like there's a better way to model the smart object properties.  But, that would take some digging, and this is a :red_circle: Fix Now bug.  Addresses #2887

Deal with smart objects with broken links

---

src/js/actions/libraries.js
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/Library.jsx
src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/shared/TextInput.jsx
src/js/util/libraries.js
src/style/sections/libraries/libraries-section.less

This PR introduces the following changes:
* During library creation, the current library's content will be hidden, to reduce confusion and give user clear instruction on where to input the library name. - addresses #2197
* Hitting return / esc can confirm / cancel the current library command (creation or rename). - addresses #2864 
* Handle edge case that asset may have empty representation and will cause exception.

CC Libraries - tweaks for library creation and rename

---

src/js/jsx/DocumentHeader.jsx
src/style/document-header.less

This is related to issue #2558. Taki is not happy that the document header got shrinked in the middle. He is wondering if it is possible to trigger the shrinking only when the container is out of space. I couldn't come up with a easy solution for this (it requires some extra work to detect if whether or not the header will be out of space), so I adjusted its behavior to use smaller text when reach maximum header count, where the count is dynamically calculated based on the current width of the container. This looks good to me, at least the user won't be surprised that the text is shrinked in the middle.
Here is the before and after comparision:

Fine tune the document header resizing behavior

---

src/js/actions/layers.js
src/js/actions/transform.js
src/js/events.js
src/js/stores/history.js

The primary bug this addresses is #1613, but there are a few other possibly-unreported bugs that are fixed.
When we option-dragging multiple artboards, we get two move events.  The debouncing of the event handler was causing us to NOT process the fancy event that notifies us of the duplication.  So, we weren't adding the layers to the model...and then things blew up downstream.  I rearranged the handler to only debounce the "regular" move events.  I'll be honest, I don't know why this needs to be debounced at all, but I wanted to make the most narrow change I could.
I essentially undid commit 529eb5e34a667ad3aa043a18bfc5ebae02ba309f from barkin (via PR #2672) which I can only assume means that the underlying core (events) behavior has changed.  "move" events were being ignored if it …

"move" event bug fixes

---

src/js/actions/policy.js
src/js/actions/tools.js
src/js/tools/sampler.js
src/js/tools/superselect.js

In some tool handlers, we are using `UI.setPointerPropagationMode` to set pointer mode directly and did not dispatch a `mode changed` event to the policy store, and thus the actual pointer mode is out of sync with the store. This will cause problem if we suspend/restore policy actions as the pointer mode might be restored to a wrong one. This PR replaces `UI.setPointerPropagationMode` calls with `policyActions.setMode` to make sure the policy store is in sync. This will address issue #2849

Addresses issue that restoring policy will set to incorrect mode

---

src/js/jsx/tools/SuperselectOverlay.jsx

Prevent the plus icons from showing up around the artboard if it is invisible.  Addresses #2596

Don't draw artboard 'adders' if the artboard is not visible

---

src/style/toolbar.less

After the fix for issue #2639 got merged with PR #2891, @designedbyscience noticed the icons in the toolbar were off. This is the fix for that -- made a new less variable with the +0.2rem change and changed all the widths in toolbar.less to be of that width.

Adjusted toolbar elements to account for retina display fix

---

src/js/jsx/sections/libraries/Library.jsx
src/js/jsx/sections/style/ShadowList.jsx
src/style/sections/libraries/libraries-section.less
src/style/shared/title-header.less

* Used the Layers panel to compare the Libraries panel against
- Added a new class with styles for different colors for subtitles
- Restructured the DOM for the Libraries panel to match the Effects panel 
- Due to the restructuring, changed the CSS for the Libraries panel a bit to match its previous alignments. 
Pictures of before and after are in the issue this references: #2629.

Visual changes to the Libraries panel

---

src/js/jsx/shared/CheckBox.jsx

uses !jsx prefix now.  This was causing the minified sources to bork.

Fixed SVGIcon require in CheckBox

---

src/js/actions/layers.js
src/js/stores/document.js

What it says! Requires Mac pgdev.761 or later. Over to @mcilroyc again because of a possibly controversial history state change: when `resetLayers` is called with `amendHistory`, I now suppress setting the dirty bit. This seems reasonable to me because in theory there was some previous change which _also_ set the dirty bit (hence the amendment), but I could use a second opinion.
Addresses #1903.

Do not dirty the document when changing the selection.

---

src/js/jsx/sections/style/ShadowList.jsx

What it says!
Addresses #2929.
**NOTE** We might need a UIF exception for this (https://watsonexp.corp.adobe.com/#bug=4071268). So, please don't merge until I get permission from @jsbache.

Correct the inner shadow x/y input tooltip

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/sections/export/ExportList.jsx
src/js/jsx/shared/Datalist.jsx

This addresses #2807, #2808, and an unreported issue: extra history state when committing a change to the "format" datalist of export asset configurations.
The default value of the `DataList` parameter `autoSelect` was `true`, and this was triggering a bug when hitting ESC.  Interestingly, even with that parameter defaulting to true, the datalist did not behave autoSelecty... so by setting this false, we aren't losing any functionality.  YES, I do believe there may still be a bug lurking deep inside DataList, but I wanted to keep this PR out of it, if at all possible.
FWIW, there is still one annoying issue with these export inputs right now: after making a new selection in the datalist, the input losing focus.  This means that hitting tab will change layer selection, not tab to the next …

ExportList now uses autoSelect=false and changeOnBlur=false datalist params

---

src/js/jsx/Main.jsx
src/js/jsx/sections/export/ExportList.jsx
src/js/jsx/sections/style/ShadowList.jsx
src/js/jsx/sections/style/VectorFill.jsx
src/js/util/system.js
src/style/panel.less
src/style/sections/style/layer-effect.less

Fixed the input labels for overflow. 
Now we can use the :lang() pseudo selector in our CSS for localization purposes. 
references: #2571 
1.) @ktaki Please check all the labels and titles in this screenshot are correct. 
2.) @placegraphichere Please approve the spacings between the labels. 
3.) @placegraphichere Please approve the spacing between the opacity label and its input 
4.) @placegraphichere Let me know if the spacing between labels and inputs is ok here

Localization fixes for Japanese and German

---

src/js/actions/layers.js
src/js/actions/type.js
src/js/models/layer.js
src/js/models/layerstructure.js
src/js/stores/document.js

With this change, we now listen for the new `fontListChanged` event, which happens when the system font list changes, handles it by updating the font list (if it is already initialized) when the font list changes. The selected text layers are also reset when this happens so that the layers panel reflects the change immediately. Note that sometimes it is necessary for the tool to be changed before Photoshop will send this event the first time.
Assigning this to @mcilroyc because I could use a second opinion on the `resetLayers` call. Which is to say, I don't think this should create a new history state, but also I'm updating the document model, so... ?
Addresses #1326.

Sync font list changes

---

src/js/stores/menu.js

This addresses #2949.  I recently added a new event that allows history state to be wrapped up and finalized after a complex transaction.  It is currently used only by the move handler.  The menu wasn't listening for this new event, so the menu was not showing "undo" as valid option after the first layer move with a clean doc.

menu store now listens for the new finalize_history event

---

src/js/actions/libraries.js
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/models/layer.js

As the title suggested, when you open a 3D graphic for edit, and try to save the document, DS won't update it to the graphic as we don't support editing 3D, also saving the changes will trigger errors afterward. This will address #2545
This PR also change the restriction on adding SO to CC Libiraries. You can now add any locally-linked SO, after that, the layer will turn into cloud-linked SO and adding it  to the libraries again is disabled.

CC Libraries - don't update graphic when saving unsupported document.

---

src/js/jsx/shared/Dialog.jsx
src/style/help/first-launch.less
src/style/search/search-bar.less
src/style/shared/dialog.less

Since the number of complicating factors for centering the dialogs keeps increasing (toolbar pinned/not pinned, 1 or 2 columns open, single column mode), we are switching to using JS to center the dialogs.
If there is enough space over the canvas for the dialog, we center it over the canvas (based on the cloaking bounds), otherwise, we center it on the screen

Center dialogs with JS calculation rather than CSS

---

src/js/actions/layers.js

This fixes a dumb programming error from yours truly in the new lazy path through `resetLayers` which caused it to only return the very first layer's descriptor repeatedly. Whoops!
Should address the follow-up bug reported by @ktaki in #1326.

Fix lazy resetLayers result collation 

---

src/js/actions/documents.js
src/js/actions/libraries.js
src/js/fluxcontroller.js
src/js/jsx/sections/style/ShadowList.jsx

This PR fixes:
1 selected empty layer is not replaced after placing file. addresses issue #2819. I checked the three difference way of placing file and here is the summary:
1. place file via menu item (place linked or embedded): empty layer will be replaced.
2. drag-n-drop local file: empty layer will be replaced.
3. drag-n-drop CC libraries graphic: empty layer will not be replaced.
**Require dev > 743 to receive the replaced layer id in `placeEvent` attributes**
2 React warn about missing unique key in children. #2651

Fix incorrect layer index after placing file and calm React warning

---

src/js/actions/transform.js

References issue #2840 
Before: 
After: 
Correct behavior -- X and Y only changes when the reference point is changed. When one changes the Width or Height, the layer should move in the opposite direction as the reference point. For example, if the reference point is set to Bottom Right, changing the width should move the left position of the layer and changing the height should change the top position of the layer. The reference point serves as an anchor, therefore does not move. Thus, the X and Y coordinates should not move either when changing the height and width inputs.

Reference Point: Changing W and H does not change X and Y coordinates

---

src/js/jsx/shared/Datalist.jsx

While looking into #2465, it became apparent that we were not longer filtering hidden options from datalists. This should fix #2465 in that we shouldn't have been able to see luminosity as an option anyways

Do not show hidden options in datalist

---

src/js/actions/libraries.js

This PR fix BMP and SVG graphic types so that you can add them to libraries, or drag from libraries. It also added checker to prevent from creating graphic with wrong representation type. Addresses issue #2945
This is a testing library I created with all graphic types: http://adobe.ly/1QtMpK3

CC Libraries: fix for BMP and SVG graphic types

---

src/js/jsx/shared/Draggable.jsx
src/js/util/math.js

On Windows (and very occasionally on Mac) mouse clicks can cause a mousedown as well as a mousemove event, even when the mouse is not actually moved during the click. This causes our drag logic to kick in, which also suppresses the following click event to prevent interference. In the case of false drags, this click suppression causes problems, e.g. failing to select layers in the layers panel, and probably other cases we haven't noticed.
@jsbache suggested that the drag operations should not start until the distance between the mousemove events and the original mousedown position exceeds some modest threshold. That's exactly what this PR does, and @chadrolfs' preliminary testing suggests that this addresses #1781. Concretely, the `Draggable` component waits to set the `dragging` bit …

Delay drag start until a distance threshold is crossed

---

src/js/actions/export.js
src/js/util/exportservice.js

This rotted in two remarkable ways.  So many feels.
Addresses #2958 
1. It would seem that the error returned by generator/JSX when a user cancels the dialog has changed from an object with a `message` property, to a simple string.  This is troubling, but I'm not sure how hard I want to try and figure out when/why it changed.
2. The previous approach was to throw a custom error in this case, and handle it in the export action that transferred to promptForFolder.  But, the transfer system is puking on that error now.  I'm fairly confident this used to work ... but anyway now I'm going with a simpler approach of simply resolving null in this case.  No fuss no muss.
The diff looks messier than it actually is.  The meat of the export logic got bumped in a couple of tab stops.

Fixed handling when a user cancels out of the folder chooser dialog

---

src/js/jsx/shared/Draggable.jsx

We currently add a click handler when a drag operation starts which stops propagation of the click event. This is because in some cases the drag-ending mouseup is followed by a click event that causes weird things to happen (e.g., entering layer rename mode at the end of a drag). But, we don't _always_ get the click event, so this just removes the post-drag click handler after a short timeout in case the spurious click never arrives.
Addresses #2964.

Fix lost click after drag

---

src/js/actions/policy.js
src/js/jsx/mixin/Focusable.js
src/js/tools/superselect.js
src/js/tools/superselect/vector.js

This removes a fertile source of errors with keyboard policies. Many moons ago @pineapplespatula had to add these so that arrow keys worked correctly in CEF text inputs while in the type modal tool state. This creates a bit of a concurrency nightmare, however, which was never fully addressed. See, e.g., #2650. However, @jfitz-adobe has recently relieved us of the need to install these arrow keyboard policies. This removes the `Focusable` keyboard policies entirely, and thus reduces the number of places where we can hurt ourselves with policy manipulation.
Should fully address #2650. Requires >= Mac pgdev.734, or whatever the latest Windows build was when this PR was filed.
(Also, it would be great to verify this on Windows too.)

Don't add/remove arrow keyboard policies on focus

---

src/js/jsx/sections/style/Type.jsx
src/js/jsx/shared/Datalist.jsx

References #2917 
When type layer is clicked on, if the font is missing, the typeface datalist will fill with the [*name of missing font*]. If multiple missing font layers are selected, the datalist reads [Missing fonts].

Typeface datalist updates with missing font name 

---

src/js/tools/ellipse.js
src/js/tools/rectangle.js
src/js/tools/superselect/vector.js

fix for issue # 2670 
there is still an issue with escaping from superselect/vector some of the time, but i think it should not block this PR, (and it have a feeling that it may be resolved by some of the other open vector mask PRs)

add escape handlers for vector mask tools

---

src/js/jsx/sections/style/Radius.jsx

References issue #1529 
Note: The reason I added the variable ```maxRadiusInput``` is because currently the Range slider uses ```maxRadius``` and the maximum value is an integer. If you use maxRadius as the max value for the input, it stops at either an integer or a .5 decimal value. Therefore ```maxRadiusInput``` makes sure the Range slider and Input values are the same no matter which you use.

added min and max for the rectangle radius

---

src/js/actions/type.js
src/js/stores/font.js

Currently, typeface names and family names are translated inconsistently, with family names always being in their native language and face names always English-only. This PR ensures that the translation is consistent, either always in the native language, or always English-only, respecting the Photoshop user preference (`Type > Show English Font Names`). 
Relies on adobe-photoshop/spaces-adapter#156.
Addresses #948. 
Thanks to @isonno for supplying the additional scripting API properties needed for this!

Consistent translation of non-English font strings

---

src/js/actions/layers.js
src/js/jsx/sections/layers/LayerFace.jsx
src/js/stores/document.js

This changes selection when collapsing groups to match Photoshop. It ensures that hidden children remain selected when a containing group is collapsed. In particular, this moves selection from selected descendants to the parent, but only if necessary, when collapsing groups. Otherwise, just clicking the group icon will (still) not change the selection. This is the same behavior as the standard Photoshop layer group disclosure triangles AFAICT.
Addresses #2538.

Update selection when collapsing groups

---

src/js/jsx/DocumentHeader.jsx
src/style/document-header.less
src/style/shared/icons.less

References #2956  
Small changes to the icon sizes so that they don't get cut off and the search icon looks as big as the other icons.

Icon header sizes adjusted 

---

src/js/stores/style.js
src/js/tools/sampler.js

This PR addresses the follwoing sampler issues:
1. should hide the sampler HUB after zoom/scroll/resize (fixe #2850)
2. with sampler tool selected, hit space will throw error in no-doc mode.

sampler: hide sampler HUB on zoom, scroll, resize

---

src/js/actions/layers.js
src/js/stores/draganddrop.js
src/static/menu-actions.json

We have lazy loading for layer attributes on startup (`layer.initialized === false`) until they are selected. When a layer is uninitialized and you reorder it without selecting it, DS will play the descriptor command but skip emmiting a change event because it thinks the layer is not initlaized and trying to avoid UI redraw (https://github.com/adobe-photoshop/spaces-design/blob/master/src/js/stores/document.js#L180). Now, what you have in the layer panel, are layers remain unchanged but inside Photoshop the reorder command is completed. Then, if you try to reorder again, it will fail and throw error. 
I made a simple fix by selecting the dragged layer (if it haven't) before reordering; this will:
1. make sure the layer is selected and initialized
2. the dragged layer is shown as selected …

Fix for layer reordering

---

src/js/actions/ui.js

Disable overlays before setting the transform to prevent artboard buttons from flashing in the previous location at the end of a pan when the cloak ends. 
Addresses #2714.

Disable overlays before setting the transform

---

src/js/actions/documents.js
src/js/actions/layers.js
src/js/jsx/Scrim.jsx
src/style/scrim.less

When the current document is unsupported (3D / non-RGB color mode):
1. all mouse interaction is disabled by blocking mouse events to the canvas.
2. document's layers are deselected by default, to prevent keyboard events (e.g. using arrow keys to change layer positon)
Hopefully will address issue #2545 completely.

Disable possible mouse/keyboard interaction with unsupported document.

---

src/js/stores/tool.js

We now have to infer tools based on the application of `nativeToolName` because it is now a function instead of a property.
Addresses #2989.

Fix startup tool inference

---

src/js/actions/policy.js
src/js/tools/superselect.js

1. Revert default keyboard mode to `NEVER_PROPAGATE`.
2. Install (new from @jfitz-adobe!) `FOCUS_PROPAGATE` keyboard _policies_ in the select tool for arrow keys.
This restores the default keyboard routing behavior so that key events by default only go to CEF. If you want to send a keystroke to Photoshop from now on, you probably want to install a `FOCUS_PROPAGATE` policy for it. (The `FOCUS_PROPAGATE` policy action is new and requires at least Mac pgdev.790) In particular, you _only_ want to install an `ALWAYS_PROPAGATE` policy if you don't think CEF should get the key event _even when a text input is focused_, which is almost never because that would be a highly confusing interaction.
Addresses #2984 and #2986.  Requires Mac pgdev.790.

Stop propagating keyboard events to PS by default; propagate arrow key events by focus

---

src/js/jsx/sections/style/ColorOverlayList.jsx
src/js/jsx/sections/style/StrokeList.jsx
src/js/jsx/sections/style/UnsupportedEffectList.jsx
src/style/sections/style/layer-effect.less

References #3008 
Before: 
After:

Effects panel subheader colors corrected

---

src/js/actions/tools.js
src/js/jsx/tools/PolicyOverlay.jsx

This add additional border policies for three on-canvas interactions:
1. Proportional resize by shift-clicking and dragging a corner anchor;
2. Proportional skew by command-shift clicking (or control-shift clicking on Windows) and dragging an anchor; and
3. Angle-constrained rotation by shift-clicking and dragging outside a corner anchor.
I'm actually not sure if these ever worked, but I'd guess that they never did. (Note that shift-marquee selection is broken on master, but is FIP in #2975.)
Addresses #2998.

Fix proportional resize, proportional skew and angle-constrained rotation

---

src/js/actions/edit.js
src/js/actions/shortcuts.js
src/js/util/dom.js

Currently, global shortcuts are disabled when any HTML element has focus. This makes sense when the focused element is a text input (typing `v` should insert a `v` character, not activate the select tool), but makes less sense for focused non-input elements like the color swatch. This prevents you, e.g., from dismissing the color picker (which focuses the swatch) and then immediately selecting a tool without first hitting escape, which seems pedantic.
This changes the shortcut matching algorithm to only be disabled for focused input elements. Furthermore, if a non-input element is focused and there is some shortcut that matches then the focused element is blurred before executing the handlers.
I'm pretty sure there was an open issue about this, but darned if I can find it.

Allow shortcuts when non-input elements have focus

---

src/js/jsx/shared/ColorInput.jsx
src/js/jsx/shared/ColorPicker.jsx

The `ColorInput` has three change event handlers:
1. `onColorChange` for changes to the opaque (RGB) color;
2. `onAlphaChange` for changes to the alpha (and not RGB) value;
3. `onChange` for arbitrary color changes.
The latter wasn't correctly percolating from the `ColorInput` to the internal `ColorPicker` component, which prevented color changes in the picker's text input to not correctly propagate changes to the opacity. This fixes that.
One reason why this problem wasn't caught earlier is that the three handlers were not marked as required for either component, and the default value for `onChange` was the identity. To avoid this in teh future, all three handlers are now marked as required for both components.
These components have become fairly convoluted since moving the text input …

Add missing onChange prop to ColorPicker

---

src/js/actions/documents.js
src/js/actions/edit.js
src/js/actions/history.js
src/js/actions/libraries.js
src/js/actions/menu.js
src/js/actions/tools.js

This addresses #2800, but makes some fairly significant changes to the way policies are suspended in/around the place object workflows.
The main change is that when entering a tool state, we suspend policies for ALL tools (except direct select, for mask mode compatibility), not just `txBx` as before.  Is this safe?  Seems OK to me, but there may be situations I'm not aware of.  Prior to this change, the enter key was being handled by DS and causing a SS "diveIn".  This seemed to work OK for single placements, but borks for multi-object placements.
When dragging an object from the library, the above change means that we no longer need to suspend policies directly from the libraries action, so I removed that.
The place-via-native-menu-commands flow is largely unchanged, but we now validate …

Place object - policy and history changes

---

src/js/tools/pen.js

fix for issue #3029 
requires https://github.com/adobe-photoshop/spaces-adapter/pull/159

 deselect paths when pen tool is not in vector mask mode

---

src/js/jsx/sections/style/Type.jsx

There were some outstanding problems after #2983 got merged, this PR addresses them. @ktaki If you can double check below that these are the expected behaviors, that would be great. References issue #2917.
Expected behavior now:
| Case  | Placeholder Text |
| ------------- | ------------- |
| 1 missing font  | [name of the font]  |
| 2+ missing fonts    |  [Mixed Fonts]  |
| 1 present font    |  name of font  |
| 2+ present fonts    |  Mixed Fonts |
| 1+ missing and present fonts   |  [Mixed Fonts] |
| 1+ missing & all the same font   |  [name of the font] |
| 1+ present & all the same font   |  name of the font |

Typeface datalist updates with missing font name

---

src/js/actions/layers.js
src/js/actions/libraries.js
src/js/actions/sampler.js
src/js/actions/shapes.js
src/js/actions/transform.js
src/js/events.js
src/js/jsx/sections/style/EffectsPanel.jsx
src/js/jsx/sections/style/Type.jsx
src/js/stores/style.js

This PR makes two changes to the copy/paste buttons:
1 copy/paste buttons in the appearances now include opacity, radius, and blend mode. This should apply for text layer, vector layer, and other layers (e.g. SO). You can checkout the video for more details of the bahaviors: https://www.dropbox.com/s/lao6v0xo6nezt0g/copy-styles.mov?dl=0. Addresses #2755 
2 copy/paste buttons in the effects panel should only apply to layer effects (used to include appearance styles). Same for the appearance panel, buttons should not copy/paste layer effects. 
1 copy/paste appearance between two text layers with different opacity result in number change back and forth.
2 undo paste-styles some times does not reset the appeanrace panel

Fix for copy/paste buttons in appearance and effects panels

---

src/js/jsx/sections/style/Type.jsx
src/js/stores/font.js

This PR addresses the following issues:
1 typeface should ordered case insensitively. (#2530)
2 some typefaces are not ordered by title. This is becuase we ordered typeface by postScriptName, and it turns out that `title` does not always match with `postScriptName`. For example `title: Wide Latin, postScriptName: LatinWide`, `title: Wawati SC Regular, postScriptName: DFWaWaSC-W5`.
The fix is to sort typefaces by upper case title, instead of postScriptName. However, it breaks the binary search in `Select._findIndex`, as postScriptNames (which are the ids of of Select's options) are longer ordered. So another change I made is replacing the ID with typeface index (zero padding string). I have several solutions, and this is the one that requires least changes. Do let me know if you have …

Fix ordering of the typefaces list 

---

src/js/actions/menu.js
src/js/jsx/help/FirstLaunch.jsx
src/js/util/ui.js
src/static/menu-actions.json

References issue #1648 
Added calls to the Headlights API for the Introduction screen (Twitter, Github, and Forum) and the menu (Twitter, HelpX, and Forum) 
If we choose to merge this as is, then we need to update this wiki with the new headlights trio that is being used: https://github.com/adobe-photoshop/spaces-design/wiki/Headlights-Categories,-Subcategories,-and-Events

Instrument all external links with Headlights API

---

src/js/util/exportservice.js

Previous was 20 seconds, and it was fairly easy to cause this to bonk out for large exports.  For example:
1. Open a large JPG file in DS (my test case was 7MB)
1. Unlock the background layer, and add a PNG (default) asset
1. Export it - and note that you might see a console "timeout" message
Addresses (or reduces the frequency of) #2340

Increase the timeout for export ws calls to two minutes

---

src/js/actions/layers.js
src/js/stores/history.js

This is a follow-up fix for #2831
1. Allow handleCanvasShift action during modal state.  When dragging a layer, a canvas shift may occur during the drag.  It seems safe to me to allow that action to get queued up without breaking modal state.
1. A narrow fix of the history amendment process which should *not* overwrite the "rogue" flag (set when we get a history state event for an action that photoshop initiates).  The bug here is that if that rogue flag gets reset, then our follow-up action won't know it is safe to amend the roguely-created history state.

move layer history fix

---

src/js/jsx/PanelSet.jsx

This fixes a race condition in `PanelSet` when toggling panel and column visibility. Those functions would both call `setState` and `setPreferences`, both of which are asynchronous, without synchronization. In some interleavings, the toggled state is lost. (The details of the interleavings are complicated but boring.) This eliminates the _direct_ `setState` calls in favor of just setting the preferences, and then also having the component listen to the preferences store for updates.
Addresses #2448 again! @ktaki Please test, if you have a moment.

Fix panel/column visibility toggle race

---

src/js/actions/layereffects.js
src/js/actions/layers.js
src/js/actions/shapes.js
src/js/actions/transform.js

Instead of merging on action options, we should merge on a plain object for the following reasons:
1. the option could be `undefined`, and `_merge(options, {enabled: true})` will return `undefined`, instead of `{enabled: true}`
2. merging on the `options` directly will pollute the object, and we should avoid doing that as the `options` may be shared between multiple actions. for example: https://github.com/adobe-photoshop/spaces-design/blob/master/src/js/actions/sampler.js#L583
So a recommneded / safer pattern would be:
```
_.merge({}, options, {enabled: true})
```
addresses issue #3034

Fix issues caused by merging on undefined/null options using `_.merge`.

---

src/js/jsx/DocumentHeader.jsx

The document that is currently selected should scroll into view in the document header. It wasn't and now it is. Also made it work more betterer at the expense of the getBoundingRect call

Fixes document title scrolling behavior

---

src/js/jsx/shared/Datalist.jsx

Addresses #3065. 
It's a major bummer that simply returning true in `shouldComponentUpdate` breaks `Datalist`.

Fix a typo in Datalist's shouldComponentUpdate method

---

src/js/actions/menu.js

`menu.native` should return the command result so that the pen tool is notified whether the path is deleted or not. Address issue #3078

Action `menu.native` should return the command result.

---

src/js/actions/history.js
src/js/stores/history.js

This addresses, or at least takes some sting off of #2073.  At the very least, this reduces the chattiness into the main PS log.  I believe that at the debug level, these messages are of ongoing usefulness.

Reduced history-related log messages to "debug"

---

src/js/models/layerstructure.js

This replaces an apparently unnecessary `mergeDeep` call with a faster `merge` call in `Layerstructure.prototype.resetBounds`. Changing a font in Vermilion previously looked like this:
Now it looks like this:
That is, the time is now dominated by React instead of Immutable, saving ~250ms.
Addresses #3057.

Replace mergeDeep with merge in Layerstructure.prototype.resetBounds

---

src/js/actions/layers.js
src/js/tools/pen.js
src/js/tools/superselect/vector.js

This adds `FOCUS_PROPAGATE` arrow key policies in superselect vector mode and the pen tool to allow nudging selected points. Pretty cool.
Addresses #3075.

Allow nudging selected points in select vector-edit mode and pen tool

---

src/js/actions/sampler.js
src/js/jsx/tools/SamplerOverlay.jsx

Make graphic button in the sampler HUB easier to click, just like the Effects and Type buttons.
Addresses #3060
note: If you are testing with LLSO, you may encounter issue #3084

Make graphic button in the sampler HUB easier to click.

---

src/js/jsx/shared/ColorPicker.jsx
src/js/jsx/shared/Dialog.jsx
src/style/shared/color-picker.less

While attempting to work on #2560, I changed the targeted positioning of the dialogs to happen via state changes rather than the direct changing of properties
IT SEEMS TO WORK FINE. But that statement is a little worrisome, so more eyes/click to check would be better.
Also, that little arrow on the color picker goes away when it is placed above the target element

Change targeted dialog position via state, remove arrow of color picker when place above target

---

src/style/help/first-launch.less

References issue #3076 
Before: 
After:
I have also verified that all other screens are positioned correctly. The only one that needed to be changed was the Swap screen to avoid widows. That change is included in this PR also. 
Before: 
After:

French introduction screen positioning fixed

---

src/js/actions/edit.js
src/js/actions/history.js
src/js/stores/history.js

Handle touch-initiated time travel, by ~~attempting to load the given prev/next history state.~~ nuking history and updating the document.  This attempts such a maneuver only if a history state "select" event is soon followed by a historyState event for a prev/next history state.  These actions are also debounced so that 3-finger scrubbing will result in fewer updateDocument calls, hopefully just once when the scrubbing subsides.
The diff is a bit messy because I moved `handleHistoryState` further down in the file for organizational reasons, and factored out a `_loadHistory` helper function.
The crux of this PR is a short timer on the "select" handler (history state only) that, if it times out, will update the document.  Assuming that a historyState event follows quickly thereafter …

Handle step back/forward events that get initiated in photoshop

---

src/js/actions/transform.js

Otherwise, the document store will try to update the layer's radii attribute and then get reverted by the `resetLayer` action, which flash the radius slider when copy/paste layer styles. 
Addresses issue #3050

`transform.setRadius` should exclude layers that does not support radius.

---

src/js/jsx/PanelSet.jsx

What it says! Partially addresses #3088. 
I notice, however, that the on Windows (with the SP3 attached keyboard at least) we do not seem to reliably get keydown events with modifier changes. It seems to work ~50% of the time... So, better than nothing?

Make the swap-panels modifier command on Mac and control on Win.

---

src/js/actions/sampler.js
src/js/actions/type.js
src/js/jsx/tools/SamplerOverlay.jsx

This PR addresses the following issues:
1. copy/paste text styles will flash the opacity field. Fix for #3049 
2. sampling text styles should include opacity.

Coalesce multiple text attribute updates when pasting/sampling text styles

---

src/js/jsx/IconBar.jsx

This fixes a bug in which the `displayConfigurationChanged` event handler's event argument would be interpreted as a truthy argument to `_updatePanelSizes`, preventing `iconBarWidth` from being correctly set, thus making the cloaking rectangle too large and causing the UI to flash out when panning the canvas.
Addresses #3101. Low risk, AFAICT.

Fix cloaking rectangle bug when display configuration changes

---

src/js/jsx/sections/style/Type.jsx
src/js/models/layer.js
src/js/models/layerstructure.js
src/js/stores/font.js

These two styles are included in the previous PR, and this PR covers some edge cases:
1. copy/paste should include 0 tracking.
2. opacity is not copied after changing. Addresses #3100 
3. bonus: fix changing type weight.

Copy/Past text should include opacity and tracking - edge cases

---

src/js/actions/history.js

Reduces the impact of #3115.  In PR #3052 I began capturing "ID" from the historyState events from photoshop.  But, given the subsequent simplification of that PR (which attempts to handle touch undo events, and was eventually simplified), it is not strictly necessary to track ID.  Thus, this PR backs out that single line of code, which should prevent the errors described in 3115.
That said, the color picker is still not working correctly wrt history; it sometimes seems to invalidate the history states.  I believe this regression happened independent of 3052, possibly much earlier.

Remove the capture of ID from historyState events

---

src/js/actions/layers.js
src/js/actions/menu.js
src/js/actions/sampler.js
src/js/actions/superselect.js
src/js/actions/tools.js
src/js/jsx/DocumentHeader.jsx
src/js/jsx/PanelSet.jsx
src/js/jsx/search/SearchBar.jsx
src/js/jsx/sections/export/ExportPanel.jsx
src/js/jsx/sections/style/AppearancePanel.jsx
src/js/jsx/sections/style/ColorOverlayList.jsx
src/js/jsx/sections/style/EffectsPanel.jsx
src/js/jsx/sections/style/LayerBlendMode.jsx
src/js/jsx/sections/style/ShadowList.jsx
src/js/jsx/sections/style/StrokeList.jsx
src/js/util/headlights.js

References #3107 -- fix now 
With this: 
- Command + click on the panel icons logs the correct event (none-visible) 
- Mouse over blend mode in stroke, layer, shadow, and color-overlay now should track only track the final blendmode chosen
- Export panel + icon logs the correct event -- preset or no preset 
- Toggling individual panels are now tracked
- Document header icons are all tracked 
- Primary sampler and secondary sampler are tracked

Headlights tracking more

---

src/js/actions/history.js
src/js/events.js
src/js/jsx/shared/ColorInput.jsx
src/js/stores/history.js

This fixes two distinct problems with the color picker and undo/redo:
1. The `ColorInput` listens for `timetravel` events and uses them to forcefully reset the positions of the sliders to an up-to-date value. But, currently, it is simply resetting the sliders to their current position, which achieves nothing. This fixes that by using a value derived by instead re-parsing the input props to determine the correct color to which the sliders should be reset. This involves factoring out the parsing logic currently in the `render` method (which is totally gross) into a separate method which can be called by `render` and by this `timetravel` handler. Mostly this is just a cut-and-paste refactoring, though I did have to make some minor changes to account for `swatchClassProps` and friends.
2. The …

Reset color picker sliders on undo/redo

---

src/js/util/exportservice.js

This helps generator crash crash recovery in debug mode, and should have no effect in non-debug mode.
When in debug mode, we do an abbreviated attempt to connect to generator in order to find the possible existence of a remote generator.  This is simply to make it convenient for developers.  The problem is that this leaves the connection in "super quick mode" which gives up too quickly after a crash-restart.  This quick-fix simply makes it "kinda quick mode".  
@chadrolfs - you may want to use this branch when initially testing the generator crash-restart functionality which is available as of dev mac 842.

Increase the number of generator connection retries during 'debug' mode

---

src/js/actions/export.js

Only finite values are allowed to be logged in headlights calls

Took out "suffix" from headlights log

---

src/js/actions/sampler.js
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/models/characterstyle.js
src/js/models/text.js
src/js/stores/font.js

Addresses issue #3123 
If a text has multiple text styles (multiple text ranges with different text style), we will use the first character style (and the stroke color) in these tools:
* sampler
* copy/paste appearance
* create text style in libraries panel

Fix sampler and copy/paste text layer with multiple text styles

---

src/js/jsx/shared/ColorInput.jsx

`colorInfo.value` was never null after last `colorInfo` changes. 
Addresses #3131

Addresses bug where mixed class was not set properly on swatches

---

src/js/actions/sampler.js
src/js/models/layer.js
src/js/models/layerstructure.js

Addresses issue #3134 . 
Also fixed bugs related to out of sycn between `Text#firstCharacterStyle` and `Text#characterStyle`: after updating text style (size, color, tracking), clicking copy button will copy the out-dated style.

copy/paste: set text color by fill color, if style is not copied from text layer.

---

src/js/jsx/sections/libraries/assets/Graphic.jsx

Addresses issue #3130 
This is a wrok around due to the reason that modifiers are not updated while PS is in modal tool state.

Temporarily disable drag-and-drop for libraries graphic while in modal tool state

---

src/js/actions/transform.js

Updating position from the transform panel is broken for a locked layer (#3019). I traced down our commits and found the cause: we set to run the descriptor asynchronously for `transforms.setPosition`, and it might break the lock overwrite mechanism (position is set before the layer is unlocked). The change was introduced from #2626, however, I am not familiar with transform enough to figure out the purpose of this change. I marked this for discussion, and let me know if you know the purpose of the `synchronous: false` setting, or the way to work around this in lock overwrite mode.

Fix updating position of locked layers

---

src/js/actions/documents.js
src/js/actions/layers.js
src/js/actions/libraries.js

This PR fixes duplicate layers in our LayerStructure model due to adding a graphic with ALT key pressed. Usually, when the ALT key is pressed, PS will add the layers contained in the graphic, instead of creating LLSO, and will not enter modal tool state. However, if the graphic contains only one layer and it is an embedded SO, PS will enter modal state tool, which causes adding the duplicate layer when we handle the `placeEvent`.
So the solution is to check whether the layer is existed when handling `placeEvent`. I also added cheker to throw error in the `layers.addLayer`, if we are trying to add duplicate layers. 
To test: drag graphic `Embedded` from library `Test - OK ...` (or import the graphic from http://adobe.ly/1Mh2XAM) onto the canvas while holding the ALT key.
Addresses issues: …

Fix for duplicate layers due to adding graphic from cc libraries.

---

src/js/jsx/tools/SuperselectOverlay.jsx

Highlighting wouldn't work right when you were in a group and tried highlighting the siblings. Problem was, we would use whatever the hitTest was returning us, and with recent changes (or maybe it was wrong for the last two months) the order was different, and the layer we want to highlight would be preceded by it's owner group.
Now I consider what's super selectable, and only use the intersection of those with what PS tells us we're hovering over.
Addresses #3132

Fix sibling highlighting when in a grouped layer

---

src/js/actions/libraries.js
src/js/actions/sampler.js
src/style/shared/drop-down.less

Addresses issue #3168, which your last selected library was wrong due to reading the library state at a wrong timing. 
~~Removed extra lines #3166~~
Added right padding to dropdown input to avoid long title overlapping with the arrow icon.

Fix for wrong last selected library.

---

src/js/actions/guides.js
src/js/actions/layers.js
src/js/actions/tools.js

These actions were not modal, so during type tool use, we were killing modal state. Fixes type tool use

Fix modal flag of transferred actions during type tool use

---

src/js/jsx/PanelSet.jsx
src/js/models/documentindex.js
src/js/stores/application.js

This is a code cleanup that factors out a `DocumentIndex` model from the application store. It should preserve the existing functionality, but in a way (i.e., it is immutable) that should make writing `shouldComponentUpdate` functions a little easier. I also include a slight simplification of the `PanelSet` logic to fetch the set of initialized documents, reducing duplication of that logic. I haven't gone through the rest of the JSX to clean up more of this logic, but I thought it would be worthwhile to get this in now instead of waiting for more.

Factor out a DocumentIndex model

---

src/js/actions/tools.js

The outside propagate_by_alpha policy was kicking in because we didn't handle shift key on the inside area as we should. So holding down shift and clicking within the selection would send the click to PS.
Addresses #3195

Add an inside policy for shift modifier to border policies

---

src/js/stores/menu.js

We didn't, so doc would be set dirty, but save would be disabled. Which is #3191.

Update menu items on group expansion/collapse

---

src/js/actions/documents.js
src/js/actions/tools.js

Problem was, tools.installShapeDefaults would directly change the current active fill/stroke color if there was no document model loaded. And if we had rectangle tool selected in PS, during `tools.beforeStartup`, we would initialize the rectangle tool, and since `documents.beforeStartup` was not yet called, reset the defaults.
Solution was to move initTool call to tools.afterStartup, so document can be initialized in our models before we try to set shape defaults.
Addresses #3169

Prioritize documents.beforeStartup higher than tools.beforeStartup

---

src/js/jsx/shared/ColorPicker.jsx
src/style/sections/libraries/libraries-section.less
src/style/shared/color-picker.less
src/style/shared/label.less

1. Use throttled and delayed actions related to color/alpha in the components to improve color picker's reponse time. I defined a separate set of throlleted actions with `50` delay, instead of creating separate functions in each component, as we are likely to change / revmoe this fix in the future, but please let me know if you disagree. I am open to better solutions.
2. Show the mouse pointer when dragging within the color palette. 
3. Fix the position of the circular icon: its center should be the location of the mouse.

Make color picker more responsive

---

src/js/actions/layers.js
src/js/events.js
src/js/models/layerstructure.js
src/js/stores/document.js

In the past, incorrect or unnecessary `mergeDeep` calls have caused both functional correctness and performance issues. This replaces all the `mergeDeep` calls inside of `LayerStructure`, where most of them exist. In the process, I noticed that the `LAYER_BOUNDS_CHANGED` event was unused, so I also deleted that, as well as its handler in the document store.
Partially addresses #3066. "Partially" because some calls still remain. In particular, one in the `dialog` store and a few in the `documentexports` model. Any ideas about those, @mcilroyc?

Replace mergeDeep calls in LayerStructure with shallow merge calls

---

src/js/actions/documents.js

Initialize documents by ID instead of by `numberOfDocuments` and then by index. We wanted to do this a few weeks ago to work around a PS bug in which `itemIndex` would have crazy values, but we couldn't because the appropriate multiGetRef descriptor didn't quite work right. As of Mac pgdev.864 it does. Even with `itemIndex` bandaged over inside PS, I suggest that this is a less surprising way to initialize documents.

Initialize documents by ID

---

src/style/main.less
src/style/shared/colors-dark.less
src/style/shared/colors-light.less
src/style/shared/colors-medium.less
src/style/shared/colors-original.less
src/style/shared/colors-shared.less

This is a very simple factoring of the shared color styles functions into their own file, `colors-shared.less`, instead of being duplicated in each of the color theme files. It's just a copy-paste job.

Factor out colors-shared from color theme files

---

Gruntfile.js
package.json

This changes the `test` and `requirejs` grunt tasks to execute their subtasks concurrently. Since the subtasks just spawn grunt child processes, this effectively runs the subtasks in parallel. 
On an i7, this speeds up `grunt test` from ~15s to 9s, and `grunt requirejs` (which is called by `grunt compile` and `grunt build`) from 140s to 45s.
This requires you to run `npm install`.

Run grunt tasks concurrently

---

src/js/actions/documents.js
src/js/actions/history.js
src/js/actions/layers.js
src/js/actions/tool/type.js
src/js/actions/transform.js
src/js/stores/history.js
src/nls/root/strings.json

Updates `layers.resetIndex()` to only amend history.  This continues the effort started in a recent PR which did the same for resetLayers and resetBounds.  This required fixing the two instances that relied on resetIndex to *create* history state by explicitly creating a history state early. 
This adds a second flavor of the generic action to create history state called `newHistoryStateRogueSafe` which will amend a previous state IF it as create roguely (via PS initiated event, described as flow number 1 [here](https://github.com/adobe-photoshop/spaces-design/wiki/History-Subsystem)
Two other things...
- Convert "editArtboardEvent" handler to use new flux action
- Remove 'move' handler from type tool because it is redundant to the handler in actions/transform
Testing note: this affects …

History cleanup: fix resetIndex to only amend history

---

src/js/actions/layers.js

This fixes a regression in artboard creation, and layer ungrouping, both that seemed to have cropped up today.
Remove post verification of getLayerIDsForDocumentID (I think that was a copy paste error?)
two other other minor fixes in promise chains
cc: @pineapplespatula

Add transfer to getLayerIDsForDocumentID in two places

---

src/js/actions/policy.js
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/models/layerstructure.js

Our latest changes to mouse over highlighting did not consider leaf layers... to fix it, I've added layerstructure.selectableLeaves which is used twice in SuperselectOverlay. #3224
Also fixed a related issue, where due to priority being higher, `policy.beforeStartup` would run after `tools.beforeStartup` and overwrite the active tool's mouse mode, which broke highlighting until user switched tools.

Fix leaf highlighting

---

src/js/actions/menu.js
src/js/actions/search.js
src/js/actions/search/commands.js
src/js/actions/shortcuts.js
src/js/actions/tools.js
src/js/stores/search.js
src/nls/root/strings.json

With this PR, global shortcuts are added to the options that are pulled up when the search bar is prompted. 
1.) commands.js now provides the search provider for both Global Shortcuts and Menu Commands. One thing I need input on is whether we want to combine global shortcuts and menu commands under one header "Commands" in the UI, or keep them under separate labels. For now, they are separate.  
2.) Whenever we call .addShortcut, an extra parameter is being added for a name. This allows us to provide a name for the shortcut when it shows up in the UI. Currently, this is way we will distinguish between which global shortcuts will be listed as options in the search bar. For example, pressing "esc" is the global shortcut to dismiss a dialog, but we do not want this to appear in the search …

Added global shortcuts to the search options

---

src/js/main.js

This PR delays instantiating the flux controller (and hence initializing the stores) until `main.startup` is called. This addresses a bug in which the UI store would have incorrect initial state (`rootSize`) due to inspecting the DOM before styles had finished loading.
Addresses #3221.

Fix initial on-canvas UI size

---

src/js/actions/edit.js
src/js/actions/layers.js

@iwehrman (or anybody): should we take this opportunity to factor out the _verify* functions into their own file so they can be used across actions?  Or is this "hack" OK for now (exposing the function directly)?

Simple layer index validation as a post condition of undo/redo

---

src/js/actions/documents.js

This is related to watson 4074678 which is fixed as of playground-dev-mac 885.  When dragging two files from the OS into photoshop, previously only one of the subsequent `placeEvent` events would contain the layer ID.  We had a hack in place to fall back on updateDocument in this case. Now the layerID should be included by photoshop, so this PR removes the hack.
Note that in debug mode with post condition validation enabled, placing multiple objects will fail validation of the first N-1 events.  This is a false positive that can be ignored.

Remove a hack around photoshop placeEvent during multiple object placement

---

src/js/actions/application.js
src/js/actions/documents.js

Currently, we always wait until `application.afterStartup` to initialize the recent files list. But, this initialization blocks the no-doc UI because it relies on that list. This PR changes `documents.initActiveDocument` to transfer to `application.afterStartup` when there are no open documents. This effectively prioritizes loading the recent files list when loading the no-doc UI. This helps get the UI completely drawn slightly faster in this case.
CC @placegraphichere

Prioritize initializing the recent files list when there are no open documents

---

src/js/actions/libraries.js

We needed the path coming from `representation.getContentPath` to be passed to the next handler. So now we tap to create a new history state instead of `then`ing to it.

Tap for newHistoryState in libraries.applyLayerStyle

---

src/js/actions/documents.js
src/js/models/document.js
src/js/models/menubar.js
src/js/stores/document.js

This PR delays loading guide information until the guides are first made visible. This is a minor performance optimization. Addresses #3231.

Load guides lazily if they're not initially visible

---

bower.json
src/js/actions/libraries.js
src/js/actions/sampler.js
src/js/jsx/sections/libraries/assets/AssetPreviewImage.jsx
src/js/main.js

This is a backward-incompatible upgrade from Bluebird 2.x to 3.x. Details here: http://bluebirdjs.com/docs/new-in-bluebird-3.html
This should be reviewed and merged with adobe-photoshop/spaces-adapter#169.
Note that Bluebird 3 contains many new warnings, most of which seem useful and relevant. However, the source of these warnings is currently very hard to pin down (see petkaantonov/bluebird#861), so I've disabled the warnings for now. When the warnings are a little easier to deal with, we should of course address their causes and enable the warnings. For now I've only made the minimal required changes because I'd like to use some of the cancellation features of version 3 in a separate branch.

Upgrade to bluebird 3.x

---

src/js/models/documentindex.js

When we broke it apart, we must have missed a private variable name, causing the errors. 
Addresses #3268

Point to the right internal variable in documentindex

---

src/js/jsx/sections/style/ColorOverlayList.jsx
src/js/jsx/sections/style/ShadowList.jsx
src/js/jsx/sections/style/Stroke.jsx
src/js/jsx/sections/style/StrokeList.jsx
src/js/jsx/sections/style/VectorFill.jsx
src/js/jsx/shared/ColorPicker.jsx
src/nls/root/strings.json
src/style/panel.less
src/style/shared/color-input.less
src/style/shared/color-picker.less
src/style/shared/colors-medium.less

Color Picker sliders now housed entirely inside slider
- looks better, feels better, I think it is better
- Gradients have been adjusted to compensate for slider circle being inside the bar
- Opacity has been moved and tweaked to read inline with the other values and save space
Several Design Tweaks to Color swatch and Panels
- Swatch sizes are based around 8 grid (3.2rem instead of 3.4)
- Transparency background tiling improved (2x2 instead of off size)
- Alignment of colors, stroke, effects now go full-column so eyeball aligns with other left side icons (trash, download for example in other panels)
- Small change to box-shadow on the color swatch rounded corners to reduce white edges
- removed any 100th decimal point for rem sizes for reduced 1/2px possibilities
An incremental …

Color Picker and Color Swatch UI improvements

---

src/js/stores/shortcut.js

This fixes an awful off-by-one bug in the shortcut store's `REMOVE_SHORTCUT` handler that was preventing the most recently installed shortcut from ever being uninstalled. 
Addresses #3311.

Fix REMOVE_SHORTCUT handler

---

src/js/actions/tool/pen.js
src/js/actions/tools.js
src/js/events.js
src/js/stores/tool.js

This PR splits the tool-change dispatch into two parts:
1. an early, optimistic part that causes the view to re-render; and
2. a later part that contains the installed policy IDs.
This significantly improves perceived tool-activation time. Addresses #3313.

Faster tool activation

---

src/js/actions/documents.js
src/js/actions/menu.js
src/js/models/menubar.js
src/js/models/menuitem.js
src/js/models/menushortcut.js

This PR contains various menu fixes and cleanups. In particular: 
1. The maps (`rootMap` and `submenuMap`) are now derived properties, which reduces complexity and at least a few bugs by obviating their maintenance.
2. Many instances of mutable object references have been purged in favor strict immutability. In particular, there is now an immutable `MenuShortcut` model, instances of which may be referenced by `MenuItem` instances.
3. The `checked` property of `MenuItem` is now properly a boolean. Previously its range also variously, erroneously included 0, 1, "on" and "off".
4. Descriptor export has been tidied up so that unnecessary cruft is not submitted to the adapter when installing new menu definitions.
5. The open-document `MenuItem` instances no longer refer directly to document …

Menu bug-fix grab bag

---

src/js/jsx/Scrim.jsx

This must have slipped through the cracks during the drag&drop work. Scrim SCU never re-updated itself due to fact that both isDropTarget and nextProps.dropTarget being false. Now it will return false there if and only if both are true.
Addresses #3312, #3251, and bunch of other dupes.

Change Scrim SCU to skip isDropTarget when false

---

src/js/models/bounds.js

Fix for issue #3212 
Adjustment layers add effects to the layers below them and do not have a visual area, so their bounds should be ignored when calculating bounds of selected layers. Othwerise it will result in incorrect bounds (which is larger than the actual bounds) and break the transform feature.

Ignore adjustment layers when calculating layer bounds

---

src/js/jsx/sections/export/ExportList.jsx
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/sections/libraries/assets/AssetSection.jsx
src/js/jsx/shared/ColorPicker.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/TextInput.jsx
src/style/sections/libraries/libraries-section.less

1. Removed property expansion in rendering the inputs
2. `singleClick` and `live` seemingly accomplished the same goal. I renamed the property `doubleClickToEdit`, which is more informative than either of the other two, and set the default to `false`, since we only use this property in LayerFace and Library Assets
3. `TextInput` does not use or need the `type` property. Removed
4. `editable` and `disabled` also seemed to accomplish the same goal. Also, confusing with the `live` property. Condensed everything down to `disabled`
5. `preventHorizontalScrolling` is used by elements with `doubleClickToEdit={true}`. I set this to default to `true`, as it doesn't harm anything and then allows us to not have 2 dependent properties that must be set in the usage of TextInput (not preventing …

Cleanup of TextInput definition and usage

---

src/static/menu-actions.json

For the undo and redo menu commands, supply the "preserveFocus" switch in the payload.  This seems like a better experience, and addresses #3154.  I can't find any downside to this.
Better experience: For example, change the Width of a rectangle using the number input, then undo.  Retaining focus in the input seems natural
The bug fix: Previously when changing to a negative value of width (which clamps to 0.1), undoing it would cause a setSize AND an undo to be performed in rapid succession.

undo/redo menu commands use preserveFocus

---

src/js/actions/sampler.js

Fix for issue #3238 
`layerTree.leaves` ignores locked layers, which causes sampling locked layer failed (no sampler HUD displayed). I change the way of retrieving the top hit layer by getting the first id from `topHitLayerID`, which is the top most hit layer id.

Fix for sampling locked layer.

---

src/js/jsx/shared/TextInput.jsx

Fix for issue #3324 
`setState` is asynchronous, and it is not safe to read the state immediately after writting to it. In this case, `this.state.editing` (in line 162 ) may remian unchanged until the last `setState` get processed. Also, I don't think we need to check `this.state.editing` there as it is always set to true in this function, so I simply remove the checker to fix the issue.

Make dropdown list starts filtering for the first input character

---

src/js/actions/tools.js

This is the victim of bad indentation and bad scope.
`tools.beforeStartup` was setting a local `_borderPolicyChangeHandler` variable, instead of the file scoped one. So during onReset, we would call `removeListener` on various stores with an `undefined` handler, which would cause the store to drop ALL the listeners, turning the app unresponsive after a reset.
Addresses #3338

Set the correct border policy change handler, SCOPES

---

src/js/actions/tools.js

```
> [0,1] === [0,1]
< false
```
So we should use `_.isEqual` instead to check equality.
Doesn't really address #3328, but that one is a lot hairier than it looks.

Correctly check for inequality in transform matrices during policy reset

---

src/js/actions/ui.js

#3328 was happening, because we would call `ui.setTransform`, which would cause `Scrim.jsx` to unmount all overlays, which would cause the blink.
Looks like the dispatch was added by Ian as a fix for #2714, which is still open for other reasons, but as far as I can tell, the original reason of #2714 the dispatch was supposed to fix no longer happens. So I'm removing that code.
Blah.

Don't toggle overlays on ui.setTransform

---

src/js/actions/documents.js
src/js/actions/layers.js
src/js/actions/type.js
src/js/fluxcontroller.js
src/js/main.js
src/js/models/layerstructure.js
src/js/util/async-dependency-queue.js

This PR adds infrastructure for idle task execution:
1. Action receivers now have a `whenIdle` method, which enqueues the given action once the queue and JavaScript engine are idle.
2. Unselected layers of activated documents are now initialized when idle instead of at first-selection time. (Note that this does not yet initialize not-yet-activated documents.) The action `layers.initializeLayersBackground` calls `initializeLayers` on 50 uninitialized layers for a given document, and then calls itself again when idle if there are still uninitialized layers.
3. The font list is initialized when idle instead of first-text-layer-selection time.
The scenarios in which this makes a noticeable performance impact are not terribly common (selecting a big range of layers that have never been …

Idle initialization of the font list and unselected layers

---

bower.json
src/js/actions/ui.js
src/js/events.js
src/js/init-build.js
src/js/init.js
src/js/jsx/Main.jsx
src/js/main.js
src/js/models/menubar.js
src/js/stores/menu.js
src/js/stores/ui.js
src/js/util/ui.js
src/nls/root/menu.json
src/static/menu-actions.json
src/static/menu-mac.json
src/static/menu-win.json
src/style/main.less
src/style/panel.less

This PR makes it possible to change the UI color stop (theme) from Design Space via `Window > Color Theme`. Changing the color stop updates the UI theme, the titlebar color and also the artboard backdrop color. Notes:
1. Currently there is a Photoshop bug that prevents the artboard backdrop color from being updated until the canvas is panned or otherwise invalidated, but @jsbache is looking into that.
2. This moves the `color-stop__XYZ` class from `body` to the `Main` React element, which is now in charge of deciding what stop to render.
3. The stop is still fetched at application start time so that the first render has the correct theme, but it's also fetched in `ui.beforeStartup` so that the correct value can make it into the store. This is slightly redundant, but tolerable I think.
4. …

Color theme switching

---

Gruntfile.js
webpack.config.js

Simple fix for #3366, should make developing a bit faster.

Keep webpack watcher alive on compilation errors

---

src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/sections/style/Type.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/NumberInput.jsx
src/js/jsx/shared/TextInput.jsx

NumberInput usage was already pretty clean across Design Space. Similar to TextInput, I cleaned up some old properties, removed the property expansion that had existed, added a few notes for the different properties.
Additionally, moved everything to use `placeholder` as the property name for placeholder text. This is the HTML property name, NumberInput and TextInput had slightly varying names.

Small NumberInput cleanup, consistent property naming

---

src/js/models/exportasset.js

This is a tiny workaround for #3331. This does not fully address the issue. This pull request is against master; there will be a different PR against the `ps-16.1` branch.

Add 0.33 and 0.67 export scales [master]

---

src/js/models/exportasset.js

This is the companion to #3370 which updates the `ps-16.1` branch. Please test this against the shipping version of Photoshop 16.1.

Add 0.33 and 0.67 export scales [ps-16.1]

---

package.json
webpack.config.js

* You will receive a system notification everytime when webpack rebuilds. This might have better experience than reloading Design Space without knowing whether your change is integrated. 
* Syntax error will not abort `grunt debug`. It will send system notification instead.

Notify webpack build status via system notifications.

---

src/js/actions/tools.js

This is a bug I found while working on some other bug. On `tools.select`, we uninstall the active border policies. But we never re-install them with the new tool.
At first I tried listening to the tool store for change events, but this bug happens when you press V *while* in select tool already, so there is no difference in tool store that we can pick up on.
And I think it's reasonable for `superselectTool.select` to transfer to resetBorderPolicies. I know refactoring of all resetBorderPolicies into a listener was made to speed up our actions, but this is one place where it is necessary to call it directly, and it doesn't block anything else.

Listen to tool store as well for border policy renewal, and short circuit tools.select on same tool

---

webpack.config.js

By using the `inline-source-map` option https://webpack.github.io/docs/configuration.html#devtool
Tested on dev 926.

Make source map works for both internal and external dev tools.

---

src/js/actions/layers.js

Addresses #3258, PS would diligently send us the `make` event for the text layer under edit as we're closing the document, and we would enqueue the `resetLayers` action. And since the document was gone, things would go on the fritz. Now we check to see if the document model still exists, similar to what handleHistoryState does.

Short circuit resetLayers if passed in doc no longer exists

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/sections/export/ExportList.jsx
src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/sections/style/BlendMode.jsx
src/js/jsx/sections/style/Type.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Select.jsx

This PR made the following improvements:
* added `onHighlightedChange` callback to distinguish with `onChange`. The first one is fired when the current highlighted option is changed (mouse over or using arrow key), and the latter is fired when the user confirm the selection via mouse click / return / enter.
* Removed `live` `autoSelect ` prop, as you can use the `onHighlightedChange` instead. Also clean up some internal state.
* added `onClose` (you can search `Datalist~onClose` for details). With this we should be able to revet to initial selection if user close the list with selecting the highlighted option for Type/Blend mode, but things get more complicated when it comes to MIXED state, so I did not introduce the change in this PR yet.
* Better jsdoc for callbacks.
* Bug fix: disabled …

Datalist refactoring

---

src/js/main.js

`__FLUX_CONTROLLER__` was `undefined` before, because it wasn't initialized at assignment time.

Initialize debug snippet hook-ups correctly

---

src/js/actions/transform.js

Not entirely sure on the root cause of bug #3149, but from running my snippets I could see that it wasn't the bounds that were the culprit, but the transformation. We get `move` and `moveToArtboard` notifications, and we must be updating our transform before Photoshop finished settling the transform matrix.
I know this is vague, but updating the transform after the duplicate solves the problem.
Addresses #3149

Update transform after a duplicate drag

---

src/js/actions/documents.js
src/js/actions/edit.js
src/js/actions/guides.js
src/js/actions/history.js
src/js/actions/libraries.js
src/js/actions/sampler.js
src/js/actions/superselect.js
src/js/actions/tool/sampler.js
src/js/actions/transform.js
src/js/actions/ui.js
src/js/events.js
src/js/jsx/DocumentHeader.jsx
src/js/jsx/Main.jsx
src/js/jsx/PanelSet.jsx
src/js/jsx/Scrim.jsx
src/js/jsx/Toolbar.jsx
src/js/jsx/sections/transform/Size.jsx
src/js/jsx/sections/transform/TransformPanel.jsx
src/js/jsx/shared/Dialog.jsx
src/js/jsx/tools/GuidesOverlay.jsx
src/js/jsx/tools/PolicyOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/locks.js
src/js/models/tools/sampler.js
src/js/stores/index.js
src/js/stores/menu.js
src/js/stores/panel.js
src/js/stores/ui.js

This PR factors a panel action module, store and lock out from the existing UI action module, store and lock. This reduces contention for the UI lock somewhat at startup time, and also arguably also makes this  code a little easier to understand. In some cases it wasn't clear what state/action should go where, but the rule of thumb I tried to use was: if it has to do with the _window_ put it in the UI store, and if it has to do with a _panel_ put it in the panel store. (We should probably rename the UI store to something more appropriate, but I don't currently have a suggestion, so I left it alone.) This seems to shave ~100ms off startup time on my MBP due to reduced lock contention.

Factor panel actions/store/lock out of ui actions/store/lock

---

src/js/jsx/tools/SuperselectVectorMaskOverlay.jsx

fix Vector Mask HUD to use Panel Store instead of UI store for the cloak rect

---

package.json

This isn't as cool as it used to be with `bower`, which allowed semver strings to be supplied, but I think this is better than not supplying a version at all.  @volfied ?

Adding tag/version strings to adapter and generator-connection deps in package.json

---

src/js/actions/documents.js
src/js/actions/edit.js
src/js/actions/type.js

We had some JS_UI locks that were no longer valid, those are removed. In most cases, these locks are essentially redundant with the transfers, so it helps keep things cleaner.
Almost all type actions seemed unnecessary, but @pineapplespatula, am I missing something?
Also in edit.js, since we dispatch `panel.TOGGLE_OVERLAYS` now, changed the lock there, this was a dormant bug.

Clean up ui locks

---

src/js/actions/layers.js

**This PR requires dev >= 932 and Adapter PR https://github.com/adobe-photoshop/spaces-adapter/pull/174**
Fix issue #3271 that not all descendant groups are expanded when option-click a group.

Fix for expand/collapse all groups

---

Gruntfile.js

I was getting tired of trying to guess whether webpack actually rebuilt or if I was staring at the same [emitted] line from last time.
So now we run this empty watcher task in Grunt that prints out when a file in src has changed, and then webpack prints it's emitted, so we get a nice time stamp and changed files log before each incremental rebuild. Devs rejoice!
Btw, Webpack doesn't offer this!!! :-1:

Print changed files in the watcher

---

src/js/actions/sampler.js
src/js/jsx/tools/SamplerOverlay.jsx
src/js/models/layerstructure.js

This PR handles locked layers in different sampler scenarios:
1. select a locked layer: sampler is disabled (no HUD and mouse click), no sampler overlay
2. select multiple locked layers: the same as 1
3. selections of locked and unlocked layers: sampler is enabled, but only applies to unlocked layers. locked layers are excluded from the sampler overlay.
Fixes issue #3238

Handle locked layers when using the sampler tool

---

src/js/actions/documents.js
src/js/actions/index.js
src/js/actions/panel.js
src/js/actions/tools.js
src/js/actions/ui.js
src/js/jsx/DocumentHeader.jsx
src/js/jsx/IconBar.jsx
src/js/jsx/PanelSet.jsx
src/js/jsx/Toolbar.jsx
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/transform/TransformPanel.jsx
src/static/menu-actions.json

I actually had this in my branch for #3374 but I forgot to update the PR... Anyway, this just splits `actions.panel` out of `actions.ui` in the obvious way.

Factor actions.panel out of actions.ui

---

package.json
src/img/ico-loader.svg
src/js/jsx/Main.jsx
src/js/jsx/sections/export/ExportAllPanel.jsx
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/jsx/sections/libraries/assets/AssetPreviewImage.jsx
src/style/component-styles.less
src/style/shared/loader.less
webpack.config.js

SMIL SVG animations are being deprecated in Chrome in favor of CSS animations. Due to how we include SVGs (using the `<use>` tag), we cannot simply add CSS animations to the individual SVGs. I added some CSS in order to target the proper tag with the spinning loaded animation.
Since we are no longer pulling in the SVG in Main.jsx, I was able to remove that code as well as the url-loader, which @volfied says was only used for that.
Addresses #3384 and #3217

Replace SVG animated loader with a CSS animated one

---

src/js/jsx/sections/libraries/assets/AssetPreviewImage.jsx

Happens when you siwtch the column mode while `AssetPreviewImage` is fetching the rendition path, because the panels are reconstructed.
@volfied can you review since you are the first witness

Fix setState error thrown by AssetPreviewImage when switching column mode

---

src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/libraries/assets/AssetSection.jsx
src/js/jsx/shared/TextInput.jsx

This PR fixes issue that user can input empty layer name (issue #3265). 
I also found the same issue on libraries asset name, and it is fixed too.

Revert input to original value if the new layer/asset name is empty.

---

src/js/actions/libraries.js

Found this out while triaging a bug. BeforeStartup should return only when it's fully finished.

Return the full promise in libraries.beforeStartup

---

src/js/actions/libraries.js

Hopefully we'll figure out the root of this issue and remove this timeout check, but for now, adding this to get some repro cases from everyone.

Add a timeout warning to cc-lib-api load promise

---

src/js/actions/search/commands.js

The biggest change here is that I replaced parseInt() with our own parseNumber(). The if statement was not executing; after this the strings are accessed and rendered correctly. References #3408

Localized search strings fixed 

---

src/js/actions/groups.js
src/js/actions/layers.js
src/js/actions/shapes.js
src/js/actions/transform.js
src/js/actions/type.js
src/js/actions/typetool.js
src/js/models/layerstructure.js

This PR adds a post-verification step for selected layer bounds to actions that modify the bounds. It also "cleans up" (and hopefully doesn't break?) the layer transform event handler.
With this on, I immediately notice a few warnings. Some of them are "false" in that there are actions racing to update the bounds, and the post-verification step sometimes runs before a later action fixes things up. I also see a number of what appear to be true (if perhaps not severe?) warnings when transforming layers via the transform panel due to rounding issues. In any case, I think we should add these warnings first and triage them later.

Verify selected layer bounds

---

src/js/actions/transform.js
src/js/jsx/mixin/Scrubby.js
src/js/jsx/sections/style/Radius.jsx
src/js/jsx/sections/style/VectorFill.jsx
src/js/jsx/sections/transform/Position.jsx
src/js/jsx/sections/transform/Rotate.jsx
src/js/jsx/sections/transform/Size.jsx
src/js/jsx/sections/transform/TransformPanel.jsx
src/js/jsx/shared/Label.jsx

- Refactored Scrubby sliders, addressing #3286 and cleaning the code a bit
- Added scrubbiness to Width and Height labels, also coalescing the scrubs
- `_getMoveLayerActions` now uses absolute positioning if coalescing is true, but translate otherwise. This change was done in order to not change existing behavior, but have scrub behavior be correct.
This is still a WIP, while I hook up other controls, so I will be updating the PR with more files as I go along, but the core functionality, and example Scrub behavior should be reviewed in case I made some error that'll carry on to other scrub implementations.

Scrubbiness for more

---

src/js/jsx/sections/libraries/assets/AssetPreviewImage.jsx
src/js/jsx/shared/Select.jsx
src/js/jsx/tools/GuidesOverlay.jsx
src/js/jsx/tools/PolicyOverlay.jsx
src/js/jsx/tools/SamplerOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/jsx/tools/SuperselectVectorMaskOverlay.jsx

Addresses #3438, by removing isMounted calls across the board.
For D3 overlays, we rely on a flag, which is simple/stupid way.
For Select, we cancel the timeout callback using `window.clearTimeout`
For AssetPreviewImage, we cancel the promise, which is a no-op if it's already resolved.

Use cancellation and local flag to remove isMounted calls

---

src/js/actions/documents.js
src/js/actions/edit.js
src/js/actions/history.js
src/js/actions/layers.js
src/js/actions/panel.js
src/js/actions/superselect.js
src/js/actions/transform.js
src/js/actions/ui.js
src/js/events.js
src/js/fluxcontroller.js
src/js/stores/panel.js
src/js/stores/ui.js

This PR adds declarative management of overlay enablement by way of a new `hideOverlays` boolean action property. When actions like this are executing the overlays are disabled, and then they're re-enabled when all the `hideOverlay` actions are complete. This generally simplifies things (fewer explicit event dispatches) and allows for local reasoning ([as they say!](https://en.wikipedia.org/wiki/Separation_logic)) about the state of the overlays.
One exception to this simple handling is the "scroll" event handler. We use a debounced handler there, but we also want to hide the overlays immediately and not reveal them until after the debounced handler has run. I could imagine handling this case declaratively as well, but since it's currently a one-off I didn't bother.
Addresses #3450 and …

Declarative overlay management

---

Gruntfile.js
src/js/actions/menu.js
src/js/fluxcontroller.js
src/js/main.js
src/js/models/menubar.js
src/js/models/menuitem.js
src/js/util/global.js
src/js/util/headlights.js
src/js/util/log.js

This PR replaces `global.debug` and its references with the `__PG_DEBUG__` global variable, and instructs uglify to define it as `false`. This makes it easier (read: possible) for uglify to statically elide dead debugging code blocks. This eliminates redundant runtime checks and, for fun, also reduces the size of the compiled bundles by ~2k. This only affects the non-debug compiled builds.

Statically eliminate debug code

---

src/js/actions/ui.js

What it says! This is a minor cleanup and performance optimization. This cuts down the time to execute the center/zoom actions from ~80ms to ~30ms on my computer.
Addresses #1631.
~~Relies on #3457. Do not merge this until after #3457 is merged.~~

Eliminate redundant updateTransform calls in center/zoom actions

---

src/js/actions/documents.js
src/js/jsx/Guard.jsx

~~This relies on #3457, which should be merged before this.~~
This improves perceived document switching time by exploiting additional concurrency in `documents.selectDocument`. In particular, if the document is already initialized, we dispatch the event which causes the UI to update (which is expensive) in parallel with the Photoshop call to select the document (which is also expensive). The former still explicitly follows the latter in case the document has not yet been initialized.
I've tried to generally follow the sequential constraints strongly implied by the existing mask-cleanup actions, but I'm not completely sure that the ordering (or lackthereof) is entirely correct. In particular, I don't really understand why, on master, the call to `deselectAll` follows the Photoshop …

Faster document activation

---

src/js/actions/documents.js
src/js/actions/edit.js
src/js/actions/groups.js
src/js/actions/history.js
src/js/actions/index.js
src/js/actions/layers.js
src/js/actions/shapes.js
src/js/actions/transform.js
src/js/actions/type.js
src/js/actions/typetool.js
src/js/actions/verify/documents.js
src/js/actions/verify/layers.js
src/js/fluxcontroller.js

This PR converts the verification postconditions to quasi-actions and allows them to be specified symbolically with pathnames instead of just via direct references. This also moves all of the verification actions into new modules underneath `actions/verify` in an attempt to tidy up `actions.documents` and `actions.layers`.
Above I referred to these as quasi-actions because the controller doesn't quite treat them the same way when executing them as action post-conditions. In particular, their locks are ignored and they're always executed in parallel under the reasonable assumption that they are side-effect free. At some point, as @mcilroyc and I have discussed, it would be nice to have both `pre` and `post` action lists which are treated a little more like action transfers, for consistency …

Verification post-conditions as actions

---

src/js/jsx/sections/transform/AlignDistribute.jsx
src/js/models/layerstructure.js
src/js/models/menubar.js
src/static/menu-actions.json

This PR enables Align operations for artboards, given all other rules still apply.
We were using `hasStrictSelectedAncestors` for both Align and Distribute buttons. However, artboards are alignable ancestors as far as Photoshop is concerned, so I've broken the disabled checks for the UI buttons into two separate functions, and use a custom checker for Align, while still using the available functions for Distribute.
Also introduced a new menu rule: `no-nesting-except-artboards`, where nesting is allowed in selected layers as long as it's the artboard in the selection.
This addresses #3197.

No nesting except ABs rule, used for align commands

---

npm-shrinkwrap.json

Newer versions of react-addons got released, and because our shrinkwrap.json did not account for react-addons-perf, npm install would fail. This is a short term relief for this problem while we figure out how to move forward.

Manually add react-addons-perf shrinkwrap

---

src/js/actions/superselect.js

Addresses #1766 
Problem was, with first click on a double click, we would deselect, and then we would "fall through" which took group bounds into consideration, but not pixel areas that PS tells us.
So now, I make sure that layers we fall through into are actually covered by the click, which prevents the "reselect" of a group when double clicking an empty area within that group.

Take hitTest into consideration when falling through in double click

---

src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/libraries/assets/AssetSection.jsx
src/js/jsx/shared/ColorPicker.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/TextInput.jsx

* Instead of handling empty value in the handler, I added new option `allowEmpty` which will ignore empty value and skip the `onChange` handler.
* `onChange` was not clear before: it could be onChange handler or onCommit handler (when `continuous` prop is true). I reduce its scope by adding a new handle `onInputChange`, which also helps remove the `continuous` prop. Please see doc for difference of two handlers.
* bug fix: disallow empty value in ColorPicker. Otherwise inputting empty value will set color to black.
@volfied @mcilroyc can you review since you both reviewed #3410 ?

Better way to handle empty value in TextInput

---

webpack.config.js

This defines `process.env.NODE_ENV` to be `"development"` in debug builds and `"production" in compiled builds.` This is required for React to use a more optimized production mode in our compiled builds. 
Addresses #3486.

Define process.env.NODE_ENV for React

---

src/js/actions/superselect.js
src/js/jsx/sections/style/ColorOverlayList.jsx
src/js/jsx/sections/style/LayerBlendMode.jsx
src/js/jsx/sections/style/ShadowList.jsx
src/js/jsx/sections/style/StrokeList.jsx
src/js/util/headlights.js

This PR defers posting headlights events until the browser is idle, and removes the return value from `headlights.logEvent` to clarify that clients should not wait for any results. This is just a nit fix.

Delay headlights logging until browser is idle

---

src/js/actions/documents.js

`documents.open` currently transfers to `initActiveDocument` as well as `application.updateRecentFiles`. But, in `initActiveDocument` itself transfers to `updateRecentFiles` as well. This removes the former transfer for efficiency.

Remove redundant recent files update

---

src/js/fluxcontroller.js
src/js/util/log.js

This adds timestamps to the Chromium timeline corresponding to action and transfer execution boundaries. This only happens in debug mode. It results in little yellow lines in the timeline with tooltips to indicate what action is starting or finishing execution:
(Above, the line is next to the 3540ms time marker.)
More info: https://developer.chrome.com/devtools/docs/console-api#consoletimestamplabel

Timestamp actions and transfers

---

src/js/actions/groups.js

When I factored the `groups` actions out of `layers` actions, I think I lost @shaoshing's PR #3381 which makes correct use a `recursive` flag in the expand/collapse group action descriptor. 
Addresses #3482.

Fix recursive group expansion

---

src/js/main.js

Expose `ReactPerf` to the global for easier access of the React's profiling tool (https://facebook.github.io/react/docs/perf.html). Also removed `ReactPerf.start()`, otherwise it will measure our components endlessly (which will increase rendering time and memory usage in dev mode)

Expose ReactPerf and make it disabled by default.

---

package.json
src/js/actions/mask.js
src/js/models/layerstructure.js
src/js/models/menubar.js
src/nls/en/menu.json
src/nls/en/shortcuts-mac.json
src/nls/en/shortcuts-win.json
src/nls/en/strings.json
src/static/menu-actions.json
src/static/menu-mac.json
src/static/menu-win.json

requires https://github.com/adobe-photoshop/spaces-adapter/pull/175 
added new menu item
which is only enabled if you select two layers, one which is a vector shape and the other is a layer that allows for vector masks to be applied

Add Menu command to create a vector mask from a shape layer

---

src/js/jsx/search/SearchBar.jsx
src/style/search/search-bar.less
src/style/shared/dialog.less

References #3364 (@placegraphichere @iwehrman this might be of most interest to you guys) 
The most important parts of the PR I need approval on are: 
a.) The spacing and layout of the search bar now -- the positions of the search icon, the list icons, the category headers, and the search inquiry as the user is typing. 
For each color stop, check the colors of these with respect to the entire UI in that color stop: 
b.) The search icon
c.) The category headers
d.) The list icons
e.) The text after the list icons
f.) The ancestry text after each option 
As is, we are able to use the same less variable names for each of the items above, no matter the color stop. If changes are to be made to specific color stops, we will just need to add specific selectors targeting that color stop. Note -- …

Fix search bar colors in all color stops

---

src/js/actions/search/libraries.js
src/js/jsx/search/SearchBar.jsx
src/js/stores/search.js

This creates an option property on registered search modules for a custom string to be shown when no datalist options are available for that category in the search bar. If no value is passed in for the property, a default string will be applied and shown. 
Provides a better solution for some of the concerns raised in #3479. Once this is merged, then we can integrate Adobe Stock search in a much more stable way. 
Note: For some of the payloads, I have added the property `noOptionsString`. For others I have no provided the property. This is to prove to whoever tests this branch that both cases work. Also, a string has been added specific to no options when the Adobe Stock filter is applied. This is in preparation for #3479, as stated above.

Customizable "No options" messages for registered search modules

---

src/style/sections/layers/face.less
src/style/sections/libraries/libraries-section.less

This PR improves the browser rendering performance when mouse over layers/libraries list. 
Before the fix, mouse over a layer face will invalidate large number of unrelated layer faces and cause the browser to spend more time on rendering. The fix is removing the style `.face:hover {z-index: 99}`, and my test shows it doesn't cause other style issue.
After the fix
The cause is related to the flexbox view: with the combination of `flex-shrink:1` and `flex-grow:1`, it seems force the libraries list to reflow when mouse over its children. 
After the fix
Performance has a significant boost:
Before
After

Styles: more efficient browser rendering when mouse over (layers/libraries list)

---

src/js/actions/layers.js
src/js/actions/superselect.js
src/js/actions/transform.js
src/js/events.js
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/stores/tool.js

On `superselect.drag`, we first run the `superselect.click` action to select whatever layer the user might be clicking on / wants to move. This calls `layers.select`, which dispatches optimistically to update our models and re-render everything on React side, before drag happens. This causes a visible delay on drags until our models/views update to send the drag operation to Photoshop to start dragging. (On average, 200 ms)
With this change, I save the selected layer IDs in the tool store, and instead of dispatching a select event, we just store those IDs, and wait for the move event to reach us before grabbing these stored IDs and emitting a select event for them, updating our models. This saves us on average 150 ms, bringing down the drag action length to 50 ms before Photoshop starts …

Delay React render on drags by blocking dispatch

---

src/js/jsx/sections/style/Radius.jsx
src/js/stores/document.js

This is an experimental change with the goal of speeding up the `Radius` component. With this change, the `DocumentStore` will no longer emit "change" events that result from `RADII_CHANGED` dispatches. Instead, a new, single-purpose "radiusChanged" event is emitted, and only the `Radius` component listens for these events. Consequently, `RADII_CHANGED` dispatches can be handled in ~5ms instead of ~40ms on master. The savings comes from not having to virtually re-render much higher level components without any effect on the DOM. This only works because no other components care about the details of border radii; future React components that care about radii changes would have to listen to this event in addition to "change" events. So, the cost is some extra complexity. Is this additional …

Experiment: direct radius updates

---

package.json
src/js/jsx/tools/GuidesOverlay.jsx

On mouse over for the guide zones, we call a debounced function that delays highlight of the zone area by 30 ms. At the end of the delay, we use the `OS.getMousePosition` API to make sure the mouse is still over the zone, and otherwise cancel highlighting.
Addresses #3495
Requires https://github.com/adobe-photoshop/spaces-adapter/pull/181 and playground-dev-mac#971 or later. (CL 1059051))

Delay guide zone highlighting by debouncing

---

src/style/shared/dialog.less

References issue #3406 
Here is what the libraries dropdown looks like in each color stop. Note - the searchbar dropdown and the libraries dropdown are now the same color.

Changed the color of the libraries dropdown

---

src/js/jsx/tools/GuidesOverlay.jsx

While looking at Timeline, I realized that instead of comparing documents (which, admittedly, will always be different), we should just compare the `guidesVisible` property as it's the only thing we care about in GuidesOverlay. 
This change prevents guidesOverlay from being redrawn everytime something happens in the document, helps with performance a little.

Only check for document.guidesVisible in guidesOverlay

---

npm-shrinkwrap.json

This is the version of npm-shrinkwrap that was pushed to perforce with the sprint 3.1 release.

Updated npm-shrinkwrap for sprint 3.1

---

Gruntfile.js
src/js/actions/sampler.js
src/js/jsx/tools/PolicyOverlay.jsx
src/js/jsx/tools/SamplerOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx

- For superselect, policy and sampler overlays
- Correct the guides overlay existing SCU
- Change Sampler behavior so it highlgihts/samples leaf layers
- Re-add file watcher that just prints out file changes
Addresses #3491, and some sampler behavior issues.

D3 Overlay shouldComponentUpdate methods

---

src/js/actions/tools.js
src/js/jsx/tools/PolicyOverlay.jsx

For policy overlay, makes sure area trying to be drawn has positive width/height, skips otherwise, this problem manifested itself if user resized the PS app window to the smallest size possible.
For border policy change listener, we also listen to panel store for canvas rectangle size differences, which helps update all policies on resize, if top left stayed put.
Addresses #3351 and #3533

Policy area validation and border update on resize

---

src/js/actions/guides.js
src/js/jsx/tools/GuidesOverlay.jsx

This PR addresses two issues:
#3520 - we make sure to not highlight a guide zone while mouse is down.
#3270 - Increase the right/bottom policy area of guides by one pixel, this allows for symmetrical guide policy zones around the guide.

Guide fixes

---

package.json
src/js/actions/search/libraries.js

Fix: search for libraries graphic and hit return to place any graphic will result in error. 
I fixed this earlier but got distracted by a bluebird@3.0.6 bug (https://github.com/petkaantonov/bluebird/issues/841) which will silent unhandled errors and exceptions (error is not shown in the console). Now it has been fixed in 3.1.0 and I saw we are already using 3.1.1 in `npm-shrinkwrap.json`, so the problem no longer exists.

Search: placing libraries graphic results in error

---

src/js/actions/transform.js

We already debounce the handling of incoming moveToArtboard events from PS, but it currently uses the default delay of zero.  This seems to *occasionally* handle the first event in a series almost immediately, which results in an error in the case of option+drag artboard duplication (see #1613).
background...
After the end of an option+drag gesture, we receive a series of event from PS in this order: moveToArtboard(several), historyState, move.
moveToArtboard is handled simply by calling (debounced) `layers.resetIndex`.  An index reset will fail, however, if it is performed *after* the duplication has occurred in PS but *before* DS has handled the `move: newDuplicateSheets` event.
By adding a 100ms delay, we increase the chance that the the `resetIndex()` will be enqueued after the move …

Debounce moveToArtboard events with a nonzero delay

---

npm-shrinkwrap.json
package.json

1. The shrinkwrapped version of generator-connection was behind the version in package.json by a minor step. This updates the shrinkwrap to fix that. I don't know why npm chooses a different format for the "from" line in the shrinkwrap file sometimes.... I think it's harmless, but maybe @mcilroyc knows.
2. The the `babel-loader` dependency has been switched from @volfied's fork back to the main repository. I noticed a few weeks ago that the main project had incorporated the small fix from @volfied's branch. I also updated and tested the other babel dependencies while I was in there.

Babel, generator package updates

---

src/js/actions/superselect.js

Addresses #3547 
I made the modifier explicit, but forgot to set it during marquee select without shift.

Pass valid modifier to select from marqueeselect

---

src/js/jsx/sections/layers/DummyLayerFace.jsx
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/layers/LayerGroup.jsx
src/js/jsx/sections/layers/LayersGroup.jsx
src/js/jsx/sections/layers/LayersPanel.jsx
src/js/jsx/shared/Draggable.jsx
src/js/models/layer.js
src/js/stores/draganddrop.js
src/style/sections/layers/face.less
src/style/sections/layers/layers-section.less
src/style/shared/icons.less

This PR applies the following changes to the LayersPanel for better performance:
1. Convert to hierarchical layer structure so that we can make sure of browser rendering with CSS selectors, and thus eliminate the number of components needed to be updated when selecting/expanding a layer/group.
~~2. Stores layer's selected/expanded/visible attributes in LayerFace's internal state so that we can re-render (using `setState`) the component immediately without waiting for the flux cycle to be completed.~~
~~* Since we skip the flux cycle, the duration for a layer to react to a select event has been reduced from `100ms-400ms` to `less than 10ms`. (time is measured between `LayerFace#handleLayerClick` and `LayerFace#componentDidUpdate` within the same instance)~~
* With the hierarchical …

LayersPanel: hierarchical structure (part 1)

---

src/js/jsx/tools/ArtboardAdderOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx
src/js/models/tools/superselect.js

This is part of the performance improvement work for drag / on canvas interaction. The PR, by itself, does not really affect much, but as we move forward, we can make some gains by avoiding redrawing artboard adders during operations that would not change the artboard bounds. Or we can show them quicker than super select bounds making the app feel faster during artboard drags.
It's also a code clean up, which is nice.

Break apart artboardAdders from Select Overlay

---

src/js/actions/transform.js
src/js/jsx/sections/transform/Position.jsx

While scrubbing, we would wrongfully pass the `coalesce` flag as the `translate` flag into `_getMoveLayerActions`, this was causing all scrubs besides the first one to be absolute, and cause the issue seen in #3536 
To fix this issue, I first fixed the flag being passed while scrubbing. However, we still had the problems that if we set absolute position while scrubbing, we would get huge jumps as the layer is being scrubbed across artboard boundaries. So we now use the absolute bounds of the layer to calculate where to scrub it next, which correctly scrubs the layer across boundaries.
Addresses #3536

For scrubbing position, use absolute values

---

src/js/actions/menu.js
src/nls/en/menu.json
src/static/menu-actions.json
src/static/menu-mac.json
src/static/menu-win.json

This PR adds the ability to run layer panel performance test automatically. The test is accessiable via the menu item `Help > Test Layer Panel Performance`. It works for the flat and hierarchical structure in the LayerPanel. Here is a video of how it works https://www.dropbox.com/s/slalhpmhjjf9a9o/layer-panel-performance-test.mov?dl=0
Benefits of adding the task:
* It includes most testing scenarios (layer selection, art board selection, collapse/expand/visibility), and we can add more in the future.
* It is easeir for us to keep monitoring the performance in each spring.
* It saves time!
PS: would it be a good idae to move the developer snippets into the menu item as well? Maybe under the menu item call `Snippets`?

Automate layer panel performance test 

---

src/js/jsx/shared/NumberInput.jsx

Currently `NumberInput` throws if its value is a non-finite number. It's hard to prevent this from ever happening, so instead I'm just changing `NumberInput` to format a non-finite number as the empty string instead of throwing.
This is vaguely related to #3542.

Format non-finite values in NumberInput

---

src/js/jsx/sections/layers/LayerGroup.jsx
src/style/sections/layers/face.less

This fixes a classname typo in `LayerGroup`: `layers-group` should be `layer-group`.
Addresses #3559.

Fix layers panel width

---

Gruntfile.js

Addresses #3567, re-starting less watcher every time files change so it doesn't stop working after an error.
Since less does not do incremental re-build, there is no loss from restarting it.

Reload style watcher on changes so fails don't stop it

---

src/js/actions/documents.js
src/js/actions/layers.js
src/js/fluxcontroller.js

This PR is written to address #3541, but also implements a new action property. 
When user tries to quit Photoshop with dirty documents open, Photoshop pops up a modal dialog asking user if they want to save, not save, or cancel. There are multiple pathways this can take based on current open documents:
- Asterisks imply dirty document which will pop the prompt):
- Cases I don't account for are already handled well / are sub cases
1. Don't Save Untitled-2 | Cancel Untitled-1
In this case we get a close event from Photoshop with saving:no field for Untitled-2, and nothing else. Which at this point we dispose of the Untitled-2 document in our models and continue
2. Save Untitled-2 | Cancel Untitled-1
In this case, PS sends us a close event with saving:yes, a save event, and then another …

Handle cmd+q quit gracefully, and a new action flag to prevent reset on failure

---

Gruntfile.js

`outputSourceFiles` embeds the files into the sourcemap, but `sourceMapRootpath` actually tells it where to find the real files by going from `www/build` to `www`

Embed less sourcemaps with correct filepath

---

src/js/jsx/tools/ArtboardAdderOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx

Recent overlays changes caused them to throw in `shouldComponentUpdate` when the document state is null. This would happen when the controller resets, which causes all unhandled errors to be unrecoverable errors. The intent of this change is just to handle that additional case more gracefully.
Addresses #3561.

Anticipate null documents in SuperselectOverlay and ArtboardAdderOvelay

---

src/static/menu-win.json

There are two `Help > Test Reset Failure` entries on Windows. One should instead be `Help > Test Transfer Failure`.
Addresses #3579.
Over to @chadrolfs to test and merge.

Fix a duplicate menu entry on Windows.

---

src/js/jsx/mixin/Scrubby.js
src/js/jsx/sections/transform/Size.jsx
src/js/stores/application.js

#3563 is addressed with dcb4575, where we set the scrub value to null so we skip scrubbing it.
Either way, when scrub failed, the scrubby state would never be reset, causing extra mouse moves to keep things broken. 2a2cd70 fixes that by listening to `"reset"` events from application store, which gets emitted when controller resets.

Fix scrubbing on no layers / failures

---

src/js/jsx/shared/Dialog.jsx

References #3532 
With the previous version of bluebird, the call to `_addListeners()` was working asynchronously behind the scenes. Therefore the click events on the document header we handled before an event listener was added on the window. With this recent change to bluebird, https://github.com/petkaantonov/bluebird/issues/915, this became synchronous and the event listener on the window was added before the click to open the document header buttons were interpreted, resulting in the automatic toggle. This PR makes the addition of event listeners in the `componentDidUpdate` asynchronous again.

Put a timer on adding event listeners to the window

---

src/style/sections/layers/face.less

This PR fix the following style issues:
#3558 Descenders are clipped a little in Layer names on Retina. Happens on some layer elements when `font-size` is `@base-8` (when `device-width <= 1440px`). 
(the first line is not clipped, the sconed one is clipped slightly)
Another issue I found was that when element's height has decimal  (e.g. 25.1875px), their layout may be inconsistent in the screen. The picture below demonstrate the problem.
(when face's height is 25.1875px, the two folder icons has different relative position)
(If change height to 25px, everything looks fine.)
As a result, when double-click to edit title, some input will shift up by 1px.
I cannot find an easy way to fix this, except for using the `@media` rule to tweak the face's rem height for a rounded pixel number in …

Layer Panel: fix style issues

---

src/style/sections/libraries/libraries-section.less

**Fix for #3560**
Things that I tested and fixed (on both retian and non-retian screen with different font-size): 
Regular Asset
Color Theme (hover on preview to expand the colors)
Text Styles
Long title

Libraries panel: style issues

---

src/js/jsx/search/SearchBar.jsx

This works around what I assume is a Chromium bug that is causing the active text input to be blurred when the application window is activated. I don't know for sure that this is a Chromium bug, but I can't figure out any other reason why this would be happening. This is surely a SuperHack.
Addresses #3519 miserably.

SuperHack: force search UI to maintain focus when activating application

---

src/js/actions/type.js
src/js/stores/history.js

When we open multiple documents at once, we get multiple `open` and `historyState` events. When we try to handle the `historyState` events for the non-active documents, because they're not allocated/initialized yet, `_handleHistoryAmendment` fails. With this PR, we check to make sure the history we're amending is of the active document.
This works for the other documents, because during allocation we initialize history. Addresses #3510

Don't handle a history event if document is not current

---

src/js/actions/layers.js

This will require pg-dev-mac#996 or later builds. Also will require https://github.com/adobe-photoshop/spaces-adapter/pull/182, and will address #3246 and #3543 
I've exposed the Layers Panel option "Add "copy" to layer names" in Photoshop to us, and added an lib/application method to set it. I've also set it up as a auto-restored property. So now, when we option drag / duplicate layers, they don't get "copy" added to their names. #3543
Skip transform when placing SOs from library was already an existing preference in Photoshop, so I've added a new `setGlobalPreferences` API to lib/application to set it. This was a conscious decision, instead of having one function to set an option, for future uses of this API. #3246

Set appendCopy and skipTransform on startup

---

src/js/jsx/shared/ColorInput.jsx
src/js/jsx/shared/ColorPicker.jsx
src/js/jsx/shared/Dialog.jsx

Addresses #3281, problem was that we had Tab with no modifiers as a closer, but not shift+tab. And on `Map` focus, it was body that had the focus, so shift tab would be handled by active tool, while tab handled by dialog.
Then I realized, we don't allow same key shortcuts, but this was same key / different modifier. So I changed that code to support same key different modifier shortcuts, using modifiers as a way to come up with unique ID.

Support same key diff. modifier dialog closers, add shift+tab to ColorInput

---

src/style/panel.less

References issue #3549 
Before: 
After: 
One thing to note, is that the padding in other panels changes slightly with this fix. Can @placegraphichere or @designedbyscience give their opinion about the change? I made this image to try and show the slight difference. If this doesn't help, you can just check out toggling the CSS change on this branch.

Padding on formlines first-child removed to fix clipping of color swatch

---

src/js/jsx/shared/Dialog.jsx
src/style/panel.less
src/style/shared/color-picker.less
src/style/shared/dialog.less

Using [CSS Mixin Guards](http://lesscss.org/features/#mixin-guards-feature), we now position the dialog pointer either at the top or the bottom of color picker dialog.
Also, addressing #3550, we now position the color picker correctly when there is no room below the clicked color input and color picker appears above it.

Add bottom dialog pointer to color picker and fix positioning

---

src/js/jsx/sections/transform/Position.jsx
src/js/jsx/sections/transform/Size.jsx
src/js/jsx/sections/transform/TransformPanel.jsx

The `Size` and `Position` components currently blink when first showing a document. This is entirely due to quirks in their `shouldComponentUpdate` methods. In particular, it seems like the components weren't rendering until their first state _change_ after mounting.
@volfied: I ended up removing a bunch of code that you wrote recently, so I'd like your feedback on this to make sure I didn't screw something up. I've removed some of your optimizations because I think they were partially responsible for the blinking.
Addresses #3613.

Prevent Size and Position components from blinking on mount

---

src/js/actions/groups.js
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/layers/LayerGroup.jsx
src/js/stores/document.js
src/js/util/svg.js
src/style/sections/layers/face.less
src/style/shared/icons.less

**Update**
* rebased with master
* description is updated to inlcude result of latest experiment
This PR aims to make the layer selection/expand/collapse/visibility more responsive (UI wise) by promoting the browser's rendering event. Take layer selection as example. Below is the Timeline when select a layer. As you can see, before the browser starts rendering, it has to wait 70ms - 80ms for the Flux cycle and React rendering to be completed. So, what if we use `setState` to trigger React rendering directly, so that the browser can start rendering as soon as possible?
Below is the Timeline after applying the `setState` method. We store the layer selection/expand/visibility in component state, and update the state directly to skip the Flux cycle. The result is as expected, the browser …

Layer Panel: faster layer face selection/expansion/visibility

---

src/js/stores/document.js

What it says! This was causing an unrecoverable error when opening the search dialog with an uninitialized document (i.e., one for which `document.layers === null`).
@shaoshing: can you let me know if this looks like the right fix?
Addresses #3619.

Do not attempt to dispatch layer-selection-changed events for uninitialized documents

---

src/js/jsx/sections/layers/LayerGroup.jsx

If you create a document and close it immediately, it will raise an error complaining `this.forceUpdate` not allowed on a unmounted instance. This PR fixes the error by cancelling the timer callback when the instance is unmounted.

LayerPanel: cancel forceUpdate when LayerGroup will unmount.

---

Gruntfile.js
package.json
webpack.config.js

**needs `npm install`**
Show notification for LESS task. It will show both successful and error message.
* Show timestamp in the WebPack's successful build message. This would be easier to know when the latest build is done if you make changes constantly.

Grunt: better notification for WebPack and LESS

---

src/js/jsx/sections/layers/DummyLayerFace.jsx
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/shared/Draggable.jsx
src/js/jsx/shared/Droppable.jsx
src/js/models/layerstructure.js

This PR fixes the drag-and-drop in the LayerPanel by changing the type of drag target in the `Draggable` component from `Layer` model to layer id, so that the `Draggable` won't hold a stale layer model. 
More details about the fix:
In the recent layer panel PR, `LayerFace` stores some `Layer` model attributes (`selected/expanded/visible`) in its state. When it receive a new layer prop, it will skip rendering if the change is the same as its state. As a result, the `Draggable` instance will hold the old version because the component is not re-rendered. This makes it fail when `Draggable` component needs to check whether it is the drag target when a drag event starts, which will always return false. The solution is to switch to layer id, which is a number and will never stale.

LayerPanel: fix broken layer face drag-and-drop

---

src/js/jsx/sections/export/ExportAllPanel.jsx
src/js/jsx/sections/export/ExportList.jsx
src/js/jsx/shared/NumberInput.jsx
src/js/models/exportasset.js
src/js/util/nls.js

This provides extremely basic number localization for `NumberInput` mainly, and also for the scale values used by export. The display of numbers is handled by the browser by the [`toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) method of `Number` objects, and relies on the browser's locale being correctly set, as it has been. The somewhat more complicated issue is parsing arithmetic expressions in `NumberInput`. This is handled with a hack: we determine if the browser wants to format decimals with a comma, and if so we swap out commas for periods and semicolons (which often separate arguments to mathematical functions in the same locale) with commas. Hence, you `sum(1,5; 2,5)` is translated to `sum(1.5, 2.5)` before …

Basic number localization

---

src/js/actions/tool/superselect/type.js
src/js/actions/tool/type.js
src/js/models/tools/pen.js
src/js/models/tools/sampler.js
src/js/models/tools/type.js

Not the best change, but gets things back to working status.
Maybe instead of dot separated paths, we should use nested paths to camelCasedNestedPaths... but then there are chances of clashes.
For now, this will fix #3644

Correctly reference nested action paths

---

src/js/actions/history.js
src/js/actions/layers.js
src/js/actions/panel.js
src/js/actions/transform.js
src/js/actions/type.js
src/js/actions/ui.js
src/js/fluxcontroller.js
src/js/jsx/DocumentHeader.jsx
src/js/jsx/Guard.jsx
src/js/jsx/IconBar.jsx
src/js/jsx/PanelSet.jsx
src/js/jsx/Toolbar.jsx
src/js/util/synchronization.js

After realizing that in Mar 19, 2015, we got rid of the async waiting nature of our own debounce function, and it's identical to `_.debounce`, this cleans it up so we use lodash.
Addresses #3639, @iwehrman please review. @mcilroyc it would be nice to have your eyes on this, as well.

Get rid of synchronization.debounce and use _.debounce instead

---

Gruntfile.js
package.json

**`npm install` is required**
This PR uses the `grunt-check-dependencies` package to add the ability to check for package dependencies before running some grunt tasks, and will inform you when `npm install` is needed. Below are the tasks that will check dependencies:
* grunt test (npm test)
* grunt compile
* grunt debug
* when running `grunt debug`, it will keep monitoring the `package.json` file for change of dependencies.

Make grunt tasks check for dependencies

---

src/js/actions/application.js
src/js/actions/documents.js
src/js/actions/export.js
src/js/actions/groups.js
src/js/actions/guides.js
src/js/actions/help.js
src/js/actions/history.js
src/js/actions/keyevents.js
src/js/actions/layers.js
src/js/actions/libraries.js
src/js/actions/menu.js
src/js/actions/panel.js
src/js/actions/policy.js
src/js/actions/search.js
src/js/actions/shortcuts.js
src/js/actions/superselect.js
src/js/actions/tools.js
src/js/actions/transform.js
src/js/actions/type.js
src/js/actions/typetool.js
src/js/actions/ui.js
src/js/fluxcontroller.js

1. Mark most actions that do not write PS doc or app state as modal safe. Playing `get` commands _should_ work even when PS is in a modal state, and the adapter should not require those to be played with the `canExecuteWhileModal` flag. Small consequence: you can now pan the canvas without ending the modal state.
2. Make `setGroupExpansion` and `setColorStop` modal safe even though they do write PS doc state.
3. Instrument the controller so that it fails fast if there are duplicate read/write locks, or unexpected action properties, both of which are indicative of typos. 
4. Fix a few typos which caused both of the aforementioned bug instances, and also add a few other missing locks.

More modal-safe actions

---

src/js/jsx/sections/style/ColorOverlayList.jsx
src/js/jsx/sections/style/EffectsPanel.jsx
src/js/jsx/sections/style/ShadowList.jsx
src/js/jsx/sections/style/StrokeList.jsx
src/js/jsx/sections/style/UnsupportedEffectList.jsx
src/js/jsx/tools/SamplerOverlay.jsx

Addresses #3650, we were using `actions.layerEffects`, but file name is `layereffects` so casing had to be changed.

Use actions.layereffects with correct casing

---

src/js/actions/menu.js
src/js/actions/tool/superselect/type.js
src/js/actions/tool/type.js
src/js/fluxcontroller.js

Continuation of #3645, this will allow us to refer to actions by dot separated path names in `this.flux.actions` object.
So instead of `this.flux.actions["tool.type"].select`, we can type `this.flux.actions.tool.type.select`

Allow nested actions

---

src/js/jsx/tools/SuperselectOverlay.jsx

Looks like we got a little over zealous with the lint cleanup in #3640 and removed the marquee rectangles from the overlay, breaking marquee select.
This re-adds them, addressing #3653

Re-add marquee rectangles

---

src/js/jsx/mixin/Focusable.js
src/js/jsx/sections/layers/LayerFace.jsx

When the name of the layer in a LayerFace was clicked on, we would immediately call `OS.acquireKeyboardFocus` due to the `mousedown` listener in Focusable mixin (which is the mixin of TextInput showing layer name). But we would never call `OS.releaseKeyboardFocus` because those were only called on commit/cancel/finish methods.
For TextInputs like layer name, we don't want to acquire focus unless the user double clicks to start editing. We instead acquire focus on `_beginEdit` function which is what happens when user double clicks.
Addresses #3581

Add acquireFocusOnMouseDown prop to Focusable, set to false in LayerFace

---

src/js/actions/shapes.js
src/js/actions/transform.js
src/js/actions/type.js
src/js/stores/menu.js

1. Set the `isUserInteractionCommand` batchPlay option when coalescing `transform.setRadius`, `shapes.setFill*`, `shapes.setStroke*` and `type.setType*` actions. (I think this only affects the color picker and the radius slider, at the moment, since the other actions that could be affected by this change aren't ever coalesced.) I can't actually measure any performance difference with this change, but @jsbache wants it and I want him to be happy! 
2. Also, just because, double the menu-update debounce timeout from 200ms to 400ms to make it less likely to trigger during user interactions. 200ms seems a little optimistic for a lot of computers...

User interaction batchPlay option

---

src/js/jsx/PanelSet.jsx
src/js/jsx/sections/layers/LayerFace.jsx

With this PR, properties on click events are used to infer modifier state instead of using the modifier store, which is less reliable. It's less reliable because it relies on receiving `adapterFlagsChanged` events, which can't be dispatched when the application is not active. So, e.g., if another window is activate, and then some modifiers are held, and then the Design Space window is activated, the modifier store's state will be incorrect. In some cases, like `SuperSelectOverlay`, we actually do want to use the functionality provided by the modifier store because we want to re-render views when modifier state changes in absence of other mouse events. But, in the case of the `LayerFace` and `IconBar` click handlers below, it's both simpler and more reliable to use the modifier properties …

More reliable click modifier tracking

---

src/js/actions/mask.js
src/js/actions/tools.js
src/js/jsx/DocumentHeader.jsx
src/js/models/layerstructure.js
src/js/models/menubar.js

Adding code to the two paths into vector masks so that they have the same results depending upon the layer selection

Unify mask commands to all have the same result

---

src/js/fluxcontroller.js

This PR adds the following improvement to the debug messages:
* Highlight slow actions (completion time > 100ms)
* ~~Includes stack trace in a console group when message `Executing Action ...`, which make it easier to know where triggers the action.~~

Better console debugging messages

---

src/js/actions/documents.js

This PR adds a guard against null document model references in `document.close`. This is necessary because the menu system can't guarantee that this action will only be played when a valid document model exists because the menu system's rebuilds are debounced. See discussion in #3678. We should be on the lookout for other instances of this unsound assumption.
Addresses #3678.

Guard against null documents in documents.close

---

src/js/jsx/sections/style/VectorFill.jsx
src/js/jsx/shared/Dialog.jsx

1. Implement `shouldComponentUpdate` in `Dialog`. This is not as easy as it should be because `Dialog` components render in two passes. To make this possible, I've added a flag to each instance of which makes it possible to track the progress of these two-pass renders.
2. Fix the `shouldComponentUpdate` implementations in Fill.jsx. We were passing in a plain objects as the `fill` prop to the components defined in `Fill.jsx`, but testing for equality with `Immutable.is`. (It would be nice if this threw an error?) I worked around the problem by just creating a custom struct to hold the properties in that previously mutable object.
Both of these components were being rendered unnecessarily when calling `initializeBackgroundLayers`. The former was also causing _all_ dialogs to re-render …

Two shouldComponentUpdate fixes

---

src/js/stores/document.js
src/js/stores/history.js

When `timetravel` event is fired, ColorInput requires its prop to be updated so that it can re-render based on the current props, and the update is triggered by document store's `change` event. Below is the expected working order:
1. Undo command executed
2. document store emits `change` event
3. ColorInput receives updated props, but skip rendering
4. history store emits `timetravel` event
5. ColorInput handles `timetravel` and re-render 
With our recent optimization on browser paint, document store's `change` event is delayed to allow browser starts rendering ASAP, and this hack disrupts the order, and now it becomes: `1 - 4 - 5 - 2 - 3`
This PR use promise to ensure the correct event order.
Fix for #3658
@mcilroyc can you review and let me know if you approve the fix?

Bug fix: document `change` event should be emitted before history `timetravel`

---

src/js/models/menubar.js

When updating the open documents menu list, do not *error* if no document is set to active in the app store.
When opening several documents simultaneously via the "Open.." menu, the first `open` event from photoshop is for an *inactive* document.  That event is handled by `allocateDocument` which causes an updateDocument, which in turn emits an event that will cause the menu items to refresh.  At this time, the application store may not be aware of the current document.  Previously, in the menu code, the `updateOpenDocuments` method would throw an error if a current document was not provided.  It seems safe to me to relax that requirement, and tolerate the no-active-document situation here. 
This is a simple fix for #3679

Menu 'open documents' refresh process should not throw error when there's no active document

---

src/js/actions/libraries.js
src/js/jsx/PanelSet.jsx
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/libraries/LibraryBar.jsx
src/js/stores/library.js
src/js/stores/panel.js
src/style/main.less
src/style/panel.less
src/style/shared/icons.less
src/style/shared/link-list.less
src/style/shared/loader.less
src/style/shared/title-header.less

This PR includes the following optimizations on CC Libraries to improve performance.
* Defer CC Libraries loading/rendering process to improve startup performance. Before, CC Libraries is loaded in the `beforeStartup` callback, which slows down the startup process and triggers libraries panel rendering, which slow down the startup further. This process can be deferred as the chance of using the librarise panel right after startup is small. 
* Prevent the Libraries panel DOM from removing when closing the last document. Otherwise, we have to waste time in rendering the panel again when creating a new document.
* Pre-render the Libraries panel in no-doc state. While in no-doc state, the libraries panel can be pre-rendered (by React) when the data is ready. 
Below is the result of the …

document load time: CC Libraries optimization

---

src/js/actions/panel.js
src/js/stores/panel.js

This PR makes three changes to avoid unnecessary action calls to update the cloaking rectangle in the adapter:
1. Factor `commitPanelSizes` out of `updatePanelSizes`. The former commits changes to the adapter, while the latter only updates the bounds in the panel store. 
2. Do not call `commitPanelSizes` until all panels have been initialized. This should make the calls that happen before `beforeStartup` less costly.
3. Once all panels are initialized, use a debounced version of `commitPanelSizes` to avoid committing unnecessarily. This should avoid repeatedly committing stale panel size values when, e.g., dragging a window from one display to another.
@shaoshing: I haven't convinced myself that this leads to any concrete improvements. Can you take a look and make a judgement call about …

Reduce cost of updating panel sizes

---

src/js/actions/transform.js

Addresses #3505 
We set autoExpandDisabled during our action play, but as soon as we finish and re-set it, PS handles canvas shift, and sends us the event, which we debounce. Because we debounce it, if we were to call swap again, we would be trying to swap layers at a wrong location, and cause the bug. So now as part of swap, we call resetBounds on all selected layers. This doesn't add that much to action time, so didn't seem like a bad performance hit.

Reset bounds of layers that moved during swap, as canvas shift can happen

---

src/js/init.js
src/js/jsx/sections/export/ExportAllPanel.jsx
src/js/jsx/sections/export/ExportList.jsx
src/js/jsx/shared/NumberInput.jsx
src/js/models/exportasset.js
src/js/util/nls.js

This PR improves our number localization so that the operating system-specified decimal separator is used, and not just the locale default. This is done by fetch `localeInfo` from Photoshop before starting the application, and using that to provide util-level information about the correct decimal separator and a decimal-formatting function. I did it this way because a) this setting can't change without restarting Photoshop, and b) it turned out to be extremely challenging to put this into our usual Flux data flow (i.e., it would have required major refactorings, and it just didn't seem to be worth the effort).
To test, manually change your locale's decimal separator this like:
And then restart Photoshop .
Addresses #3136.

Number localization with os-specified decimal separator

---

src/js/jsx/PanelSet.jsx
src/js/jsx/sections/export/ExportPanel.jsx
src/js/jsx/sections/layers/LayersPanel.jsx
src/js/jsx/sections/libraries/LibrariesPanel.jsx
src/js/jsx/sections/nodoc/ArtboardPresets.jsx
src/js/jsx/sections/nodoc/RecentFiles.jsx
src/js/jsx/sections/style/AppearancePanel.jsx
src/js/jsx/sections/style/EffectsPanel.jsx
src/js/jsx/sections/transform/Position.jsx
src/js/jsx/sections/transform/Size.jsx
src/js/jsx/sections/transform/TransformPanel.jsx
src/style/panel.less
src/style/sections/libraries/libraries-section.less
src/style/sections/style/style-section.less
src/style/shared/icons.less

This PR improves the performance of switching initialized documents by optimizing the rendering process. When switching documents, we toggle the CSS class "section__active" to show panels of active document and hide the rest of the panels. Before, to just toggle one class, we have to re-render all the panels (`Transform, Appearance, Effects, Export, Layers`), which adds extra time to the switching. To improve this, this PR wraps the panel components with a `div`, and toggle the panels by change the class of the `div`. In this way, the panels can remain unchanged.
| | Before | After | Diff |
| --- | --- | --- | --- |
| switch from an empty doc to vermilion | 364ms | **256ms** | -108ms |
| switch from vermilion to an empty doc | 199ms | **89ms** | -110ms |
(both documents are already …

Improve performance of switching initialized documents

---

npm-shrinkwrap.json
package.json

what it says.  ~~Anyone concerned with the esprima-fb bit?~~
update: I nuked node_modules and started over... and the esprima-fb dep went away.

Updated shrinkwrap with new spaces-adapter version (including semver dep)

---

src/static/menu-win.json

This PR updates the windows menu config to include the two new debugging items. 
Tested with Windows dev build 1065.

Update menu for Windows

---

src/js/actions/libraries.js

This is in preparation for the next libraries API. As it is, will be a no-op.

Insert token in vulcan callback for libraries API if exists

---

src/js/jsx/IconBar.jsx
src/js/jsx/PanelSet.jsx

The structure of the `PanelSet` recently changed to include the `IconBar`, but the bounds arithmetic did not change along with it. This resolves the discrepancy by putting the `PanelSet` in charge of reporting both `panelBounds` and `iconBounds`. As a nice side effect, there is one fewer component calling `updatePanelSizes` all the time.
Addresses #3703.

Fix panel bounds measurement

---

src/js/jsx/search/SearchBar.jsx
src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/libraries/LibraryList.jsx
src/js/jsx/shared/ColorPicker.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/Dialog.jsx
src/js/jsx/shared/TextInput.jsx

This PR makes the following changes to the event-handling interfaces of `TextInput` and `Datalist`:
1. `TextInput` now has a single `onInput` prop in place of the previous `onInputChange` and `onDOMChange` props. Those props were only ever being called one after another as a result of a `change` event on the `input` element, so this simplifies the interface and changes the name to be more meaningful and correct.
2. `Datalist` now has an `onInput` prop that replaces the previous `onInputChange` prop. The latter was a confusing name in relation to the semantics of that prop, which was and is that it is triggered as a result of the child `TextInput`'s `onInput` event. 
Besides updating the usage of these components and fixing up some stale comments, this also makes a change to the …

TextInput and Datalist event handling fixes

---

src/js/jsx/sections/transform/Size.jsx

We're currently specifying a blanket minimum layers size of 0.1, but that actually only works for vectors or groups that contain only vectors. This PR changes the minimum size to be 1 unless all selected leaf layers are vector layers; in that case, go with the existing minimum size of 0.1.
Addresses #3153.

Use minimum layer size of 1 unless all selected leaves are vectors

---

src/js/actions/search.js
src/js/actions/search/libraries.js
src/js/actions/search/stock.js
src/js/jsx/Search.jsx
src/js/jsx/search/SearchBar.jsx
src/js/jsx/shared/Datalist.jsx
src/js/jsx/shared/TextInput.jsx
src/js/stores/search.js
src/nls/en/strings.json

This PR adds the option to search Adobe Stock via the search bar. (JIRA PS-656) 
It also solves issues #3610, #3529, #3524. 
Testing: 
- The category "Adobe Stock" is now added to the search bar as a potential category the user can choose
- If the user selects the category "Adobe Stock", the user can: 
> - Enter a string, press `enter` and adobestock.com will open to the results page of the user search 
> - Enter no string, press `enter` and adobestock.com homepage will open 
> - Enter a string, click the option `Search Adobe Stock...` and adobestock.com will open to the results page of the user search 
> - Enter no string, click the option `Search Adobe Stock...` and adobestock.com homepage will open
- If the user selects any or no category within the search bar: 
>  - If the user types …

Integrate Adobe Stock search into search bar within DS

---

src/js/actions/layers.js
src/js/actions/verify/layers.js
src/js/models/layerstructure.js
src/js/models/radii.js

This PR does few things:
- Changes `_boundsPropertyForLayer` function to `_boundsPropertiesForLayer`, allowing for multiple property keys to be attached to a layer bound. This allows us to get `keyOriginType` as well for vector layers on `resetBounds` calls.
- When a vector layer is rotated, it's keyOriginType changes as well, which tells us the layer can no longer set corner radii. So on `resetBounds` call, we update both of those properties, also in `verifySelectedLayerBounds`
Addresses #3444

Update keyOriginType for layers on handleLayerTransform

---

src/js/jsx/tools/GuidesOverlay.jsx
src/js/jsx/tools/SamplerOverlay.jsx
src/js/jsx/tools/SuperselectOverlay.jsx

What it says! This cuts down on some pointless, wasteful calls to `hitTest`.
Addresses #3732.

Only update overlays when pointer is inside canvas bounds

---

src/js/actions/tools.js

Beautiful edge case, create artboard guide, deselect all layers, then select a layer with no bounds.
We would only check for bounds, and a layer with no bounds would be equal to no layers selected. So now we also check to see if top selected ancestors differ, since they drive which artboard guides show.
Adresses #3736

Compare top selected ancestors for border policy reset

---

src/js/actions/layers.js
src/js/models/bounds.js
src/js/models/layerstructure.js

In a situation where a vector mask was created for a group, we would still be calculating it's bounds using the child bounds. But the transform controls show for the union of child bounds and the mask bounds.
This PR makes sure we get the required properties for the group bounds, and use them in bounds calculations.
Addresses #3704 and potentially other mask related group bounds issues

Consider vector masks of groups in their bounds

---

src/js/jsx/sections/style/Type.jsx

References issue #3701 
Before: 
After:

Added class label to opacity for Japanese styling

---

src/js/jsx/sections/layers/LayerFace.jsx
src/js/jsx/sections/layers/LayerGroup.jsx

Fix for issue #3375
I have to move the `scroll-into-view` logic into the `LayerGroup` as ordering `LayerFace` within the same group will not re-render the layer face, which makes it difficult to know when to scroll the panel as the `LayerFace#componentDidUpdate` is not called. This also result in a cleaner solution for scrolling the panel. Now the scroll works for:
* order layer via menu items (e.g. Bring Forward `cmd+]`)
* undo/redo layer order

Scroll layers panel when layer is invisible due to change of position

---

src/js/jsx/PanelSet.jsx
src/style/main.less
src/style/panel.less

This PR promote the panel's fade-in animation so that they are displayed faster during startup. Before, the animation starts when the `FluxController` emits `ready` event. In general, the event is emitted 150ms - 300ms later after the `PanelSet` completes rendering for the active document, as the event has to wait until all `beforeStartpu` callbacks are completed. So, instead of waiting for the `ready` event, the `PanelSet` now starts the animation when its active document's content are flushed to the DOM.
1) the panel content are flushed to the DOM. 2) `Main` component receives the `ready` event.
| panel fade-in starts | Before | After | Diff |
| --- | --- | --- | --- |
| empty document | 1690ms | 1530ms | -160ms |
| vermilion | 2630ms | 2410ms | -220ms |

Show document panels earlier by promoting the fade-in animation.

---

src/js/actions/transform.js
src/js/jsx/sections/transform/TransformPanel.jsx

Starting with pg-dev-mac#1104, we will get an array named `moveToArtboard` inside the `move` and `duplicateNewSheets` commands that will tell us all the layers that changed artboards with structure: `[ { layer: #, artboard: # }, ...]`
Whoever is reviewing, please do a quick testing as well (I've done some but it's nice to have extra eyes)
Also addresses #3748

Stop listening to moveToArtboard events, and look for it in move events

---

src/js/jsx/sections/layers/LayerGroup.jsx

This PR checks if the current document has selected layers before scrolling into it at initial display. This will fix for issue #3764

Bug fix: check existence of layer before scrolling into it

---

src/js/actions/search/commands.js
src/js/actions/tools.js
src/js/jsx/ToolbarIcon.jsx
src/js/models/tools/ellipse.js
src/js/models/tools/pen.js
src/js/models/tools/rectangle.js
src/js/models/tools/sampler.js
src/js/models/tools/superselect.js
src/js/models/tools/superselect/type.js
src/js/models/tools/superselect/vector.js
src/js/models/tools/type.js
src/nls/en/strings.json

References issue #3737 
- All tools have "Tool" succeeding their individual names 
- "Super Select" --> "Select Tool"
- "Vector Mask" --> "Vector Mask Mode"
- "Super Select Vector" --> "Direct Selection Tool"
- "Direct Selection Tool" is not an option in Search > Global Shortcuts if we are not in Vector Mode

Changes to search bar: edits the tool names, direct selection vector option conditional

---

package.json

@jsbache found today that node 0.10.x is insufficient for `grunt compile`. This simple change should cause `npm install` to fail with a clear error message when when using a node version below 4.2.3. (I arbitrarily picked that version because it was LTS for a while, and there doesn't seem to be a good reason to force developers to upgrade to anything newer at this point.)
Addresses #3780. 
More info: http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html

Require at least node version 4.2.3 when running npm install.

---

src/js/jsx/mixin/Scrubby.js

Prevent the default browser behavior during scrubby mousemove events to avoid selecting text within input elements. This seems to work for me, but please test! CC @chadrolfs 
Addresses #3266.

Avoid selecting text during scrub

---

src/js/actions/documents.js

Fix for issue #3655. Before, when selecting an uninitialized document, `ui.updateTransform` was executed before the selected document was set as the current document, and causes the action to read transform of the previously selected document wrongly. This PR changed the execution order to make sure `ui.updateTransform` is executed before `documents.updateDocument`.

Update transform after the selected document is initialized.

---

src/js/jsx/sections/export/ExportAllPanel.jsx

This is a narrow fix for the problem reported in #3710.  I made this fix awhile ago but sat on it while continuing to research the "make it just work" proposal/discussion from that issue.  But, I think it makes sense to just squash this bug, and backlog the fancy proposal.
If there is nothing to export, disable the button (in the modal export dialog)

Disable the export button on the export modal panel if nothing to export

---

src/js/actions/type.js
src/js/jsx/sections/style/Type.jsx
src/js/jsx/shared/Datalist.jsx

This makes the type face and weight `Datalist` instances coalescable, by mixing the `Coalesce` mixin into the `Type` component. This means that when you open one of those datalists and browse through the entries, you'll only create one history state and don't have to undo a thousand times to get back to your original font.
I'm embarrassed that we shipped with this last time. It turned out to be a lot easier to fix than I thought... 
Addresses #3667.

Coalesce type face and weight changes

---

src/js/actions/documents.js

Fix for issue #3635 by applying the similar workaround that we have for the `make` handler (https://github.com/adobe-photoshop/spaces-design/blob/master/src/js/actions/layers.js#L1905)

Delay adding new layer for 'drag' event.

---

src/js/actions/type.js

When coalescing type `postScript` changes, we aren't currently informing the history store. I believe this fixes the problem, as per @mcilroyc's suggestion. 
Addresses #3667 again.

Preserve history state when coalescing type face/weight changes

---

src/js/actions/documents.js

This is my second attempt on fixing issue #3635. It turns out that the error is caused by dropping image onto an empty artboard, which triggers layer replacement. Although the new layer is replaced by an existing layer, PS still emitting message with the incorrect ID of the replaced layer, and that's why the `layers.addLayers` failed. This PR checks if the id from `event.layerID` exists before adding a new layer.

Bug fix: error when dragging image from browser onto empty artboard.

---

src/js/jsx/shared/Label.jsx

Temporarily disable the scrubby feature to address issue #3591
(I am keeping the scrub handles in the components (`Radius`, `VectorFill`, `Position`, `Rotate`, and `Size`) for future reference.)

Disable the scrubby feature

---

src/js/jsx/help/FirstLaunch.jsx
src/nls/en/strings.json
src/style/help/first-launch.less

This adds a Mac-only advertisement paragraph to the last screen in the first-launch dialog for Adobe Experience Design CC. On Windows it will still look like this:
But on Mac it will now look like this:

Add a Mac-only ad for Adobe Xd in the first-launch dialog

---

src/js/actions/transform.js

This is a first-down hail-mary pass trying to address #3804.
I confirmed that photoshop is acting strangely when asked to set an artboard's absolute position by X/Y coords.  But, while troubleshooting, I tried using the alternate method of moving layers that is used when entering X or Y coords in the Position inputs.  This alternate flavor of `_getMoveLayerActions` uses an underlying `move` command instead of `transform`.
It seems to work fine.  But I half-expect someone to remember a situation that I haven't considered which breaks it.
Note: If this alternate approach *is* sufficient, then it seems like one of the code paths in `_getMoveLayerActions` may effectively be dead now.
Bonus Bug: I also found in the existing version that the width of an artboard was sometimes slowly growing …

Translate instead of setting absolute position when swapping layers

---

src/js/actions/layers.js
src/js/actions/shapes.js
src/js/jsx/sections/style/AppearanceProperties.jsx
src/js/jsx/sections/style/Opacity.jsx

Addresses #3807 by setting the `layer.changeColors` action to be modal safe.
This PR also disables the Opacity element when in modal text edit state because attempting to set opacity while modal will throw an error.

When in modal text edit state, allow color change and disable opacity input

---

src/js/actions/menu.js
src/js/jsx/tools/SamplerOverlay.jsx

DS will fail to recover from action failure if the currently selected tool is sampler. This is because the `SamplerOverlay` is unable to read the selected layers in its `shouldComponentUpdate` function, as the current document is unavailable during resetting. This PR fixes the issue by checking the existence of the current document. I also checked the other tools to make sure doing the same checking in their SCU function. 
Fix: https://jira.corp.adobe.com/browse/PS-2645
Mitigate: https://github.com/adobe-photoshop/spaces-design/issues/3108 (it should not be a ship blocker now)

Fix unrecoverable state after failure in sampling LLSO

---

src/index-debug.html
src/index.html
src/nls/de/strings.json
src/nls/en/strings.json
src/nls/fr/strings.json
src/nls/ja/strings.json
src/style/help/first-launch.less

1. Fixes a problem with how webpack was merging dictionaries at compile time that prevented non-English translations from showing in the first-launch dialog.
2. Fix some layout issues in the last slide in French and German.
3. Remove a dangling space in the `{ADOBE_XD}` separator in the Japanese translation that caused `undefined` to trickle into the last slide.
Addresses #3819 and partially addresses #3820.

First-launch dialog localization fixes

---

src/js/jsx/sections/transform/Rotate.jsx

There was an extra div around the rotation tool icon that caused the label and input to split into 2 different lines. References #3825 
Before:
After:

Removed extra div around rotation tool icon

---

src/js/actions/menu.js
src/js/jsx/help/FirstLaunch.jsx
src/nls/en/strings.json
src/static/menu-actions.json

This PR localizes the two dynamic links we have to Design Space help page and Experience Design page. To achieve one of these, I've added a `localize` parameter to url payload in those menu items so DS knows to localize the string instead of directly trying to go to the provided URL. I couldn't do a string matching here, because we use this with libraries panel for certain actions as well.
@iwehrman please review.

Localize designspace help and adobe_xd go urls

---

src/style/main.less
src/style/panel.less
src/style/sections/style/style-section.less

Issue #3824 
There was a minimum height on multiple panels in the properties panel. This pushed the entire UI upwards to accommodate each of them. Media queries now detect the app height and adjust the panels accordingly.

Properties panel adjustable heights to accommodate app resizing
